// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: social/guild/v1/guild.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuildService_ListGuilds_FullMethodName              = "/guild.v1.GuildService/ListGuilds"
	GuildService_CreateGuild_FullMethodName             = "/guild.v1.GuildService/CreateGuild"
	GuildService_JoinGuild_FullMethodName               = "/guild.v1.GuildService/JoinGuild"
	GuildService_LeaveGuild_FullMethodName              = "/guild.v1.GuildService/LeaveGuild"
	GuildService_InviteToGuild_FullMethodName           = "/guild.v1.GuildService/InviteToGuild"
	GuildService_ListGuildMembers_FullMethodName        = "/guild.v1.GuildService/ListGuildMembers"
	GuildService_ListGuildEvents_FullMethodName         = "/guild.v1.GuildService/ListGuildEvents"
	GuildService_CreateGuildEvent_FullMethodName        = "/guild.v1.GuildService/CreateGuildEvent"
	GuildService_DeleteGuild_FullMethodName             = "/guild.v1.GuildService/DeleteGuild"
	GuildService_GetGuildPulse_FullMethodName           = "/guild.v1.GuildService/GetGuildPulse"
	GuildService_GetGuildMemberStats_FullMethodName     = "/guild.v1.GuildService/GetGuildMemberStats"
	GuildService_GetActiveGuildChallenge_FullMethodName = "/guild.v1.GuildService/GetActiveGuildChallenge"
	GuildService_CreateGuildChallenge_FullMethodName    = "/guild.v1.GuildService/CreateGuildChallenge"
)

// GuildServiceClient is the client API for GuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuildServiceClient interface {
	ListGuilds(ctx context.Context, in *ListGuildsRequest, opts ...grpc.CallOption) (*ListGuildsResponse, error)
	CreateGuild(ctx context.Context, in *CreateGuildRequest, opts ...grpc.CallOption) (*GuildResponse, error)
	JoinGuild(ctx context.Context, in *JoinGuildRequest, opts ...grpc.CallOption) (*JoinGuildResponse, error)
	LeaveGuild(ctx context.Context, in *LeaveGuildRequest, opts ...grpc.CallOption) (*LeaveGuildResponse, error)
	InviteToGuild(ctx context.Context, in *InviteToGuildRequest, opts ...grpc.CallOption) (*InviteToGuildResponse, error)
	ListGuildMembers(ctx context.Context, in *ListGuildMembersRequest, opts ...grpc.CallOption) (*ListGuildMembersResponse, error)
	ListGuildEvents(ctx context.Context, in *ListGuildEventsRequest, opts ...grpc.CallOption) (*ListGuildEventsResponse, error)
	CreateGuildEvent(ctx context.Context, in *CreateGuildEventRequest, opts ...grpc.CallOption) (*CreateGuildEventResponse, error)
	DeleteGuild(ctx context.Context, in *DeleteGuildRequest, opts ...grpc.CallOption) (*DeleteGuildResponse, error)
	GetGuildPulse(ctx context.Context, in *GetGuildPulseRequest, opts ...grpc.CallOption) (*GetGuildPulseResponse, error)
	GetGuildMemberStats(ctx context.Context, in *GetGuildMemberStatsRequest, opts ...grpc.CallOption) (*GetGuildMemberStatsResponse, error)
	GetActiveGuildChallenge(ctx context.Context, in *GetActiveGuildChallengeRequest, opts ...grpc.CallOption) (*GetActiveGuildChallengeResponse, error)
	CreateGuildChallenge(ctx context.Context, in *CreateGuildChallengeRequest, opts ...grpc.CallOption) (*CreateGuildChallengeResponse, error)
}

type guildServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGuildServiceClient(cc grpc.ClientConnInterface) GuildServiceClient {
	return &guildServiceClient{cc}
}

func (c *guildServiceClient) ListGuilds(ctx context.Context, in *ListGuildsRequest, opts ...grpc.CallOption) (*ListGuildsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGuildsResponse)
	err := c.cc.Invoke(ctx, GuildService_ListGuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) CreateGuild(ctx context.Context, in *CreateGuildRequest, opts ...grpc.CallOption) (*GuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildResponse)
	err := c.cc.Invoke(ctx, GuildService_CreateGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) JoinGuild(ctx context.Context, in *JoinGuildRequest, opts ...grpc.CallOption) (*JoinGuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGuildResponse)
	err := c.cc.Invoke(ctx, GuildService_JoinGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) LeaveGuild(ctx context.Context, in *LeaveGuildRequest, opts ...grpc.CallOption) (*LeaveGuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveGuildResponse)
	err := c.cc.Invoke(ctx, GuildService_LeaveGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) InviteToGuild(ctx context.Context, in *InviteToGuildRequest, opts ...grpc.CallOption) (*InviteToGuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteToGuildResponse)
	err := c.cc.Invoke(ctx, GuildService_InviteToGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) ListGuildMembers(ctx context.Context, in *ListGuildMembersRequest, opts ...grpc.CallOption) (*ListGuildMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGuildMembersResponse)
	err := c.cc.Invoke(ctx, GuildService_ListGuildMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) ListGuildEvents(ctx context.Context, in *ListGuildEventsRequest, opts ...grpc.CallOption) (*ListGuildEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGuildEventsResponse)
	err := c.cc.Invoke(ctx, GuildService_ListGuildEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) CreateGuildEvent(ctx context.Context, in *CreateGuildEventRequest, opts ...grpc.CallOption) (*CreateGuildEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGuildEventResponse)
	err := c.cc.Invoke(ctx, GuildService_CreateGuildEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) DeleteGuild(ctx context.Context, in *DeleteGuildRequest, opts ...grpc.CallOption) (*DeleteGuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGuildResponse)
	err := c.cc.Invoke(ctx, GuildService_DeleteGuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) GetGuildPulse(ctx context.Context, in *GetGuildPulseRequest, opts ...grpc.CallOption) (*GetGuildPulseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGuildPulseResponse)
	err := c.cc.Invoke(ctx, GuildService_GetGuildPulse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) GetGuildMemberStats(ctx context.Context, in *GetGuildMemberStatsRequest, opts ...grpc.CallOption) (*GetGuildMemberStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGuildMemberStatsResponse)
	err := c.cc.Invoke(ctx, GuildService_GetGuildMemberStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) GetActiveGuildChallenge(ctx context.Context, in *GetActiveGuildChallengeRequest, opts ...grpc.CallOption) (*GetActiveGuildChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveGuildChallengeResponse)
	err := c.cc.Invoke(ctx, GuildService_GetActiveGuildChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildServiceClient) CreateGuildChallenge(ctx context.Context, in *CreateGuildChallengeRequest, opts ...grpc.CallOption) (*CreateGuildChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGuildChallengeResponse)
	err := c.cc.Invoke(ctx, GuildService_CreateGuildChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuildServiceServer is the server API for GuildService service.
// All implementations must embed UnimplementedGuildServiceServer
// for forward compatibility.
type GuildServiceServer interface {
	ListGuilds(context.Context, *ListGuildsRequest) (*ListGuildsResponse, error)
	CreateGuild(context.Context, *CreateGuildRequest) (*GuildResponse, error)
	JoinGuild(context.Context, *JoinGuildRequest) (*JoinGuildResponse, error)
	LeaveGuild(context.Context, *LeaveGuildRequest) (*LeaveGuildResponse, error)
	InviteToGuild(context.Context, *InviteToGuildRequest) (*InviteToGuildResponse, error)
	ListGuildMembers(context.Context, *ListGuildMembersRequest) (*ListGuildMembersResponse, error)
	ListGuildEvents(context.Context, *ListGuildEventsRequest) (*ListGuildEventsResponse, error)
	CreateGuildEvent(context.Context, *CreateGuildEventRequest) (*CreateGuildEventResponse, error)
	DeleteGuild(context.Context, *DeleteGuildRequest) (*DeleteGuildResponse, error)
	GetGuildPulse(context.Context, *GetGuildPulseRequest) (*GetGuildPulseResponse, error)
	GetGuildMemberStats(context.Context, *GetGuildMemberStatsRequest) (*GetGuildMemberStatsResponse, error)
	GetActiveGuildChallenge(context.Context, *GetActiveGuildChallengeRequest) (*GetActiveGuildChallengeResponse, error)
	CreateGuildChallenge(context.Context, *CreateGuildChallengeRequest) (*CreateGuildChallengeResponse, error)
	mustEmbedUnimplementedGuildServiceServer()
}

// UnimplementedGuildServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuildServiceServer struct{}

func (UnimplementedGuildServiceServer) ListGuilds(context.Context, *ListGuildsRequest) (*ListGuildsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGuilds not implemented")
}
func (UnimplementedGuildServiceServer) CreateGuild(context.Context, *CreateGuildRequest) (*GuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGuild not implemented")
}
func (UnimplementedGuildServiceServer) JoinGuild(context.Context, *JoinGuildRequest) (*JoinGuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGuild not implemented")
}
func (UnimplementedGuildServiceServer) LeaveGuild(context.Context, *LeaveGuildRequest) (*LeaveGuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGuild not implemented")
}
func (UnimplementedGuildServiceServer) InviteToGuild(context.Context, *InviteToGuildRequest) (*InviteToGuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteToGuild not implemented")
}
func (UnimplementedGuildServiceServer) ListGuildMembers(context.Context, *ListGuildMembersRequest) (*ListGuildMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGuildMembers not implemented")
}
func (UnimplementedGuildServiceServer) ListGuildEvents(context.Context, *ListGuildEventsRequest) (*ListGuildEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGuildEvents not implemented")
}
func (UnimplementedGuildServiceServer) CreateGuildEvent(context.Context, *CreateGuildEventRequest) (*CreateGuildEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGuildEvent not implemented")
}
func (UnimplementedGuildServiceServer) DeleteGuild(context.Context, *DeleteGuildRequest) (*DeleteGuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGuild not implemented")
}
func (UnimplementedGuildServiceServer) GetGuildPulse(context.Context, *GetGuildPulseRequest) (*GetGuildPulseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGuildPulse not implemented")
}
func (UnimplementedGuildServiceServer) GetGuildMemberStats(context.Context, *GetGuildMemberStatsRequest) (*GetGuildMemberStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGuildMemberStats not implemented")
}
func (UnimplementedGuildServiceServer) GetActiveGuildChallenge(context.Context, *GetActiveGuildChallengeRequest) (*GetActiveGuildChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveGuildChallenge not implemented")
}
func (UnimplementedGuildServiceServer) CreateGuildChallenge(context.Context, *CreateGuildChallengeRequest) (*CreateGuildChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGuildChallenge not implemented")
}
func (UnimplementedGuildServiceServer) mustEmbedUnimplementedGuildServiceServer() {}
func (UnimplementedGuildServiceServer) testEmbeddedByValue()                      {}

// UnsafeGuildServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuildServiceServer will
// result in compilation errors.
type UnsafeGuildServiceServer interface {
	mustEmbedUnimplementedGuildServiceServer()
}

func RegisterGuildServiceServer(s grpc.ServiceRegistrar, srv GuildServiceServer) {
	// If the following call panics, it indicates UnimplementedGuildServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuildService_ServiceDesc, srv)
}

func _GuildService_ListGuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).ListGuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_ListGuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).ListGuilds(ctx, req.(*ListGuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_CreateGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).CreateGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_CreateGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).CreateGuild(ctx, req.(*CreateGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_JoinGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).JoinGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_JoinGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).JoinGuild(ctx, req.(*JoinGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_LeaveGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).LeaveGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_LeaveGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).LeaveGuild(ctx, req.(*LeaveGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_InviteToGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteToGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).InviteToGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_InviteToGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).InviteToGuild(ctx, req.(*InviteToGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_ListGuildMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGuildMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).ListGuildMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_ListGuildMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).ListGuildMembers(ctx, req.(*ListGuildMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_ListGuildEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGuildEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).ListGuildEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_ListGuildEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).ListGuildEvents(ctx, req.(*ListGuildEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_CreateGuildEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGuildEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).CreateGuildEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_CreateGuildEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).CreateGuildEvent(ctx, req.(*CreateGuildEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_DeleteGuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).DeleteGuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_DeleteGuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).DeleteGuild(ctx, req.(*DeleteGuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_GetGuildPulse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildPulseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).GetGuildPulse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_GetGuildPulse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).GetGuildPulse(ctx, req.(*GetGuildPulseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_GetGuildMemberStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildMemberStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).GetGuildMemberStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_GetGuildMemberStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).GetGuildMemberStats(ctx, req.(*GetGuildMemberStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_GetActiveGuildChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveGuildChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).GetActiveGuildChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_GetActiveGuildChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).GetActiveGuildChallenge(ctx, req.(*GetActiveGuildChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuildService_CreateGuildChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGuildChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServiceServer).CreateGuildChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildService_CreateGuildChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServiceServer).CreateGuildChallenge(ctx, req.(*CreateGuildChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuildService_ServiceDesc is the grpc.ServiceDesc for GuildService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuildService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guild.v1.GuildService",
	HandlerType: (*GuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGuilds",
			Handler:    _GuildService_ListGuilds_Handler,
		},
		{
			MethodName: "CreateGuild",
			Handler:    _GuildService_CreateGuild_Handler,
		},
		{
			MethodName: "JoinGuild",
			Handler:    _GuildService_JoinGuild_Handler,
		},
		{
			MethodName: "LeaveGuild",
			Handler:    _GuildService_LeaveGuild_Handler,
		},
		{
			MethodName: "InviteToGuild",
			Handler:    _GuildService_InviteToGuild_Handler,
		},
		{
			MethodName: "ListGuildMembers",
			Handler:    _GuildService_ListGuildMembers_Handler,
		},
		{
			MethodName: "ListGuildEvents",
			Handler:    _GuildService_ListGuildEvents_Handler,
		},
		{
			MethodName: "CreateGuildEvent",
			Handler:    _GuildService_CreateGuildEvent_Handler,
		},
		{
			MethodName: "DeleteGuild",
			Handler:    _GuildService_DeleteGuild_Handler,
		},
		{
			MethodName: "GetGuildPulse",
			Handler:    _GuildService_GetGuildPulse_Handler,
		},
		{
			MethodName: "GetGuildMemberStats",
			Handler:    _GuildService_GetGuildMemberStats_Handler,
		},
		{
			MethodName: "GetActiveGuildChallenge",
			Handler:    _GuildService_GetActiveGuildChallenge_Handler,
		},
		{
			MethodName: "CreateGuildChallenge",
			Handler:    _GuildService_CreateGuildChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social/guild/v1/guild.proto",
}
