// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: core/hub/v1/hub.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHubServiceGetOverview = "/hub.v1.HubService/GetOverview"

type HubServiceHTTPServer interface {
	GetOverview(context.Context, *GetOverviewRequest) (*GetOverviewResponse, error)
}

func RegisterHubServiceHTTPServer(s *http.Server, srv HubServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/hub/overview", _HubService_GetOverview0_HTTP_Handler(srv))
}

func _HubService_GetOverview0_HTTP_Handler(srv HubServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOverviewRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHubServiceGetOverview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOverview(ctx, req.(*GetOverviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOverviewResponse)
		return ctx.Result(200, reply)
	}
}

type HubServiceHTTPClient interface {
	GetOverview(ctx context.Context, req *GetOverviewRequest, opts ...http.CallOption) (rsp *GetOverviewResponse, err error)
}

type HubServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHubServiceHTTPClient(client *http.Client) HubServiceHTTPClient {
	return &HubServiceHTTPClientImpl{client}
}

func (c *HubServiceHTTPClientImpl) GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...http.CallOption) (*GetOverviewResponse, error) {
	var out GetOverviewResponse
	pattern := "/api/v1/hub/overview"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHubServiceGetOverview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
