import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

type Region = { id: string; xPct: number; yPct: number; label: string; i18nKey: string }

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const svgPath = process.argv[2] ? resolve(root, process.argv[2]) : resolve(root, 'front/public/img/big_map.svg')
const outPath = process.argv[3]
  ? resolve(root, process.argv[3])
  : resolve(root, 'front/src/pages/AtlasWorldPage/model/atlasRegions.generated.ts')

const svg = readFileSync(svgPath, 'utf8')
const viewBox = svg.match(/viewBox=["']\s*([\d.-]+)\s+([\d.-]+)\s+([\d.-]+)\s+([\d.-]+)\s*["']/)
const minX = Number(viewBox?.[1] ?? 0)
const minY = Number(viewBox?.[2] ?? 0)
const width = Number(viewBox?.[3] ?? 1024)
const height = Number(viewBox?.[4] ?? 1024)

const fallback: Region[] = [
  { id: 'north_peaks', xPct: 32, yPct: 24, label: 'Северные вершины', i18nKey: 'atlasWorld.region.north_peaks' },
  { id: 'capital_market', xPct: 50, yPct: 50, label: 'Столичный рынок', i18nKey: 'atlasWorld.region.capital_market' },
  { id: 'east_archipelago', xPct: 78, yPct: 60, label: 'Восточный архипелаг', i18nKey: 'atlasWorld.region.east_archipelago' },
  { id: 'south_dunes', xPct: 44, yPct: 80, label: 'Южные дюны', i18nKey: 'atlasWorld.region.south_dunes' },
  { id: 'west_caverns', xPct: 18, yPct: 58, label: 'Западные пещеры', i18nKey: 'atlasWorld.region.west_caverns' },
]

const regions = [...svg.matchAll(/<g\b[^>]*\bid=["']region-([^"']+)["'][^>]*>([\s\S]*?)<\/g>/g)].map((m) => {
  const id = slug(m[1])
  const body = m[2]
  const groupOpen = m[0].match(/^<g\b[^>]*>/)?.[0] ?? ''
  const explicitX = attrNumber(groupOpen, 'data-centroid-x')
  const explicitY = attrNumber(groupOpen, 'data-centroid-y')
  const nums = [...body.matchAll(/[-+]?\d*\.?\d+(?:e[-+]?\d+)?/gi)].map((n) => Number(n[0])).filter(Number.isFinite)
  const xs = nums.filter((_, i) => i % 2 === 0)
  const ys = nums.filter((_, i) => i % 2 === 1)
  const cx = explicitX ?? (xs.length ? avg(xs) : minX + width / 2)
  const cy = explicitY ?? (ys.length ? avg(ys) : minY + height / 2)
  const label = decodeEntities((body.match(/<text\b[^>]*>([\s\S]*?)<\/text>/)?.[1] ?? id).replace(/<[^>]+>/g, '').trim())
  return {
    id,
    xPct: round(((cx - minX) / width) * 100),
    yPct: round(((cy - minY) / height) * 100),
    label,
    i18nKey: `atlasWorld.region.${id}`,
  }
})

const data = regions.length ? regions : fallback
writeFileSync(outPath, `// Generated by scripts/svg-extract.ts. Keep the shape stable for AtlasWorldPage.
export const ATLAS_REGIONS = ${JSON.stringify(data, null, 2).replace(/"([^"]+)":/g, '$1:')} as const
`)
console.log(`wrote ${data.length} atlas regions to ${outPath}`)
if (!regions.length) console.warn(`no <g id="region-*"> groups found in ${svgPath}; wrote curated fallback regions`)

function avg(v: number[]) { return v.reduce((s, n) => s + n, 0) / v.length }
function round(v: number) { return Math.round(v * 100) / 100 }
function slug(v: string) { return v.trim().replace(/^region-/, '').replace(/-/g, '_') }
function attrNumber(tag: string, name: string) {
  const m = tag.match(new RegExp(`${name}=["']([^"']+)["']`))
  if (!m) return undefined
  const n = Number(m[1])
  return Number.isFinite(n) ? n : undefined
}
function decodeEntities(v: string) {
  return v.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'")
}
