// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: social/inbox/v1/inbox.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ThreadKind classifies inbox threads so the client can route icons, avatars
// and interactivity (only some kinds accept user replies).
type ThreadKind int32

const (
	ThreadKind_THREAD_KIND_UNSPECIFIED ThreadKind = 0
	ThreadKind_THREAD_KIND_MENTOR      ThreadKind = 1 // AI or human mentor feedback
	ThreadKind_THREAD_KIND_GUILD       ThreadKind = 2 // Guild bot / raid notices
	ThreadKind_THREAD_KIND_SYSTEM      ThreadKind = 3 // Level-up, achievement, season events
	ThreadKind_THREAD_KIND_DUEL        ThreadKind = 4 // Post-match chat with opponent
	ThreadKind_THREAD_KIND_CHALLENGE   ThreadKind = 5 // Async friend challenge conversation
	ThreadKind_THREAD_KIND_FRIEND      ThreadKind = 6 // Direct friend-to-friend mail
)

// Enum value maps for ThreadKind.
var (
	ThreadKind_name = map[int32]string{
		0: "THREAD_KIND_UNSPECIFIED",
		1: "THREAD_KIND_MENTOR",
		2: "THREAD_KIND_GUILD",
		3: "THREAD_KIND_SYSTEM",
		4: "THREAD_KIND_DUEL",
		5: "THREAD_KIND_CHALLENGE",
		6: "THREAD_KIND_FRIEND",
	}
	ThreadKind_value = map[string]int32{
		"THREAD_KIND_UNSPECIFIED": 0,
		"THREAD_KIND_MENTOR":      1,
		"THREAD_KIND_GUILD":       2,
		"THREAD_KIND_SYSTEM":      3,
		"THREAD_KIND_DUEL":        4,
		"THREAD_KIND_CHALLENGE":   5,
		"THREAD_KIND_FRIEND":      6,
	}
)

func (x ThreadKind) Enum() *ThreadKind {
	p := new(ThreadKind)
	*p = x
	return p
}

func (x ThreadKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreadKind) Descriptor() protoreflect.EnumDescriptor {
	return file_social_inbox_v1_inbox_proto_enumTypes[0].Descriptor()
}

func (ThreadKind) Type() protoreflect.EnumType {
	return &file_social_inbox_v1_inbox_proto_enumTypes[0]
}

func (x ThreadKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreadKind.Descriptor instead.
func (ThreadKind) EnumDescriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{0}
}

type SenderKind int32

const (
	SenderKind_SENDER_KIND_UNSPECIFIED SenderKind = 0
	SenderKind_SENDER_KIND_USER        SenderKind = 1
	SenderKind_SENDER_KIND_SYSTEM      SenderKind = 2
	SenderKind_SENDER_KIND_MENTOR_BOT  SenderKind = 3
	SenderKind_SENDER_KIND_GUILD_BOT   SenderKind = 4
)

// Enum value maps for SenderKind.
var (
	SenderKind_name = map[int32]string{
		0: "SENDER_KIND_UNSPECIFIED",
		1: "SENDER_KIND_USER",
		2: "SENDER_KIND_SYSTEM",
		3: "SENDER_KIND_MENTOR_BOT",
		4: "SENDER_KIND_GUILD_BOT",
	}
	SenderKind_value = map[string]int32{
		"SENDER_KIND_UNSPECIFIED": 0,
		"SENDER_KIND_USER":        1,
		"SENDER_KIND_SYSTEM":      2,
		"SENDER_KIND_MENTOR_BOT":  3,
		"SENDER_KIND_GUILD_BOT":   4,
	}
)

func (x SenderKind) Enum() *SenderKind {
	p := new(SenderKind)
	*p = x
	return p
}

func (x SenderKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SenderKind) Descriptor() protoreflect.EnumDescriptor {
	return file_social_inbox_v1_inbox_proto_enumTypes[1].Descriptor()
}

func (SenderKind) Type() protoreflect.EnumType {
	return &file_social_inbox_v1_inbox_proto_enumTypes[1]
}

func (x SenderKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SenderKind.Descriptor instead.
func (SenderKind) EnumDescriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{1}
}

type InboxThread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          ThreadKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=inbox.v1.ThreadKind" json:"kind,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"` // display title ("Varek · Mentor")
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`   // emoji or 2-letter initials
	Preview       string                 `protobuf:"bytes,5,opt,name=preview,proto3" json:"preview,omitempty"` // last-message snippet
	UnreadCount   int32                  `protobuf:"varint,6,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	LastMessageAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	ExternalId    string                 `protobuf:"bytes,8,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // optional link to source entity
	Interactive   bool                   `protobuf:"varint,9,opt,name=interactive,proto3" json:"interactive,omitempty"`                // can the user reply?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxThread) Reset() {
	*x = InboxThread{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxThread) ProtoMessage() {}

func (x *InboxThread) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxThread.ProtoReflect.Descriptor instead.
func (*InboxThread) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{0}
}

func (x *InboxThread) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InboxThread) GetKind() ThreadKind {
	if x != nil {
		return x.Kind
	}
	return ThreadKind_THREAD_KIND_UNSPECIFIED
}

func (x *InboxThread) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *InboxThread) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *InboxThread) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *InboxThread) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *InboxThread) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *InboxThread) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *InboxThread) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

type InboxMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	SenderKind    SenderKind             `protobuf:"varint,3,opt,name=sender_kind,json=senderKind,proto3,enum=inbox.v1.SenderKind" json:"sender_kind,omitempty"`
	SenderId      string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // empty for system/bot
	SenderName    string                 `protobuf:"bytes,5,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Read          bool                   `protobuf:"varint,7,opt,name=read,proto3" json:"read,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxMessage) Reset() {
	*x = InboxMessage{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxMessage) ProtoMessage() {}

func (x *InboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxMessage.ProtoReflect.Descriptor instead.
func (*InboxMessage) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{1}
}

func (x *InboxMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InboxMessage) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *InboxMessage) GetSenderKind() SenderKind {
	if x != nil {
		return x.SenderKind
	}
	return SenderKind_SENDER_KIND_UNSPECIFIED
}

func (x *InboxMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *InboxMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *InboxMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *InboxMessage) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *InboxMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListThreadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // default 50, max 100
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsRequest) Reset() {
	*x = ListThreadsRequest{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsRequest) ProtoMessage() {}

func (x *ListThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsRequest.ProtoReflect.Descriptor instead.
func (*ListThreadsRequest) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{2}
}

func (x *ListThreadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListThreadsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*InboxThread         `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	UnreadTotal   int32                  `protobuf:"varint,3,opt,name=unread_total,json=unreadTotal,proto3" json:"unread_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsResponse) Reset() {
	*x = ListThreadsResponse{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsResponse) ProtoMessage() {}

func (x *ListThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsResponse.ProtoReflect.Descriptor instead.
func (*ListThreadsResponse) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{3}
}

func (x *ListThreadsResponse) GetThreads() []*InboxThread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *ListThreadsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListThreadsResponse) GetUnreadTotal() int32 {
	if x != nil {
		return x.UnreadTotal
	}
	return 0
}

type GetThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadRequest) Reset() {
	*x = GetThreadRequest{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadRequest) ProtoMessage() {}

func (x *GetThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadRequest.ProtoReflect.Descriptor instead.
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{4}
}

func (x *GetThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type GetThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thread        *InboxThread           `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Messages      []*InboxMessage        `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadResponse) Reset() {
	*x = GetThreadResponse{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadResponse) ProtoMessage() {}

func (x *GetThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadResponse.ProtoReflect.Descriptor instead.
func (*GetThreadResponse) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{5}
}

func (x *GetThreadResponse) GetThread() *InboxThread {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *GetThreadResponse) GetMessages() []*InboxMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MarkThreadReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkThreadReadRequest) Reset() {
	*x = MarkThreadReadRequest{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkThreadReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkThreadReadRequest) ProtoMessage() {}

func (x *MarkThreadReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkThreadReadRequest.ProtoReflect.Descriptor instead.
func (*MarkThreadReadRequest) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{6}
}

func (x *MarkThreadReadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type MarkThreadReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	UnreadTotal   int32                  `protobuf:"varint,2,opt,name=unread_total,json=unreadTotal,proto3" json:"unread_total,omitempty"` // updated badge count after marking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkThreadReadResponse) Reset() {
	*x = MarkThreadReadResponse{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkThreadReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkThreadReadResponse) ProtoMessage() {}

func (x *MarkThreadReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkThreadReadResponse.ProtoReflect.Descriptor instead.
func (*MarkThreadReadResponse) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{7}
}

func (x *MarkThreadReadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MarkThreadReadResponse) GetUnreadTotal() int32 {
	if x != nil {
		return x.UnreadTotal
	}
	return 0
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SendMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *InboxMessage          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetMessage() *InboxMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{10}
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadTotal   int32                  `protobuf:"varint,1,opt,name=unread_total,json=unreadTotal,proto3" json:"unread_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{11}
}

func (x *GetUnreadCountResponse) GetUnreadTotal() int32 {
	if x != nil {
		return x.UnreadTotal
	}
	return 0
}

type CreateDirectThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   string                 `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"` // UUID of the target user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectThreadRequest) Reset() {
	*x = CreateDirectThreadRequest{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectThreadRequest) ProtoMessage() {}

func (x *CreateDirectThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectThreadRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectThreadRequest) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{12}
}

func (x *CreateDirectThreadRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

type CreateDirectThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"` // sender-side thread UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectThreadResponse) Reset() {
	*x = CreateDirectThreadResponse{}
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectThreadResponse) ProtoMessage() {}

func (x *CreateDirectThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_inbox_v1_inbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectThreadResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectThreadResponse) Descriptor() ([]byte, []int) {
	return file_social_inbox_v1_inbox_proto_rawDescGZIP(), []int{13}
}

func (x *CreateDirectThreadResponse) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

var File_social_inbox_v1_inbox_proto protoreflect.FileDescriptor

const file_social_inbox_v1_inbox_proto_rawDesc = "" +
	"\n" +
	"\x1bsocial/inbox/v1/inbox.proto\x12\binbox.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x02\n" +
	"\vInboxThread\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x14.inbox.v1.ThreadKindR\x04kind\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x18\n" +
	"\apreview\x18\x05 \x01(\tR\apreview\x12!\n" +
	"\funread_count\x18\x06 \x01(\x05R\vunreadCount\x12B\n" +
	"\x0flast_message_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\x12\x1f\n" +
	"\vexternal_id\x18\b \x01(\tR\n" +
	"externalId\x12 \n" +
	"\vinteractive\x18\t \x01(\bR\vinteractive\"\x93\x02\n" +
	"\fInboxMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x125\n" +
	"\vsender_kind\x18\x03 \x01(\x0e2\x14.inbox.v1.SenderKindR\n" +
	"senderKind\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x05 \x01(\tR\n" +
	"senderName\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x12\n" +
	"\x04read\x18\a \x01(\bR\x04read\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"B\n" +
	"\x12ListThreadsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x7f\n" +
	"\x13ListThreadsResponse\x12/\n" +
	"\athreads\x18\x01 \x03(\v2\x15.inbox.v1.InboxThreadR\athreads\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12!\n" +
	"\funread_total\x18\x03 \x01(\x05R\vunreadTotal\"/\n" +
	"\x10GetThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"v\n" +
	"\x11GetThreadResponse\x12-\n" +
	"\x06thread\x18\x01 \x01(\v2\x15.inbox.v1.InboxThreadR\x06thread\x122\n" +
	"\bmessages\x18\x02 \x03(\v2\x16.inbox.v1.InboxMessageR\bmessages\"4\n" +
	"\x15MarkThreadReadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"K\n" +
	"\x16MarkThreadReadResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\funread_total\x18\x02 \x01(\x05R\vunreadTotal\"E\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"G\n" +
	"\x13SendMessageResponse\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x16.inbox.v1.InboxMessageR\amessage\"\x17\n" +
	"\x15GetUnreadCountRequest\";\n" +
	"\x16GetUnreadCountResponse\x12!\n" +
	"\funread_total\x18\x01 \x01(\x05R\vunreadTotal\">\n" +
	"\x19CreateDirectThreadRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\"9\n" +
	"\x1aCreateDirectThreadResponse\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId*\xb9\x01\n" +
	"\n" +
	"ThreadKind\x12\x1b\n" +
	"\x17THREAD_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12THREAD_KIND_MENTOR\x10\x01\x12\x15\n" +
	"\x11THREAD_KIND_GUILD\x10\x02\x12\x16\n" +
	"\x12THREAD_KIND_SYSTEM\x10\x03\x12\x14\n" +
	"\x10THREAD_KIND_DUEL\x10\x04\x12\x19\n" +
	"\x15THREAD_KIND_CHALLENGE\x10\x05\x12\x16\n" +
	"\x12THREAD_KIND_FRIEND\x10\x06*\x8e\x01\n" +
	"\n" +
	"SenderKind\x12\x1b\n" +
	"\x17SENDER_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SENDER_KIND_USER\x10\x01\x12\x16\n" +
	"\x12SENDER_KIND_SYSTEM\x10\x02\x12\x1a\n" +
	"\x16SENDER_KIND_MENTOR_BOT\x10\x03\x12\x19\n" +
	"\x15SENDER_KIND_GUILD_BOT\x10\x042\xee\x05\n" +
	"\fInboxService\x12i\n" +
	"\vListThreads\x12\x1c.inbox.v1.ListThreadsRequest\x1a\x1d.inbox.v1.ListThreadsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/inbox/threads\x12o\n" +
	"\tGetThread\x12\x1a.inbox.v1.GetThreadRequest\x1a\x1b.inbox.v1.GetThreadResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/inbox/threads/{thread_id}\x12\x86\x01\n" +
	"\x0eMarkThreadRead\x12\x1f.inbox.v1.MarkThreadReadRequest\x1a .inbox.v1.MarkThreadReadResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/inbox/threads/{thread_id}/read\x12\x81\x01\n" +
	"\vSendMessage\x12\x1c.inbox.v1.SendMessageRequest\x1a\x1d.inbox.v1.SendMessageResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/api/v1/inbox/threads/{thread_id}/messages\x12q\n" +
	"\x0eGetUnreadCount\x12\x1f.inbox.v1.GetUnreadCountRequest\x1a .inbox.v1.GetUnreadCountResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/inbox/unread\x12\x81\x01\n" +
	"\x12CreateDirectThread\x12#.inbox.v1.CreateDirectThreadRequest\x1a$.inbox.v1.CreateDirectThreadResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/inbox/threadsB\x19Z\x17api/pkg/api/inbox/v1;v1b\x06proto3"

var (
	file_social_inbox_v1_inbox_proto_rawDescOnce sync.Once
	file_social_inbox_v1_inbox_proto_rawDescData []byte
)

func file_social_inbox_v1_inbox_proto_rawDescGZIP() []byte {
	file_social_inbox_v1_inbox_proto_rawDescOnce.Do(func() {
		file_social_inbox_v1_inbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_inbox_v1_inbox_proto_rawDesc), len(file_social_inbox_v1_inbox_proto_rawDesc)))
	})
	return file_social_inbox_v1_inbox_proto_rawDescData
}

var file_social_inbox_v1_inbox_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_social_inbox_v1_inbox_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_social_inbox_v1_inbox_proto_goTypes = []any{
	(ThreadKind)(0),                    // 0: inbox.v1.ThreadKind
	(SenderKind)(0),                    // 1: inbox.v1.SenderKind
	(*InboxThread)(nil),                // 2: inbox.v1.InboxThread
	(*InboxMessage)(nil),               // 3: inbox.v1.InboxMessage
	(*ListThreadsRequest)(nil),         // 4: inbox.v1.ListThreadsRequest
	(*ListThreadsResponse)(nil),        // 5: inbox.v1.ListThreadsResponse
	(*GetThreadRequest)(nil),           // 6: inbox.v1.GetThreadRequest
	(*GetThreadResponse)(nil),          // 7: inbox.v1.GetThreadResponse
	(*MarkThreadReadRequest)(nil),      // 8: inbox.v1.MarkThreadReadRequest
	(*MarkThreadReadResponse)(nil),     // 9: inbox.v1.MarkThreadReadResponse
	(*SendMessageRequest)(nil),         // 10: inbox.v1.SendMessageRequest
	(*SendMessageResponse)(nil),        // 11: inbox.v1.SendMessageResponse
	(*GetUnreadCountRequest)(nil),      // 12: inbox.v1.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),     // 13: inbox.v1.GetUnreadCountResponse
	(*CreateDirectThreadRequest)(nil),  // 14: inbox.v1.CreateDirectThreadRequest
	(*CreateDirectThreadResponse)(nil), // 15: inbox.v1.CreateDirectThreadResponse
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
}
var file_social_inbox_v1_inbox_proto_depIdxs = []int32{
	0,  // 0: inbox.v1.InboxThread.kind:type_name -> inbox.v1.ThreadKind
	16, // 1: inbox.v1.InboxThread.last_message_at:type_name -> google.protobuf.Timestamp
	1,  // 2: inbox.v1.InboxMessage.sender_kind:type_name -> inbox.v1.SenderKind
	16, // 3: inbox.v1.InboxMessage.created_at:type_name -> google.protobuf.Timestamp
	2,  // 4: inbox.v1.ListThreadsResponse.threads:type_name -> inbox.v1.InboxThread
	2,  // 5: inbox.v1.GetThreadResponse.thread:type_name -> inbox.v1.InboxThread
	3,  // 6: inbox.v1.GetThreadResponse.messages:type_name -> inbox.v1.InboxMessage
	3,  // 7: inbox.v1.SendMessageResponse.message:type_name -> inbox.v1.InboxMessage
	4,  // 8: inbox.v1.InboxService.ListThreads:input_type -> inbox.v1.ListThreadsRequest
	6,  // 9: inbox.v1.InboxService.GetThread:input_type -> inbox.v1.GetThreadRequest
	8,  // 10: inbox.v1.InboxService.MarkThreadRead:input_type -> inbox.v1.MarkThreadReadRequest
	10, // 11: inbox.v1.InboxService.SendMessage:input_type -> inbox.v1.SendMessageRequest
	12, // 12: inbox.v1.InboxService.GetUnreadCount:input_type -> inbox.v1.GetUnreadCountRequest
	14, // 13: inbox.v1.InboxService.CreateDirectThread:input_type -> inbox.v1.CreateDirectThreadRequest
	5,  // 14: inbox.v1.InboxService.ListThreads:output_type -> inbox.v1.ListThreadsResponse
	7,  // 15: inbox.v1.InboxService.GetThread:output_type -> inbox.v1.GetThreadResponse
	9,  // 16: inbox.v1.InboxService.MarkThreadRead:output_type -> inbox.v1.MarkThreadReadResponse
	11, // 17: inbox.v1.InboxService.SendMessage:output_type -> inbox.v1.SendMessageResponse
	13, // 18: inbox.v1.InboxService.GetUnreadCount:output_type -> inbox.v1.GetUnreadCountResponse
	15, // 19: inbox.v1.InboxService.CreateDirectThread:output_type -> inbox.v1.CreateDirectThreadResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_social_inbox_v1_inbox_proto_init() }
func file_social_inbox_v1_inbox_proto_init() {
	if File_social_inbox_v1_inbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_inbox_v1_inbox_proto_rawDesc), len(file_social_inbox_v1_inbox_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_inbox_v1_inbox_proto_goTypes,
		DependencyIndexes: file_social_inbox_v1_inbox_proto_depIdxs,
		EnumInfos:         file_social_inbox_v1_inbox_proto_enumTypes,
		MessageInfos:      file_social_inbox_v1_inbox_proto_msgTypes,
	}.Build()
	File_social_inbox_v1_inbox_proto = out.File
	file_social_inbox_v1_inbox_proto_goTypes = nil
	file_social_inbox_v1_inbox_proto_depIdxs = nil
}
