// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "api/internal/model"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateEvent provides a mock function with given fields: ctx, userID, isAdmin, req
func (_m *Service) CreateEvent(ctx context.Context, userID uuid.UUID, isAdmin bool, req model.CreateEventRequest) (*model.Event, error) {
	ret := _m.Called(ctx, userID, isAdmin, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 *model.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, model.CreateEventRequest) (*model.Event, error)); ok {
		return rf(ctx, userID, isAdmin, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, model.CreateEventRequest) *model.Event); ok {
		r0 = rf(ctx, userID, isAdmin, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool, model.CreateEventRequest) error); ok {
		r1 = rf(ctx, userID, isAdmin, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type Service_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - isAdmin bool
//   - req model.CreateEventRequest
func (_e *Service_Expecter) CreateEvent(ctx interface{}, userID interface{}, isAdmin interface{}, req interface{}) *Service_CreateEvent_Call {
	return &Service_CreateEvent_Call{Call: _e.mock.On("CreateEvent", ctx, userID, isAdmin, req)}
}

func (_c *Service_CreateEvent_Call) Run(run func(ctx context.Context, userID uuid.UUID, isAdmin bool, req model.CreateEventRequest)) *Service_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool), args[3].(model.CreateEventRequest))
	})
	return _c
}

func (_c *Service_CreateEvent_Call) Return(_a0 *model.Event, _a1 error) *Service_CreateEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateEvent_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool, model.CreateEventRequest) (*model.Event, error)) *Service_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvent provides a mock function with given fields: ctx, eventID, user
func (_m *Service) DeleteEvent(ctx context.Context, eventID uuid.UUID, user *model.User) error {
	ret := _m.Called(ctx, eventID, user)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.User) error); ok {
		r0 = rf(ctx, eventID, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_DeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvent'
type Service_DeleteEvent_Call struct {
	*mock.Call
}

// DeleteEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - user *model.User
func (_e *Service_Expecter) DeleteEvent(ctx interface{}, eventID interface{}, user interface{}) *Service_DeleteEvent_Call {
	return &Service_DeleteEvent_Call{Call: _e.mock.On("DeleteEvent", ctx, eventID, user)}
}

func (_c *Service_DeleteEvent_Call) Run(run func(ctx context.Context, eventID uuid.UUID, user *model.User)) *Service_DeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*model.User))
	})
	return _c
}

func (_c *Service_DeleteEvent_Call) Return(_a0 error) *Service_DeleteEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_DeleteEvent_Call) RunAndReturn(run func(context.Context, uuid.UUID, *model.User) error) *Service_DeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// JoinEvent provides a mock function with given fields: ctx, userID, eventID
func (_m *Service) JoinEvent(ctx context.Context, userID uuid.UUID, eventID uuid.UUID) (*model.Event, error) {
	ret := _m.Called(ctx, userID, eventID)

	if len(ret) == 0 {
		panic("no return value specified for JoinEvent")
	}

	var r0 *model.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Event, error)); ok {
		return rf(ctx, userID, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Event); ok {
		r0 = rf(ctx, userID, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_JoinEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinEvent'
type Service_JoinEvent_Call struct {
	*mock.Call
}

// JoinEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - eventID uuid.UUID
func (_e *Service_Expecter) JoinEvent(ctx interface{}, userID interface{}, eventID interface{}) *Service_JoinEvent_Call {
	return &Service_JoinEvent_Call{Call: _e.mock.On("JoinEvent", ctx, userID, eventID)}
}

func (_c *Service_JoinEvent_Call) Run(run func(ctx context.Context, userID uuid.UUID, eventID uuid.UUID)) *Service_JoinEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Service_JoinEvent_Call) Return(_a0 *model.Event, _a1 error) *Service_JoinEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_JoinEvent_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.Event, error)) *Service_JoinEvent_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveEvent provides a mock function with given fields: ctx, userID, eventID
func (_m *Service) LeaveEvent(ctx context.Context, userID uuid.UUID, eventID uuid.UUID) error {
	ret := _m.Called(ctx, userID, eventID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_LeaveEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveEvent'
type Service_LeaveEvent_Call struct {
	*mock.Call
}

// LeaveEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - eventID uuid.UUID
func (_e *Service_Expecter) LeaveEvent(ctx interface{}, userID interface{}, eventID interface{}) *Service_LeaveEvent_Call {
	return &Service_LeaveEvent_Call{Call: _e.mock.On("LeaveEvent", ctx, userID, eventID)}
}

func (_c *Service_LeaveEvent_Call) Run(run func(ctx context.Context, userID uuid.UUID, eventID uuid.UUID)) *Service_LeaveEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Service_LeaveEvent_Call) Return(_a0 error) *Service_LeaveEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_LeaveEvent_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *Service_LeaveEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ListEvents provides a mock function with given fields: ctx, userID, opts
func (_m *Service) ListEvents(ctx context.Context, userID uuid.UUID, opts model.ListEventsOptions) (*model.ListEventsResponse, error) {
	ret := _m.Called(ctx, userID, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 *model.ListEventsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.ListEventsOptions) (*model.ListEventsResponse, error)); ok {
		return rf(ctx, userID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.ListEventsOptions) *model.ListEventsResponse); ok {
		r0 = rf(ctx, userID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ListEventsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.ListEventsOptions) error); ok {
		r1 = rf(ctx, userID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvents'
type Service_ListEvents_Call struct {
	*mock.Call
}

// ListEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - opts model.ListEventsOptions
func (_e *Service_Expecter) ListEvents(ctx interface{}, userID interface{}, opts interface{}) *Service_ListEvents_Call {
	return &Service_ListEvents_Call{Call: _e.mock.On("ListEvents", ctx, userID, opts)}
}

func (_c *Service_ListEvents_Call) Run(run func(ctx context.Context, userID uuid.UUID, opts model.ListEventsOptions)) *Service_ListEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.ListEventsOptions))
	})
	return _c
}

func (_c *Service_ListEvents_Call) Return(_a0 *model.ListEventsResponse, _a1 error) *Service_ListEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListEvents_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.ListEventsOptions) (*model.ListEventsResponse, error)) *Service_ListEvents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvent provides a mock function with given fields: ctx, eventID, user, req
func (_m *Service) UpdateEvent(ctx context.Context, eventID uuid.UUID, user *model.User, req model.UpdateEventRequest) (*model.Event, error) {
	ret := _m.Called(ctx, eventID, user, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 *model.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.User, model.UpdateEventRequest) (*model.Event, error)); ok {
		return rf(ctx, eventID, user, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.User, model.UpdateEventRequest) *model.Event); ok {
		r0 = rf(ctx, eventID, user, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.User, model.UpdateEventRequest) error); ok {
		r1 = rf(ctx, eventID, user, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_UpdateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvent'
type Service_UpdateEvent_Call struct {
	*mock.Call
}

// UpdateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - user *model.User
//   - req model.UpdateEventRequest
func (_e *Service_Expecter) UpdateEvent(ctx interface{}, eventID interface{}, user interface{}, req interface{}) *Service_UpdateEvent_Call {
	return &Service_UpdateEvent_Call{Call: _e.mock.On("UpdateEvent", ctx, eventID, user, req)}
}

func (_c *Service_UpdateEvent_Call) Run(run func(ctx context.Context, eventID uuid.UUID, user *model.User, req model.UpdateEventRequest)) *Service_UpdateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*model.User), args[3].(model.UpdateEventRequest))
	})
	return _c
}

func (_c *Service_UpdateEvent_Call) Return(_a0 *model.Event, _a1 error) *Service_UpdateEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_UpdateEvent_Call) RunAndReturn(run func(context.Context, uuid.UUID, *model.User, model.UpdateEventRequest) (*model.Event, error)) *Service_UpdateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
