package seeds

func generatedInterviewPrepTasks() []InterviewPrepCatalogTask {
	return append(append(append(goInterviewPrepTasks(), pythonInterviewPrepTasks()...), sqlInterviewPrepTasks()...), systemDesignInterviewPrepTasks()...)
}

func goInterviewPrepTasks() []InterviewPrepCatalogTask {
	return []InterviewPrepCatalogTask{
		guidedCodingTask("go-lru-cache-api", "Go: LRU cache API", "go", "Спроектируй и напиши LRU cache с `Get/Put`, eviction и O(1) операциями. Затем объясни выбор структуры данных и как сделать реализацию thread-safe.", goStarter("type Cache interface {\n\tGet(key string) (string, bool)\n\tPut(key string, value string)\n}\n"), "Обычно используют hash map + doubly linked list: map даёт O(1) доступ по ключу, список хранит порядок использования. Для многопоточности нужен mutex или single-owner goroutine.", q("Почему одного map недостаточно?", "Map не хранит порядок использования. Без дополнительной структуры нельзя за O(1) понять, какой элемент вытеснять."), q("Что меняется в concurrent-версии?", "Нужно синхронизировать и map, и связный список. Часто достаточно одного mutex, если нет экстремальных требований к contention."), q("Какие типичные баги здесь?", "Необновлённый head/tail при eviction, потеря ссылки на узел, рассинхрон map и list, гонки в concurrent-режиме.")),
		guidedCodingTask("go-merge-k-sorted-lists", "Go: merge k sorted lists", "go", "Реализуй merge k sorted lists через heap, затем объясни асимптотику и почему divide-and-conquer может быть альтернативой.", goStarter("type ListNode struct {\n\tVal  int\n\tNext *ListNode\n}\n\nfunc mergeKLists(lists []*ListNode) *ListNode {\n\treturn nil\n}\n"), "Классическое решение использует min-heap размера k и даёт O(n log k). Альтернатива через pairwise merge или divide-and-conquer даёт ту же асимптотику, но другой trade-off по константам.", q("Почему heap здесь хорошо подходит?", "Потому что в каждый момент нужен минимум среди текущих голов k списков. Heap даёт его за O(log k) на шаг."), q("Когда divide-and-conquer может быть проще?", "Когда проще переиспользовать merge двух списков и не хочется писать heap.Interface, особенно на интервью с ограниченным временем."), q("Где тут легко ошибиться в Go?", "В обработке nil-списков, в ссылках на следующий узел и в обновлении хвоста результирующего списка.")),
		guidedCodingTask("go-idempotent-consumer", "Go: idempotent consumer", "go", "Спроектируй consumer, который обрабатывает сообщения идемпотентно. После решения обсуди dedup key, retention окна и exactly-once мифы.", goStarter("type Message struct {\n\tID      string\n\tPayload string\n}\n\ntype Store interface {\n\tSeen(id string) (bool, error)\n\tMarkSeen(id string) error\n}\n"), "Практически идемпотентность строится на dedup key и durable store с TTL/retention window. Exactly-once обычно заменяется at-least-once + идемпотентная обработка.", q("Почему at-least-once без идемпотентности опасен?", "Повторная доставка создаёт дублирующие записи, повторные списания или повторные сайд-эффекты."), q("Где хранить dedup state?", "В durable storage рядом с бизнес-состоянием или в отдельном KV/DB с гарантией консистентности относительно эффекта."), q("Почему exactly-once часто маркетинг?", "Потому что end-to-end exactly-once между брокером, приложением и внешними системами почти всегда распадается на набор локальных гарантий.")),
		guidedCodingTask("go-sharded-counter", "Go: sharded counter", "go", "Нужно спроектировать counter для high-write workload. Опиши sharding, flush в durable storage и trade-offs по точности.", goStarter("type Counter interface {\n\tInc(key string, delta int64)\n\tGet(key string) int64\n}\n"), "Чтобы уменьшить lock contention, часто шардируют счётчик по нескольким buckets и агрегируют чтения. Если нужна durability, шардированные инкременты периодически flush'ат в хранилище.", q("Почему один global mutex плохо масштабируется?", "При большом числе записей он становится точкой contention и ограничивает throughput на CPU."), q("Что происходит с точностью при async flush?", "Мгновенное значение в durable store может отставать от in-memory значения. Нужно явно договориться о freshness guarantees."), q("Как читать значение быстро?", "Либо суммировать shard'ы на чтении, либо держать агрегированное значение ценой более сложной синхронизации.")),
		guidedCodingTask("go-retryable-job-scheduler", "Go: retryable job scheduler", "go", "Придумай scheduler задач с retry, exponential backoff и dead-letter queue. После решения обсуди jitter и poison messages.", goStarter("type Job struct {\n\tID       string\n\tAttempts int\n}\n"), "Нужно хранить состояние попыток, вычислять next run с backoff и уметь переводить poison jobs в DLQ. Jitter уменьшает thundering herd на восстановлении после ошибок.", q("Зачем нужен jitter поверх backoff?", "Чтобы тысячи задач не ретраились одновременно и не перегружали зависимость новой волной запросов."), q("Когда отправлять задачу в DLQ?", "Когда превышен лимит попыток, ошибка признана неретрабельной или задача явно классифицирована как poison."), q("Чем retry scheduler отличается от простой очереди?", "Он хранит время следующего запуска и состояние повторов, а не просто FIFO-порядок доставки.")),
		guidedCodingTask("go-sliding-window-median", "Go: sliding window median", "go", "Реализуй идею sliding window median и объясни, почему часто используют два heap'а plus lazy deletion.", goStarter("func medianSlidingWindow(nums []int, k int) []float64 {\n\treturn nil\n}\n"), "Обычно используют max-heap для левой половины и min-heap для правой. Удаления из середины делают через lazy deletion map, потому что стандартный heap не умеет дешёвое remove by value.", q("Почему сортировать окно каждый раз плохо?", "Это O(k log k) на каждое окно и слишком дорого на больших n."), q("Зачем нужна lazy deletion?", "Потому что элемент выходит из окна не обязательно с вершины heap, и немедленное удаление неудобно и дорого."), q("Как поддерживать баланс heap'ов?", "Размеры должны отличаться не больше чем на 1, иначе медиана считается неверно.")),
		guidedCodingTask("go-consistent-hash-router", "Go: consistent hash router", "go", "Спроектируй consistent hash router для распределения ключей по нодам. Затем расскажи про virtual nodes и поведение при ребалансе.", goStarter("type Router interface {\n\tAddNode(id string)\n\tRemoveNode(id string)\n\tRoute(key string) string\n}\n"), "Consistent hashing минимизирует перетасовку ключей при изменении набора нод. Virtual nodes улучшают распределение и уменьшают skew.", q("Почему modulo hashing плохо при добавлении ноды?", "Потому что почти все ключи перераспределяются заново, вызывая большой cache churn и load spike."), q("Что дают virtual nodes?", "Они делают распределение ключей более ровным и снижают влияние неудачного положения одной физической ноды на ring."), q("Какие проблемы остаются?", "Неравномерный load по hot keys, необходимость репликации, state transfer и защита от split-brain при частичных отказах.")),
		guidedCodingTask("go-webhook-delivery-worker", "Go: webhook delivery worker", "go", "Нужно спроектировать delivery worker для webhook'ов: retries, signature verification, timeout budgets и observability.", goStarter("type Delivery struct {\n\tEndpoint string\n\tBody     []byte\n}\n"), "Важны bounded concurrency, retry policy, подпись тела, строгие timeout'ы и метрики по success rate, latency и DLQ. Внешний endpoint нельзя считать надёжным или быстрым.", q("Почему webhook sender нельзя делать без timeout?", "Медленный клиент может занять worker навсегда и сломать throughput всей системы."), q("Что обязательно логировать и метрицировать?", "Попытки, latency, HTTP status, timeout rate, DLQ rate и correlation id для трассировки конкретной доставки."), q("Зачем подпись запроса?", "Чтобы receiver мог проверить подлинность отправителя и целостность payload.")),
	}
}

func pythonInterviewPrepTasks() []InterviewPrepCatalogTask {
	return []InterviewPrepCatalogTask{
		guidedCodingTask("python-top-k-frequent-stream", "Python: top-k frequent stream", "python", "Нужно поддерживать top-k самых частых элементов в потоке. После решения обсуди heap vs Counter и стоимость пересчёта.", pythonStarter("def solve(input: str) -> str:\n    return \"\"\n"), "Для batched варианта часто хватает Counter + heapq.nlargest. Для truly streaming задачи обычно нужна структура с инкрементальным обновлением и понятными trade-off по памяти.", q("Почему полный пересчёт после каждого элемента дорог?", "Потому что при большом потоке это превращается в постоянную сортировку или rebuild heap без нужды."), q("Когда Counter достаточно?", "Когда ответ нужен офлайн или периодически, а не после каждого события с минимальной задержкой."), q("Какая главная проблема у streaming top-k?", "Стабильно поддерживать порядок и частоты при ограниченной памяти и без полного пересчёта.")),
		guidedCodingTask("python-async-batch-aggregator", "Python: async batch aggregator", "python", "Спроектируй async batch aggregator на Python: collect N items or T milliseconds, затем flush. После решения обсуди backpressure и graceful shutdown.", pythonStarter("import asyncio\n\nasync def flush_batch(items: list[str]) -> None:\n    pass\n"), "В async batching нужно держать таймер, bounded queue и явный shutdown path. Иначе легко получить висящие task'и и потерю последнего неполного батча.", q("Почему нужен bounded queue?", "Без него producer может перегрузить процесс и память при медленном flush."), q("Что делать с последним неполным батчем при shutdown?", "Явно flush'ить его перед завершением, если политика допускает частичный батч."), q("Где тут частая ошибка?", "Создавать fire-and-forget task без await/cancel и терять исключения из flush coroutine.")),
		guidedCodingTask("python-interval-merge", "Python: merge intervals", "python", "Реализуй merge intervals, затем объясни почему сортировка по началу делает задачу простой.", pythonStarter("def merge(intervals: list[list[int]]) -> list[list[int]]:\n    return []\n"), "После сортировки по left endpoint достаточно идти слева направо и либо расширять текущий интервал, либо добавлять новый. Сложность O(n log n) из-за сортировки.", q("Почему без сортировки сложнее?", "Без глобального порядка сложно локально решить, какие интервалы ещё могут пересечься позже."), q("Какой invariant удобно держать?", "Что в результирующем списке уже лежат непересекающиеся интервалы, и текущий последний можно только расширить."), q("Что делать с edge case touching intervals?", "Нужно заранее договориться, считаются ли [1,2] и [2,3] пересекающимися. Это часть постановки.")),
		guidedCodingTask("python-task-scheduler-cooldown", "Python: task scheduler with cooldown", "python", "Нужно распланировать задачи с cooldown между одинаковыми типами. После решения обсуди greedy и priority queue.", pythonStarter("def solve(input: str) -> str:\n    return \"0\"\n"), "Обычно решение использует max-heap по оставшемуся количеству задач и очередь cooldown событий. Это greedy с O(n log k) по числу типов задач.", q("Почему greedy здесь работает?", "На каждом шаге выгодно брать самый частый доступный тип, иначе легко получить лишние idle slots позже."), q("Зачем отдельная cooldown queue?", "Чтобы понимать, когда тип задачи снова станет доступным для heap."), q("Что будет, если cooldown большой?", "Появится больше idle интервалов, если не хватает других задач для заполнения окна.")),
		guidedCodingTask("python-deduplicate-webhook-events", "Python: deduplicate webhook events", "python", "Спроектируй dedup layer для webhook events на Python. Потом расскажи про TTL, memory bound и race conditions.", pythonStarter("def should_process(event_id: str) -> bool:\n    return True\n"), "Нужен dedup store с TTL и bounded memory policy. В distributed варианте локального set недостаточно: нужна общая durable точка истины или координация.", q("Почему вечное хранение seen-id плохо?", "Множество будет бесконечно расти и станет дорогим по памяти или диску."), q("Как выбрать TTL?", "Из окна допустимой повторной доставки события со стороны интеграции плюс небольшой запас."), q("Что ломается в multi-process варианте?", "Два процесса могут одновременно не увидеть id и оба обработать событие без общей атомарной записи.")),
		guidedCodingTask("python-trie-autocomplete", "Python: trie autocomplete", "python", "Нужно реализовать autocomplete по префиксу и обсудить trie vs sorted array.", pythonStarter("class Trie:\n    def insert(self, word: str) -> None:\n        pass\n\n    def suggest(self, prefix: str, limit: int) -> list[str]:\n        return []\n"), "Trie удобен для prefix lookup, но дорог по памяти. Для маленьких словарей и редких обновлений sorted array + binary search может быть проще и дешевле.", q("Почему trie прожорлив по памяти?", "Потому что хранит много узлов и переходов, особенно на разреженном алфавите."), q("Когда sorted array лучше?", "Когда словарь редко меняется, а слов немного и хочется простую реализацию."), q("Как ограничить expensive DFS на suggest?", "Хранить топ-подсказки заранее на узлах или останавливать обход после набора limit элементов.")),
		guidedCodingTask("python-rolling-median", "Python: rolling median", "python", "Реализуй rolling median и обсуди two heaps и lazy deletion.", pythonStarter("def solve(input: str) -> str:\n    return \"\"\n"), "Как и в Go-версии, два heap'а плюс lazy deletion позволяют поддерживать окно эффективнее, чем постоянная сортировка. В Python это часто реализуют через heapq и dict счётчиков удалённых значений.", q("Почему list.sort на каждом шаге не годится?", "Потому что даёт слишком высокую стоимость пересчёта окна при длинном потоке."), q("Какая сложность у two-heaps подхода?", "Обычно O(log k) на обновление окна и O(1) на чтение медианы с оговоркой на lazy cleanup."), q("Что важно для корректности?", "Баланс heap'ов и очистка устаревших элементов перед чтением вершины.")),
		guidedCodingTask("python-jsonl-log-parser", "Python: JSONL log parser", "python", "Нужно распарсить JSONL лог, посчитать топ ошибок и latency percentiles. Потом обсуди streaming parse и memory usage.", pythonStarter("def solve(input: str) -> str:\n    return \"\"\n"), "Лучше парсить поток построчно, а не грузить весь файл в память. Для percentiles на больших объёмах могут понадобиться approximate algorithms вместо хранения всех latency.", q("Почему нельзя бездумно читать всё в память?", "Потому что лог может быть на гигабайты, и процесс упрётся в RAM."), q("Что делать с битыми строками?", "Явно считать их malformed, логировать/метрицировать и решать политику skip vs fail."), q("Как считать percentiles на большом потоке?", "Либо хранить все значения ценой памяти, либо использовать approximate sketches вроде t-digest/HDR histogram.")),
		guidedCodingTask("python-backoff-retry-simulator", "Python: backoff retry simulator", "python", "Смоделируй retry с exponential backoff и jitter, затем обсуди thundering herd и caps.", pythonStarter("def solve(input: str) -> str:\n    return \"\"\n"), "Exponential backoff без cap и jitter легко превращается либо в слишком долгие ожидания, либо в синхронные волны повторов. В бою почти всегда нужен max delay и случайный разброс.", q("Почему jitter обязателен?", "Он рассинхронизирует клиентов и снижает риск повторной общей перегрузки зависимости."), q("Зачем нужен max backoff cap?", "Иначе после длинной серии ошибок задержка растёт слишком сильно и recovery становится болезненно медленным."), q("Когда retry вообще не нужен?", "На неретрабельных ошибках валидации, auth или бизнес-ошибках, где повтор ничего не изменит.")),
	}
}

func sqlInterviewPrepTasks() []InterviewPrepCatalogTask {
	return []InterviewPrepCatalogTask{
		guidedCodingTask("sql-first-order-per-user", "SQL: first order per user", "sql", "Есть orders(user_id, order_id, created_at). Нужно вернуть первый order каждого пользователя. Затем обсуди window functions vs group by + join.", sqlStarter("SELECT\n  user_id,\n  order_id,\n  created_at\nFROM orders;\n"), "Часто проще всего через ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at). Альтернатива через MIN(created_at) + join тоже рабочая, но может давать неоднозначность при тай-брейках.", q("Почему MIN(created_at) не всегда достаточно?", "Потому что при одинаковом created_at у пользователя может быть несколько заказов, и нужен явный tie-break."), q("Когда window function удобнее?", "Когда нужно одновременно вернуть и саму строку, и ranking/ordering без дополнительного self-join."), q("Какие индексы помогут?", "Обычно orders(user_id, created_at, order_id) или близкий covering index.")),
		guidedCodingTask("sql-top-products-by-category", "SQL: top products by category", "sql", "Нужно вывести top-3 продукта по выручке в каждой категории. Потом обсуди dense_rank и обработку ties.", sqlStarter("SELECT\n  category_id,\n  product_id,\n  revenue\nFROM product_sales;\n"), "Обычно решение строится на агрегировании revenue по product_id и затем DENSE_RANK/ROW_NUMBER в рамках category_id. Нужно заранее договориться, как вести себя при ties.", q("Почему LIMIT 3 на весь запрос не работает?", "Потому что нужен top-3 внутри каждой категории, а не глобально по таблице."), q("Когда использовать ROW_NUMBER, а когда DENSE_RANK?", "ROW_NUMBER жёстко режет до 3 строк, а DENSE_RANK может вернуть больше строк при одинаковом значении метрики."), q("Что обычно тяжёлое в таком запросе?", "Агрегация по большим фактам и последующая сортировка внутри partition'ов.")),
		guidedCodingTask("sql-last-event-before-conversion", "SQL: last event before conversion", "sql", "Есть события пользователя и отдельно conversions. Нужно найти последнее событие перед конверсией. Затем обсуди join condition и duplicate conversions.", sqlStarter("SELECT\n  user_id,\n  event_name,\n  event_time\nFROM events;\n"), "Нужно корректно джойнить события по условию `event_time < conversion_time` и потом выбрать максимальное событие на каждую конверсию. Часто помогает window function или lateral join.", q("Почему простой MAX(event_time) GROUP BY user_id недостаточен?", "Потому что конверсий может быть несколько, и нужно искать событие отдельно для каждой конверсии."), q("Чем опасен join без временного условия?", "Он свяжет и события после конверсии, что сломает причинную интерпретацию воронки."), q("Какие данные здесь особенно вредят?", "Дубликаты конверсий, одинаковые timestamps и late-arriving events.")),
		guidedCodingTask("sql-overlapping-subscriptions", "SQL: overlapping subscriptions", "sql", "Нужно найти пересекающиеся подписки одного пользователя. Затем обсуди inclusive/exclusive boundaries.", sqlStarter("SELECT\n  user_id,\n  plan_id,\n  start_at,\n  end_at\nFROM subscriptions;\n"), "Обычно задачу решают self-join'ом по user_id и условию пересечения интервалов. Важно явно договориться, считаются ли touching intervals пересечением.", q("Как выглядит условие пересечения интервалов?", "Два интервала пересекаются, если начало одного меньше конца другого и наоборот, с поправкой на границы."), q("Почему нужна нормализация open-ended подписок?", "Потому что NULL end_at нужно явно трактовать как бесконечность или текущее время."), q("Чем self-join опасен на больших данных?", "Кардинальность растёт квадратично внутри пользователя, поэтому нужны фильтры, индексы и аккуратная дедупликация пар.")),
		guidedCodingTask("sql-churned-users", "SQL: churned users by month", "sql", "Нужно найти пользователей, которые были активны в прошлом месяце, но не активны в текущем. После решения обсуди anti-join и календарные границы.", sqlStarter("SELECT DISTINCT\n  user_id\nFROM events;\n"), "Обычно churn определяют через anti-join между активными в двух соседних окнах. Главное здесь — аккуратные границы периода и единый timezone.", q("Почему NOT IN может быть опасен?", "Из-за NULL semantics запрос может вернуть неожиданный результат. Часто безопаснее NOT EXISTS или left anti-join."), q("Что считать активностью?", "Это бизнес-решение: логин, платёж, сессия, любое событие или набор событий."), q("Почему month boundary надо фиксировать явно?", "Чтобы отчёт не плавал из-за локального времени, UTC и late-arriving событий.")),
		guidedCodingTask("sql-session-gap-detection", "SQL: detect session gaps", "sql", "Есть user events. Нужно разрезать их на сессии по правилу gap > 30 минут. Затем обсуди lag и window partitioning.", sqlStarter("SELECT\n  user_id,\n  event_time\nFROM events;\n"), "Классика через LAG(event_time) и marker новой сессии, затем cumulative sum по пользователю. Здесь важно правильное partition by user_id и упорядочивание.", q("Зачем нужен LAG?", "Он позволяет сравнить текущее событие с предыдущим внутри пользователя и понять, началась ли новая сессия."), q("Почему cumulative sum удобно использовать после marker?", "Он превращает булев признак старта новой сессии в стабильный session_id внутри partition."), q("Какие данные ломают логику?", "Неупорядоченные timestamps, дубликаты событий и смешение timezone.")),
		guidedCodingTask("sql-active-premium-users", "SQL: active premium users", "sql", "Нужно вернуть премиум-пользователей, у которых есть и активная подписка, и хотя бы одна активность за последние 7 дней. Потом обсуди semi-join.", sqlStarter("SELECT\n  u.id\nFROM users u;\n"), "Обычно это пересечение множества premium subscription и recent activity. Хорошо читается через EXISTS, если не нужно таскать лишние строки из фактов.", q("Почему EXISTS часто лучше JOIN?", "Потому что нужен факт существования, а не размножение строк по всем активностям пользователя."), q("Что важно в фильтре активной подписки?", "Явно учесть start/end интервалы и open-ended планы."), q("Какие индексы полезны?", "На subscriptions(user_id, status/start/end) и events(user_id, event_time).")),
		guidedCodingTask("sql-repeat-card-fraud", "SQL: possible card fraud", "sql", "Нужно найти карты, с которых за 10 минут прошли платежи с разных аккаунтов. Затем обсуди self-join vs window.", sqlStarter("SELECT\n  card_hash,\n  user_id,\n  created_at\nFROM payments;\n"), "Обычно задачу можно решить self-join'ом по card_hash и временной близости или через окна с агрегированием диапазона. Нужно исключать совпадение одной и той же транзакции с собой.", q("Почему self-join может быть дорогим?", "Потому что на hot card_hash число пар растёт квадратично в окне времени."), q("Зачем исключать одинакового user_id?", "По условию подозрительны разные аккаунты на одной карте, а не повторные платежи одного пользователя."), q("Как уменьшить false positives?", "Добавить amount/device/ip/merchant constraints и более точное определение suspicious pattern.")),
		guidedCodingTask("sql-retention-by-first-purchase", "SQL: retention by first purchase month", "sql", "Нужно посчитать retention по месяцу первой покупки. Потом обсуди cohort definition и distinct users.", sqlStarter("SELECT\n  user_id,\n  created_at\nFROM orders;\n"), "Retention почти всегда считают по уникальным пользователям, а не по числу событий. Когорта зависит от first purchase date, а активность — от наличия покупки в следующих месяцах.", q("Почему retention нельзя считать по count(order_id)?", "Потому что активный пользователь с множеством покупок исказит метрику относительно других."), q("Что считается первой покупкой?", "Минимальная дата заказа пользователя, если иное не оговорено бизнес-логикой."), q("Почему важно различать cohort month и activity month?", "Иначе можно случайно посчитать только размер когорты, а не возврат пользователей во времени.")),
	}
}

func systemDesignInterviewPrepTasks() []InterviewPrepCatalogTask {
	return []InterviewPrepCatalogTask{
		systemDesignTask("system-design-url-shortener", "System Design: URL shortener", "Спроектируй URL shortener на большой нагрузке: генерация коротких ключей, redirect latency, analytics, custom aliases и abuse control.", "Хорошее решение разделяет write path создания short link и read path редиректа, держит hot mapping в кэше и продумывает генерацию ключей без горячей точки.", q("Где здесь главный hot path?", "Редирект по short code. Он должен быть быстрым и дешёвым, потому что читательский трафик обычно намного выше write traffic."), q("Как обрабатывать custom alias?", "Нужна проверка уникальности, политика reserved words и защита от squatting/abuse."), q("Что логировать в analytics async?", "Redirect events, geo/device/referrer и счётчики по ссылкам без замедления синхронного redirect path.")),
		systemDesignTask("system-design-metrics-pipeline", "System Design: metrics pipeline", "Спроектируй ingestion pipeline для application metrics: high-cardinality labels, aggregation, downsampling, alerting и retention tiers.", "Нужно отделить ingestion от storage/query path, продумать cardinality explosion и разные слои хранения: raw, rollups, long-term retention.", q("Почему high-cardinality labels опасны?", "Они взрывают объём series и память индекса, быстро превращая систему в дорогую и нестабильную."), q("Зачем downsampling?", "Чтобы долго хранить историю дешевле и ускорять длинные аналитические запросы."), q("Где обычно размещают alert evaluation?", "Либо рядом с TSDB/query layer, либо отдельным сервисом, чтобы не смешивать ingestion и rule execution.")),
		systemDesignTask("system-design-autocomplete", "System Design: autocomplete", "Спроектируй autocomplete/search-as-you-type: prefix lookup, ranking, freshness, typo tolerance и cache invalidation.", "Нужно выбрать между trie/FST/index-based подходом, продумать precompute top suggestions и обновление словаря без дорогих full rebuild.", q("Что важнее на hot path autocomplete?", "Очень низкая latency и предсказуемый tail, потому что запрос идёт на каждый ввод символа."), q("Как сочетать freshness и low latency?", "Часто используют основной precomputed index плюс overlay/дельта-слой для свежих обновлений."), q("Почему typo tolerance дорог?", "Fuzzy matching сильно расширяет пространство кандидатов и может резко увеличить CPU/latency.")),
		systemDesignTask("system-design-ride-dispatch", "System Design: ride dispatch", "Спроектируй dispatch для ride-hailing: matching водителя и пассажира, realtime location, surge pricing и graceful degradation.", "Здесь важны realtime location updates, geo-index, fairness matching и устойчивость к залипшим stale locations. Matching обычно отделяют от расчёта цены и биллинга.", q("Почему location stream нельзя слать напрямую в SQL?", "Слишком частые обновления приведут к высокому write load и плохой latency на горячем state."), q("Как обрабатывать stale driver location?", "Через TTL/heartbeat и исключение неподтверждённых водителей из matching pool."), q("Что деградирует первым при перегрузке?", "Дополнительные enrichments и часть ranking/price hints, но не базовый ability to match and accept ride.")),
		systemDesignTask("system-design-video-upload", "System Design: video upload and processing", "Спроектируй pipeline загрузки видео: upload, transcoding, thumbnails, moderation, CDN delivery и retries.", "Обычно upload path делают напрямую в object storage через signed URL, а тяжёлую обработку запускают async через очередь/оркестратор jobs.", q("Почему upload лучше отдавать в object storage напрямую?", "Чтобы не прогонять большие файлы через application servers и не делать их узким местом."), q("Где держать статус обработки?", "В отдельной metadata базе/таблице, чтобы UI мог опрашивать прогресс и состояние пайплайна."), q("Что делать с частично неуспешным transcoding?", "Хранить per-profile status, ретраить отдельные шаги и не валить весь asset целиком без причины.")),
		systemDesignTask("system-design-notifications-platform", "System Design: notifications platform", "Спроектируй платформу уведомлений: email, push, sms, templates, rate limits, user preferences и deduplication.", "Нужно разделять scheduling, templating, delivery providers и user preferences. Важны dedup, priority, quiet hours и observability по каналам.", q("Почему user preferences должны применяться до dispatch?", "Иначе система будет тратить ресурсы на сообщения, которые всё равно нельзя отправлять."), q("Зачем dedup в notification platform?", "Чтобы одно и то же событие не превратилось в несколько почти одинаковых уведомлений через retry/fan-out."), q("Что считать delivery success?", "Это зависит от канала: accepted by provider, delivered to device, opened by user — это разные уровни.")),
		systemDesignTask("system-design-feature-flags", "System Design: feature flags service", "Спроектируй feature flags service: targeting rules, SDK cache, consistency, audit log и kill switch.", "Главные вопросы — low-latency evaluation, распространение обновлений, безопасный fallback и аудит изменений. Обычно control plane и data plane разделяют.", q("Почему flag evaluation нельзя делать только через synchronous network call?", "Потому что это добавит latency и превратит flags service в SPOF для клиентских запросов."), q("Зачем audit log?", "Чтобы понимать, кто и когда поменял rollout, и быстро разбираться в инцидентах."), q("Что такое kill switch?", "Флаг или механизм, который позволяет мгновенно выключить проблемную функциональность без нового деплоя.")),
		systemDesignTask("system-design-payment-ledger", "System Design: payment ledger", "Спроектируй payment ledger: immutable entries, idempotency, reconciliation, retries и money movement safety.", "Ledger требует append-only модель, идемпотентность команд и сильную трассируемость изменений. Денежные операции лучше оформлять как двойные проводки, а не mutable balances.", q("Почему mutable balance без ledger опасен?", "Потому что теряется история изменений, сложно делать reconciliation и расследовать расхождения."), q("Зачем idempotency key в платёжном API?", "Чтобы повтор запроса не создал второе списание при сетевых ретраях или таймаутах клиента."), q("Что значит reconciliation в этой системе?", "Сверка внутренних записей с внешними провайдерами/банками и поиск расхождений.")),
		systemDesignTask("system-design-feed-ranking", "System Design: feed ranking service", "Спроектируй ленту с ranking: candidate generation, personalized scoring, cache, freshness и fallback без ML.", "Обычно систему делят на candidate generation и ranking. На практике важно уметь деградировать к простому heuristic ranker, если модели или фичи недоступны.", q("Почему candidate generation и ranking лучше разделять?", "Потому что полный scoring по всем объектам слишком дорог, а сначала нужно сузить набор кандидатов."), q("Что деградирует при недоступности online features?", "Можно переключиться на cached features, global popularity или более простой heuristic ranking."), q("Как балансировать freshness и relevance?", "Через фичи времени, exploration rules и смешивание свежего контента с высокорелевантным старым.")),
		systemDesignTask("system-design-api-gateway", "System Design: API gateway for multi-service app", "Спроектируй API gateway: auth, rate limit, routing, retries, circuit breaking, observability и config rollout.", "Gateway не должен превращаться в монолит бизнес-логики, но обязан централизовать cross-cutting concerns: auth, limits, routing, telemetry.", q("Почему retries на gateway опасны без идемпотентности?", "Они могут умножить побочные эффекты downstream write-операций."), q("Что лучше держать в gateway, а что нет?", "Cross-cutting concerns да, бизнес-решения и orchestration лучше держать ближе к домену."), q("Как выкатывать конфиг безопасно?", "Через versioned config, staged rollout и быстрый rollback при росте ошибок.")),
	}
}

func guidedCodingTask(slug string, title string, language string, statement string, starter string, reference string, questions ...InterviewPrepCatalogQuestion) InterviewPrepCatalogTask {
	return InterviewPrepCatalogTask{
		Slug:              slug,
		Title:             title,
		PrepType:          "coding",
		Language:          language,
		IsExecutable:      false,
		ExecutionProfile:  "pure",
		RunnerMode:        "function_io",
		DurationSeconds:   1800,
		Statement:         statement,
		StarterCode:       starter,
		ReferenceSolution: reference,
		IsActive:          true,
		Questions:         questions,
	}
}

func systemDesignTask(slug string, title string, statement string, reference string, questions ...InterviewPrepCatalogQuestion) InterviewPrepCatalogTask {
	return InterviewPrepCatalogTask{
		Slug:              slug,
		Title:             title,
		PrepType:          "system_design",
		Language:          "system_design",
		IsExecutable:      false,
		ExecutionProfile:  "pure",
		RunnerMode:        "function_io",
		DurationSeconds:   2700,
		Statement:         statement,
		StarterCode:       "",
		ReferenceSolution: reference,
		IsActive:          true,
		Questions:         questions,
	}
}

func q(prompt string, answer string) InterviewPrepCatalogQuestion {
	return InterviewPrepCatalogQuestion{
		Prompt:   prompt,
		Answer:   answer,
		Position: 0,
	}
}

func goStarter(body string) string {
	return "package main\n\n" + body
}

func pythonStarter(body string) string {
	return body
}

func sqlStarter(body string) string {
	return body
}
