// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: challenge/v1/challenge.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChallengeService_GetBlindReviewTask_FullMethodName = "/challenge.v1.ChallengeService/GetBlindReviewTask"
	ChallengeService_SubmitBlindReview_FullMethodName  = "/challenge.v1.ChallengeService/SubmitBlindReview"
	ChallengeService_GetSpeedRunRecords_FullMethodName = "/challenge.v1.ChallengeService/GetSpeedRunRecords"
	ChallengeService_GetWeeklyChallenge_FullMethodName = "/challenge.v1.ChallengeService/GetWeeklyChallenge"
)

// ChallengeServiceClient is the client API for ChallengeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChallengeService hosts the read-only "mini-game" modes in druz9:
// blind review, personal speed-run records, weekly boss info. Write
// paths (SubmitDailyReview, SubmitWeeklyBoss, RecordSpeedRun,
// GetDailyLeaderboard) existed historically but were never wired on
// the frontend and have been removed — add them back only when a page
// actually consumes them.
type ChallengeServiceClient interface {
	GetBlindReviewTask(ctx context.Context, in *GetBlindReviewTaskRequest, opts ...grpc.CallOption) (*BlindReviewTask, error)
	SubmitBlindReview(ctx context.Context, in *SubmitBlindReviewRequest, opts ...grpc.CallOption) (*BlindReviewResult, error)
	GetSpeedRunRecords(ctx context.Context, in *GetSpeedRunRecordsRequest, opts ...grpc.CallOption) (*GetSpeedRunRecordsResponse, error)
	GetWeeklyChallenge(ctx context.Context, in *GetWeeklyChallengeRequest, opts ...grpc.CallOption) (*GetWeeklyChallengeResponse, error)
}

type challengeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChallengeServiceClient(cc grpc.ClientConnInterface) ChallengeServiceClient {
	return &challengeServiceClient{cc}
}

func (c *challengeServiceClient) GetBlindReviewTask(ctx context.Context, in *GetBlindReviewTaskRequest, opts ...grpc.CallOption) (*BlindReviewTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlindReviewTask)
	err := c.cc.Invoke(ctx, ChallengeService_GetBlindReviewTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *challengeServiceClient) SubmitBlindReview(ctx context.Context, in *SubmitBlindReviewRequest, opts ...grpc.CallOption) (*BlindReviewResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlindReviewResult)
	err := c.cc.Invoke(ctx, ChallengeService_SubmitBlindReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *challengeServiceClient) GetSpeedRunRecords(ctx context.Context, in *GetSpeedRunRecordsRequest, opts ...grpc.CallOption) (*GetSpeedRunRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpeedRunRecordsResponse)
	err := c.cc.Invoke(ctx, ChallengeService_GetSpeedRunRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *challengeServiceClient) GetWeeklyChallenge(ctx context.Context, in *GetWeeklyChallengeRequest, opts ...grpc.CallOption) (*GetWeeklyChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeeklyChallengeResponse)
	err := c.cc.Invoke(ctx, ChallengeService_GetWeeklyChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChallengeServiceServer is the server API for ChallengeService service.
// All implementations must embed UnimplementedChallengeServiceServer
// for forward compatibility.
//
// ChallengeService hosts the read-only "mini-game" modes in druz9:
// blind review, personal speed-run records, weekly boss info. Write
// paths (SubmitDailyReview, SubmitWeeklyBoss, RecordSpeedRun,
// GetDailyLeaderboard) existed historically but were never wired on
// the frontend and have been removed — add them back only when a page
// actually consumes them.
type ChallengeServiceServer interface {
	GetBlindReviewTask(context.Context, *GetBlindReviewTaskRequest) (*BlindReviewTask, error)
	SubmitBlindReview(context.Context, *SubmitBlindReviewRequest) (*BlindReviewResult, error)
	GetSpeedRunRecords(context.Context, *GetSpeedRunRecordsRequest) (*GetSpeedRunRecordsResponse, error)
	GetWeeklyChallenge(context.Context, *GetWeeklyChallengeRequest) (*GetWeeklyChallengeResponse, error)
	mustEmbedUnimplementedChallengeServiceServer()
}

// UnimplementedChallengeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChallengeServiceServer struct{}

func (UnimplementedChallengeServiceServer) GetBlindReviewTask(context.Context, *GetBlindReviewTaskRequest) (*BlindReviewTask, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlindReviewTask not implemented")
}
func (UnimplementedChallengeServiceServer) SubmitBlindReview(context.Context, *SubmitBlindReviewRequest) (*BlindReviewResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBlindReview not implemented")
}
func (UnimplementedChallengeServiceServer) GetSpeedRunRecords(context.Context, *GetSpeedRunRecordsRequest) (*GetSpeedRunRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpeedRunRecords not implemented")
}
func (UnimplementedChallengeServiceServer) GetWeeklyChallenge(context.Context, *GetWeeklyChallengeRequest) (*GetWeeklyChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeeklyChallenge not implemented")
}
func (UnimplementedChallengeServiceServer) mustEmbedUnimplementedChallengeServiceServer() {}
func (UnimplementedChallengeServiceServer) testEmbeddedByValue()                          {}

// UnsafeChallengeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChallengeServiceServer will
// result in compilation errors.
type UnsafeChallengeServiceServer interface {
	mustEmbedUnimplementedChallengeServiceServer()
}

func RegisterChallengeServiceServer(s grpc.ServiceRegistrar, srv ChallengeServiceServer) {
	// If the following call panics, it indicates UnimplementedChallengeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChallengeService_ServiceDesc, srv)
}

func _ChallengeService_GetBlindReviewTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlindReviewTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeServiceServer).GetBlindReviewTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChallengeService_GetBlindReviewTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeServiceServer).GetBlindReviewTask(ctx, req.(*GetBlindReviewTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChallengeService_SubmitBlindReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBlindReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeServiceServer).SubmitBlindReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChallengeService_SubmitBlindReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeServiceServer).SubmitBlindReview(ctx, req.(*SubmitBlindReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChallengeService_GetSpeedRunRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpeedRunRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeServiceServer).GetSpeedRunRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChallengeService_GetSpeedRunRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeServiceServer).GetSpeedRunRecords(ctx, req.(*GetSpeedRunRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChallengeService_GetWeeklyChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeeklyChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeServiceServer).GetWeeklyChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChallengeService_GetWeeklyChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeServiceServer).GetWeeklyChallenge(ctx, req.(*GetWeeklyChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChallengeService_ServiceDesc is the grpc.ServiceDesc for ChallengeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChallengeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "challenge.v1.ChallengeService",
	HandlerType: (*ChallengeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlindReviewTask",
			Handler:    _ChallengeService_GetBlindReviewTask_Handler,
		},
		{
			MethodName: "SubmitBlindReview",
			Handler:    _ChallengeService_SubmitBlindReview_Handler,
		},
		{
			MethodName: "GetSpeedRunRecords",
			Handler:    _ChallengeService_GetSpeedRunRecords_Handler,
		},
		{
			MethodName: "GetWeeklyChallenge",
			Handler:    _ChallengeService_GetWeeklyChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "challenge/v1/challenge.proto",
}
