// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: referral/v1/referral.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReferralService_ListReferrals_FullMethodName  = "/referral.v1.ReferralService/ListReferrals"
	ReferralService_CreateReferral_FullMethodName = "/referral.v1.ReferralService/CreateReferral"
	ReferralService_UpdateReferral_FullMethodName = "/referral.v1.ReferralService/UpdateReferral"
	ReferralService_DeleteReferral_FullMethodName = "/referral.v1.ReferralService/DeleteReferral"
)

// ReferralServiceClient is the client API for ReferralService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReferralServiceClient interface {
	ListReferrals(ctx context.Context, in *ListReferralsRequest, opts ...grpc.CallOption) (*ListReferralsResponse, error)
	CreateReferral(ctx context.Context, in *CreateReferralRequest, opts ...grpc.CallOption) (*ReferralResponse, error)
	UpdateReferral(ctx context.Context, in *UpdateReferralRequest, opts ...grpc.CallOption) (*ReferralResponse, error)
	DeleteReferral(ctx context.Context, in *DeleteReferralRequest, opts ...grpc.CallOption) (*ReferralStatusResponse, error)
}

type referralServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReferralServiceClient(cc grpc.ClientConnInterface) ReferralServiceClient {
	return &referralServiceClient{cc}
}

func (c *referralServiceClient) ListReferrals(ctx context.Context, in *ListReferralsRequest, opts ...grpc.CallOption) (*ListReferralsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReferralsResponse)
	err := c.cc.Invoke(ctx, ReferralService_ListReferrals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralServiceClient) CreateReferral(ctx context.Context, in *CreateReferralRequest, opts ...grpc.CallOption) (*ReferralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReferralResponse)
	err := c.cc.Invoke(ctx, ReferralService_CreateReferral_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralServiceClient) UpdateReferral(ctx context.Context, in *UpdateReferralRequest, opts ...grpc.CallOption) (*ReferralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReferralResponse)
	err := c.cc.Invoke(ctx, ReferralService_UpdateReferral_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralServiceClient) DeleteReferral(ctx context.Context, in *DeleteReferralRequest, opts ...grpc.CallOption) (*ReferralStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReferralStatusResponse)
	err := c.cc.Invoke(ctx, ReferralService_DeleteReferral_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReferralServiceServer is the server API for ReferralService service.
// All implementations must embed UnimplementedReferralServiceServer
// for forward compatibility.
type ReferralServiceServer interface {
	ListReferrals(context.Context, *ListReferralsRequest) (*ListReferralsResponse, error)
	CreateReferral(context.Context, *CreateReferralRequest) (*ReferralResponse, error)
	UpdateReferral(context.Context, *UpdateReferralRequest) (*ReferralResponse, error)
	DeleteReferral(context.Context, *DeleteReferralRequest) (*ReferralStatusResponse, error)
	mustEmbedUnimplementedReferralServiceServer()
}

// UnimplementedReferralServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReferralServiceServer struct{}

func (UnimplementedReferralServiceServer) ListReferrals(context.Context, *ListReferralsRequest) (*ListReferralsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReferrals not implemented")
}
func (UnimplementedReferralServiceServer) CreateReferral(context.Context, *CreateReferralRequest) (*ReferralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReferral not implemented")
}
func (UnimplementedReferralServiceServer) UpdateReferral(context.Context, *UpdateReferralRequest) (*ReferralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReferral not implemented")
}
func (UnimplementedReferralServiceServer) DeleteReferral(context.Context, *DeleteReferralRequest) (*ReferralStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteReferral not implemented")
}
func (UnimplementedReferralServiceServer) mustEmbedUnimplementedReferralServiceServer() {}
func (UnimplementedReferralServiceServer) testEmbeddedByValue()                         {}

// UnsafeReferralServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReferralServiceServer will
// result in compilation errors.
type UnsafeReferralServiceServer interface {
	mustEmbedUnimplementedReferralServiceServer()
}

func RegisterReferralServiceServer(s grpc.ServiceRegistrar, srv ReferralServiceServer) {
	// If the following call panics, it indicates UnimplementedReferralServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReferralService_ServiceDesc, srv)
}

func _ReferralService_ListReferrals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReferralsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServiceServer).ListReferrals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferralService_ListReferrals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServiceServer).ListReferrals(ctx, req.(*ListReferralsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferralService_CreateReferral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReferralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServiceServer).CreateReferral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferralService_CreateReferral_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServiceServer).CreateReferral(ctx, req.(*CreateReferralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferralService_UpdateReferral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReferralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServiceServer).UpdateReferral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferralService_UpdateReferral_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServiceServer).UpdateReferral(ctx, req.(*UpdateReferralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferralService_DeleteReferral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReferralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServiceServer).DeleteReferral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferralService_DeleteReferral_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServiceServer).DeleteReferral(ctx, req.(*DeleteReferralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReferralService_ServiceDesc is the grpc.ServiceDesc for ReferralService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReferralService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "referral.v1.ReferralService",
	HandlerType: (*ReferralServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListReferrals",
			Handler:    _ReferralService_ListReferrals_Handler,
		},
		{
			MethodName: "CreateReferral",
			Handler:    _ReferralService_CreateReferral_Handler,
		},
		{
			MethodName: "UpdateReferral",
			Handler:    _ReferralService_UpdateReferral_Handler,
		},
		{
			MethodName: "DeleteReferral",
			Handler:    _ReferralService_DeleteReferral_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "referral/v1/referral.proto",
}
