// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: referral/v1/referral.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListReferralsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReferralsRequest) Reset() {
	*x = ListReferralsRequest{}
	mi := &file_referral_v1_referral_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReferralsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferralsRequest) ProtoMessage() {}

func (x *ListReferralsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_v1_referral_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferralsRequest.ProtoReflect.Descriptor instead.
func (*ListReferralsRequest) Descriptor() ([]byte, []int) {
	return file_referral_v1_referral_proto_rawDescGZIP(), []int{0}
}

func (x *ListReferralsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReferralsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateReferralRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company        string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	VacancyUrl     string                 `protobuf:"bytes,3,opt,name=vacancy_url,json=vacancyUrl,proto3" json:"vacancy_url,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Experience     string                 `protobuf:"bytes,5,opt,name=experience,proto3" json:"experience,omitempty"`
	Location       string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	EmploymentType string                 `protobuf:"bytes,7,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateReferralRequest) Reset() {
	*x = CreateReferralRequest{}
	mi := &file_referral_v1_referral_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReferralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReferralRequest) ProtoMessage() {}

func (x *CreateReferralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_v1_referral_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReferralRequest.ProtoReflect.Descriptor instead.
func (*CreateReferralRequest) Descriptor() ([]byte, []int) {
	return file_referral_v1_referral_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReferralRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateReferralRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreateReferralRequest) GetVacancyUrl() string {
	if x != nil {
		return x.VacancyUrl
	}
	return ""
}

func (x *CreateReferralRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateReferralRequest) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *CreateReferralRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateReferralRequest) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

type UpdateReferralRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReferralId     string                 `protobuf:"bytes,1,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Company        string                 `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	VacancyUrl     string                 `protobuf:"bytes,4,opt,name=vacancy_url,json=vacancyUrl,proto3" json:"vacancy_url,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Experience     string                 `protobuf:"bytes,6,opt,name=experience,proto3" json:"experience,omitempty"`
	Location       string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	EmploymentType string                 `protobuf:"bytes,8,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateReferralRequest) Reset() {
	*x = UpdateReferralRequest{}
	mi := &file_referral_v1_referral_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReferralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReferralRequest) ProtoMessage() {}

func (x *UpdateReferralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_v1_referral_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReferralRequest.ProtoReflect.Descriptor instead.
func (*UpdateReferralRequest) Descriptor() ([]byte, []int) {
	return file_referral_v1_referral_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateReferralRequest) GetReferralId() string {
	if x != nil {
		return x.ReferralId
	}
	return ""
}

func (x *UpdateReferralRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateReferralRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UpdateReferralRequest) GetVacancyUrl() string {
	if x != nil {
		return x.VacancyUrl
	}
	return ""
}

func (x *UpdateReferralRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateReferralRequest) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *UpdateReferralRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateReferralRequest) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

type DeleteReferralRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferralId    string                 `protobuf:"bytes,1,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReferralRequest) Reset() {
	*x = DeleteReferralRequest{}
	mi := &file_referral_v1_referral_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReferralRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReferralRequest) ProtoMessage() {}

func (x *DeleteReferralRequest) ProtoReflect() protoreflect.Message {
	mi := &file_referral_v1_referral_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReferralRequest.ProtoReflect.Descriptor instead.
func (*DeleteReferralRequest) Descriptor() ([]byte, []int) {
	return file_referral_v1_referral_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteReferralRequest) GetReferralId() string {
	if x != nil {
		return x.ReferralId
	}
	return ""
}

type ListReferralsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referrals     []*Referral            `protobuf:"bytes,1,rep,name=referrals,proto3" json:"referrals,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReferralsResponse) Reset() {
	*x = ListReferralsResponse{}
	mi := &file_referral_v1_referral_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReferralsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferralsResponse) ProtoMessage() {}

func (x *ListReferralsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_v1_referral_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferralsResponse.ProtoReflect.Descriptor instead.
func (*ListReferralsResponse) Descriptor() ([]byte, []int) {
	return file_referral_v1_referral_proto_rawDescGZIP(), []int{4}
}

func (x *ListReferralsResponse) GetReferrals() []*Referral {
	if x != nil {
		return x.Referrals
	}
	return nil
}

func (x *ListReferralsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReferralsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListReferralsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListReferralsResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

type ReferralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referral      *Referral              `protobuf:"bytes,1,opt,name=referral,proto3" json:"referral,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferralResponse) Reset() {
	*x = ReferralResponse{}
	mi := &file_referral_v1_referral_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferralResponse) ProtoMessage() {}

func (x *ReferralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_v1_referral_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferralResponse.ProtoReflect.Descriptor instead.
func (*ReferralResponse) Descriptor() ([]byte, []int) {
	return file_referral_v1_referral_proto_rawDescGZIP(), []int{5}
}

func (x *ReferralResponse) GetReferral() *Referral {
	if x != nil {
		return x.Referral
	}
	return nil
}

type ReferralStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferralStatusResponse) Reset() {
	*x = ReferralStatusResponse{}
	mi := &file_referral_v1_referral_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferralStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferralStatusResponse) ProtoMessage() {}

func (x *ReferralStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_referral_v1_referral_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferralStatusResponse.ProtoReflect.Descriptor instead.
func (*ReferralStatusResponse) Descriptor() ([]byte, []int) {
	return file_referral_v1_referral_proto_rawDescGZIP(), []int{6}
}

func (x *ReferralStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Referral struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                   string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthorName               string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorTelegramUsername   string                 `protobuf:"bytes,4,opt,name=author_telegram_username,json=authorTelegramUsername,proto3" json:"author_telegram_username,omitempty"`
	AuthorTelegramProfileUrl string                 `protobuf:"bytes,5,opt,name=author_telegram_profile_url,json=authorTelegramProfileUrl,proto3" json:"author_telegram_profile_url,omitempty"`
	Title                    string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Company                  string                 `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	VacancyUrl               string                 `protobuf:"bytes,8,opt,name=vacancy_url,json=vacancyUrl,proto3" json:"vacancy_url,omitempty"`
	Description              string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Experience               string                 `protobuf:"bytes,10,opt,name=experience,proto3" json:"experience,omitempty"`
	Location                 string                 `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	EmploymentType           string                 `protobuf:"bytes,12,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	IsOwner                  bool                   `protobuf:"varint,13,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	CreatedAt                *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Referral) Reset() {
	*x = Referral{}
	mi := &file_referral_v1_referral_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Referral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Referral) ProtoMessage() {}

func (x *Referral) ProtoReflect() protoreflect.Message {
	mi := &file_referral_v1_referral_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Referral.ProtoReflect.Descriptor instead.
func (*Referral) Descriptor() ([]byte, []int) {
	return file_referral_v1_referral_proto_rawDescGZIP(), []int{7}
}

func (x *Referral) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Referral) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Referral) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Referral) GetAuthorTelegramUsername() string {
	if x != nil {
		return x.AuthorTelegramUsername
	}
	return ""
}

func (x *Referral) GetAuthorTelegramProfileUrl() string {
	if x != nil {
		return x.AuthorTelegramProfileUrl
	}
	return ""
}

func (x *Referral) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Referral) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Referral) GetVacancyUrl() string {
	if x != nil {
		return x.VacancyUrl
	}
	return ""
}

func (x *Referral) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Referral) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *Referral) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Referral) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *Referral) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

func (x *Referral) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Referral) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_referral_v1_referral_proto protoreflect.FileDescriptor

const file_referral_v1_referral_proto_rawDesc = "" +
	"\n" +
	"\x1areferral/v1/referral.proto\x12\vreferral.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x14ListReferralsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xef\x01\n" +
	"\x15CreateReferralRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x1f\n" +
	"\vvacancy_url\x18\x03 \x01(\tR\n" +
	"vacancyUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"experience\x18\x05 \x01(\tR\n" +
	"experience\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12'\n" +
	"\x0femployment_type\x18\a \x01(\tR\x0eemploymentType\"\x90\x02\n" +
	"\x15UpdateReferralRequest\x12\x1f\n" +
	"\vreferral_id\x18\x01 \x01(\tR\n" +
	"referralId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x03 \x01(\tR\acompany\x12\x1f\n" +
	"\vvacancy_url\x18\x04 \x01(\tR\n" +
	"vacancyUrl\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"experience\x18\x06 \x01(\tR\n" +
	"experience\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12'\n" +
	"\x0femployment_type\x18\b \x01(\tR\x0eemploymentType\"8\n" +
	"\x15DeleteReferralRequest\x12\x1f\n" +
	"\vreferral_id\x18\x01 \x01(\tR\n" +
	"referralId\"\xbf\x01\n" +
	"\x15ListReferralsResponse\x123\n" +
	"\treferrals\x18\x01 \x03(\v2\x15.referral.v1.ReferralR\treferrals\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\"\n" +
	"\rhas_next_page\x18\x05 \x01(\bR\vhasNextPage\"E\n" +
	"\x10ReferralResponse\x121\n" +
	"\breferral\x18\x01 \x01(\v2\x15.referral.v1.ReferralR\breferral\"0\n" +
	"\x16ReferralStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xb6\x04\n" +
	"\bReferral\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x128\n" +
	"\x18author_telegram_username\x18\x04 \x01(\tR\x16authorTelegramUsername\x12=\n" +
	"\x1bauthor_telegram_profile_url\x18\x05 \x01(\tR\x18authorTelegramProfileUrl\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\a \x01(\tR\acompany\x12\x1f\n" +
	"\vvacancy_url\x18\b \x01(\tR\n" +
	"vacancyUrl\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"experience\x18\n" +
	" \x01(\tR\n" +
	"experience\x12\x1a\n" +
	"\blocation\x18\v \x01(\tR\blocation\x12'\n" +
	"\x0femployment_type\x18\f \x01(\tR\x0eemploymentType\x12\x19\n" +
	"\bis_owner\x18\r \x01(\bR\aisOwner\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xfd\x03\n" +
	"\x0fReferralService\x12q\n" +
	"\rListReferrals\x12!.referral.v1.ListReferralsRequest\x1a\".referral.v1.ListReferralsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/referrals\x12q\n" +
	"\x0eCreateReferral\x12\".referral.v1.CreateReferralRequest\x1a\x1d.referral.v1.ReferralResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/referrals\x12\x7f\n" +
	"\x0eUpdateReferral\x12\".referral.v1.UpdateReferralRequest\x1a\x1d.referral.v1.ReferralResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/api/v1/referrals/{referral_id}\x12\x82\x01\n" +
	"\x0eDeleteReferral\x12\".referral.v1.DeleteReferralRequest\x1a#.referral.v1.ReferralStatusResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/api/v1/referrals/{referral_id}B\x1cZ\x1aapi/pkg/api/referral/v1;v1b\x06proto3"

var (
	file_referral_v1_referral_proto_rawDescOnce sync.Once
	file_referral_v1_referral_proto_rawDescData []byte
)

func file_referral_v1_referral_proto_rawDescGZIP() []byte {
	file_referral_v1_referral_proto_rawDescOnce.Do(func() {
		file_referral_v1_referral_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_referral_v1_referral_proto_rawDesc), len(file_referral_v1_referral_proto_rawDesc)))
	})
	return file_referral_v1_referral_proto_rawDescData
}

var file_referral_v1_referral_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_referral_v1_referral_proto_goTypes = []any{
	(*ListReferralsRequest)(nil),   // 0: referral.v1.ListReferralsRequest
	(*CreateReferralRequest)(nil),  // 1: referral.v1.CreateReferralRequest
	(*UpdateReferralRequest)(nil),  // 2: referral.v1.UpdateReferralRequest
	(*DeleteReferralRequest)(nil),  // 3: referral.v1.DeleteReferralRequest
	(*ListReferralsResponse)(nil),  // 4: referral.v1.ListReferralsResponse
	(*ReferralResponse)(nil),       // 5: referral.v1.ReferralResponse
	(*ReferralStatusResponse)(nil), // 6: referral.v1.ReferralStatusResponse
	(*Referral)(nil),               // 7: referral.v1.Referral
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_referral_v1_referral_proto_depIdxs = []int32{
	7, // 0: referral.v1.ListReferralsResponse.referrals:type_name -> referral.v1.Referral
	7, // 1: referral.v1.ReferralResponse.referral:type_name -> referral.v1.Referral
	8, // 2: referral.v1.Referral.created_at:type_name -> google.protobuf.Timestamp
	8, // 3: referral.v1.Referral.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: referral.v1.ReferralService.ListReferrals:input_type -> referral.v1.ListReferralsRequest
	1, // 5: referral.v1.ReferralService.CreateReferral:input_type -> referral.v1.CreateReferralRequest
	2, // 6: referral.v1.ReferralService.UpdateReferral:input_type -> referral.v1.UpdateReferralRequest
	3, // 7: referral.v1.ReferralService.DeleteReferral:input_type -> referral.v1.DeleteReferralRequest
	4, // 8: referral.v1.ReferralService.ListReferrals:output_type -> referral.v1.ListReferralsResponse
	5, // 9: referral.v1.ReferralService.CreateReferral:output_type -> referral.v1.ReferralResponse
	5, // 10: referral.v1.ReferralService.UpdateReferral:output_type -> referral.v1.ReferralResponse
	6, // 11: referral.v1.ReferralService.DeleteReferral:output_type -> referral.v1.ReferralStatusResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_referral_v1_referral_proto_init() }
func file_referral_v1_referral_proto_init() {
	if File_referral_v1_referral_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_referral_v1_referral_proto_rawDesc), len(file_referral_v1_referral_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_referral_v1_referral_proto_goTypes,
		DependencyIndexes: file_referral_v1_referral_proto_depIdxs,
		MessageInfos:      file_referral_v1_referral_proto_msgTypes,
	}.Build()
	File_referral_v1_referral_proto = out.File
	file_referral_v1_referral_proto_goTypes = nil
	file_referral_v1_referral_proto_depIdxs = nil
}
