// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: referral/v1/referral.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationReferralServiceCreateReferral = "/referral.v1.ReferralService/CreateReferral"
const OperationReferralServiceDeleteReferral = "/referral.v1.ReferralService/DeleteReferral"
const OperationReferralServiceListReferrals = "/referral.v1.ReferralService/ListReferrals"
const OperationReferralServiceUpdateReferral = "/referral.v1.ReferralService/UpdateReferral"

type ReferralServiceHTTPServer interface {
	CreateReferral(context.Context, *CreateReferralRequest) (*ReferralResponse, error)
	DeleteReferral(context.Context, *DeleteReferralRequest) (*ReferralStatusResponse, error)
	ListReferrals(context.Context, *ListReferralsRequest) (*ListReferralsResponse, error)
	UpdateReferral(context.Context, *UpdateReferralRequest) (*ReferralResponse, error)
}

func RegisterReferralServiceHTTPServer(s *http.Server, srv ReferralServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/referrals", _ReferralService_ListReferrals0_HTTP_Handler(srv))
	r.POST("/api/v1/referrals", _ReferralService_CreateReferral0_HTTP_Handler(srv))
	r.PUT("/api/v1/referrals/{referral_id}", _ReferralService_UpdateReferral0_HTTP_Handler(srv))
	r.DELETE("/api/v1/referrals/{referral_id}", _ReferralService_DeleteReferral0_HTTP_Handler(srv))
}

func _ReferralService_ListReferrals0_HTTP_Handler(srv ReferralServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReferralsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralServiceListReferrals)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListReferrals(ctx, req.(*ListReferralsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReferralsResponse)
		return ctx.Result(200, reply)
	}
}

func _ReferralService_CreateReferral0_HTTP_Handler(srv ReferralServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateReferralRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralServiceCreateReferral)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateReferral(ctx, req.(*CreateReferralRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReferralResponse)
		return ctx.Result(200, reply)
	}
}

func _ReferralService_UpdateReferral0_HTTP_Handler(srv ReferralServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateReferralRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralServiceUpdateReferral)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateReferral(ctx, req.(*UpdateReferralRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReferralResponse)
		return ctx.Result(200, reply)
	}
}

func _ReferralService_DeleteReferral0_HTTP_Handler(srv ReferralServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteReferralRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralServiceDeleteReferral)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteReferral(ctx, req.(*DeleteReferralRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReferralStatusResponse)
		return ctx.Result(200, reply)
	}
}

type ReferralServiceHTTPClient interface {
	CreateReferral(ctx context.Context, req *CreateReferralRequest, opts ...http.CallOption) (rsp *ReferralResponse, err error)
	DeleteReferral(ctx context.Context, req *DeleteReferralRequest, opts ...http.CallOption) (rsp *ReferralStatusResponse, err error)
	ListReferrals(ctx context.Context, req *ListReferralsRequest, opts ...http.CallOption) (rsp *ListReferralsResponse, err error)
	UpdateReferral(ctx context.Context, req *UpdateReferralRequest, opts ...http.CallOption) (rsp *ReferralResponse, err error)
}

type ReferralServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewReferralServiceHTTPClient(client *http.Client) ReferralServiceHTTPClient {
	return &ReferralServiceHTTPClientImpl{client}
}

func (c *ReferralServiceHTTPClientImpl) CreateReferral(ctx context.Context, in *CreateReferralRequest, opts ...http.CallOption) (*ReferralResponse, error) {
	var out ReferralResponse
	pattern := "/api/v1/referrals"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationReferralServiceCreateReferral))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferralServiceHTTPClientImpl) DeleteReferral(ctx context.Context, in *DeleteReferralRequest, opts ...http.CallOption) (*ReferralStatusResponse, error) {
	var out ReferralStatusResponse
	pattern := "/api/v1/referrals/{referral_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferralServiceDeleteReferral))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferralServiceHTTPClientImpl) ListReferrals(ctx context.Context, in *ListReferralsRequest, opts ...http.CallOption) (*ListReferralsResponse, error) {
	var out ListReferralsResponse
	pattern := "/api/v1/referrals"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferralServiceListReferrals))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferralServiceHTTPClientImpl) UpdateReferral(ctx context.Context, in *UpdateReferralRequest, opts ...http.CallOption) (*ReferralResponse, error) {
	var out ReferralResponse
	pattern := "/api/v1/referrals/{referral_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationReferralServiceUpdateReferral))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
