// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "api/internal/model"

	time "time"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id uuid.UUID) (*model.FriendChallenge, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.FriendChallenge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.FriendChallenge, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.FriendChallenge); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FriendChallenge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Repository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) GetByID(ctx interface{}, id interface{}) *Repository_GetByID_Call {
	return &Repository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *Repository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_GetByID_Call) Return(_a0 *model.FriendChallenge, _a1 error) *Repository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.FriendChallenge, error)) *Repository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, ch
func (_m *Repository) Insert(ctx context.Context, ch *model.FriendChallenge) error {
	ret := _m.Called(ctx, ch)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.FriendChallenge) error); ok {
		r0 = rf(ctx, ch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type Repository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - ch *model.FriendChallenge
func (_e *Repository_Expecter) Insert(ctx interface{}, ch interface{}) *Repository_Insert_Call {
	return &Repository_Insert_Call{Call: _e.mock.On("Insert", ctx, ch)}
}

func (_c *Repository_Insert_Call) Run(run func(ctx context.Context, ch *model.FriendChallenge)) *Repository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.FriendChallenge))
	})
	return _c
}

func (_c *Repository_Insert_Call) Return(_a0 error) *Repository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Insert_Call) RunAndReturn(run func(context.Context, *model.FriendChallenge) error) *Repository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// ListHistory provides a mock function with given fields: ctx, userID, limit, offset
func (_m *Repository) ListHistory(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]*model.FriendChallenge, int32, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListHistory")
	}

	var r0 []*model.FriendChallenge
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) ([]*model.FriendChallenge, int32, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) []*model.FriendChallenge); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FriendChallenge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, int32) int32); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int32, int32) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_ListHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHistory'
type Repository_ListHistory_Call struct {
	*mock.Call
}

// ListHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int32
//   - offset int32
func (_e *Repository_Expecter) ListHistory(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *Repository_ListHistory_Call {
	return &Repository_ListHistory_Call{Call: _e.mock.On("ListHistory", ctx, userID, limit, offset)}
}

func (_c *Repository_ListHistory_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32)) *Repository_ListHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *Repository_ListHistory_Call) Return(_a0 []*model.FriendChallenge, _a1 int32, _a2 error) *Repository_ListHistory_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_ListHistory_Call) RunAndReturn(run func(context.Context, uuid.UUID, int32, int32) ([]*model.FriendChallenge, int32, error)) *Repository_ListHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListIncoming provides a mock function with given fields: ctx, userID, limit, offset
func (_m *Repository) ListIncoming(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]*model.FriendChallenge, int32, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListIncoming")
	}

	var r0 []*model.FriendChallenge
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) ([]*model.FriendChallenge, int32, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) []*model.FriendChallenge); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FriendChallenge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, int32) int32); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int32, int32) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_ListIncoming_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIncoming'
type Repository_ListIncoming_Call struct {
	*mock.Call
}

// ListIncoming is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int32
//   - offset int32
func (_e *Repository_Expecter) ListIncoming(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *Repository_ListIncoming_Call {
	return &Repository_ListIncoming_Call{Call: _e.mock.On("ListIncoming", ctx, userID, limit, offset)}
}

func (_c *Repository_ListIncoming_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32)) *Repository_ListIncoming_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *Repository_ListIncoming_Call) Return(_a0 []*model.FriendChallenge, _a1 int32, _a2 error) *Repository_ListIncoming_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_ListIncoming_Call) RunAndReturn(run func(context.Context, uuid.UUID, int32, int32) ([]*model.FriendChallenge, int32, error)) *Repository_ListIncoming_Call {
	_c.Call.Return(run)
	return _c
}

// ListSent provides a mock function with given fields: ctx, userID, limit, offset
func (_m *Repository) ListSent(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]*model.FriendChallenge, int32, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListSent")
	}

	var r0 []*model.FriendChallenge
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) ([]*model.FriendChallenge, int32, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) []*model.FriendChallenge); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FriendChallenge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, int32) int32); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int32, int32) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_ListSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSent'
type Repository_ListSent_Call struct {
	*mock.Call
}

// ListSent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int32
//   - offset int32
func (_e *Repository_Expecter) ListSent(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *Repository_ListSent_Call {
	return &Repository_ListSent_Call{Call: _e.mock.On("ListSent", ctx, userID, limit, offset)}
}

func (_c *Repository_ListSent_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32)) *Repository_ListSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *Repository_ListSent_Call) Return(_a0 []*model.FriendChallenge, _a1 int32, _a2 error) *Repository_ListSent_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_ListSent_Call) RunAndReturn(run func(context.Context, uuid.UUID, int32, int32) ([]*model.FriendChallenge, int32, error)) *Repository_ListSent_Call {
	_c.Call.Return(run)
	return _c
}

// SweepExpired provides a mock function with given fields: ctx, now
func (_m *Repository) SweepExpired(ctx context.Context, now time.Time) (int, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for SweepExpired")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int); ok {
		r0 = rf(ctx, now)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_SweepExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SweepExpired'
type Repository_SweepExpired_Call struct {
	*mock.Call
}

// SweepExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *Repository_Expecter) SweepExpired(ctx interface{}, now interface{}) *Repository_SweepExpired_Call {
	return &Repository_SweepExpired_Call{Call: _e.mock.On("SweepExpired", ctx, now)}
}

func (_c *Repository_SweepExpired_Call) Run(run func(ctx context.Context, now time.Time)) *Repository_SweepExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *Repository_SweepExpired_Call) Return(_a0 int, _a1 error) *Repository_SweepExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_SweepExpired_Call) RunAndReturn(run func(context.Context, time.Time) (int, error)) *Repository_SweepExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, ch
func (_m *Repository) Update(ctx context.Context, ch *model.FriendChallenge) error {
	ret := _m.Called(ctx, ch)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.FriendChallenge) error); ok {
		r0 = rf(ctx, ch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ch *model.FriendChallenge
func (_e *Repository_Expecter) Update(ctx interface{}, ch interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, ch)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, ch *model.FriendChallenge)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.FriendChallenge))
	})
	return _c
}

func (_c *Repository_Update_Call) Return(_a0 error) *Repository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(context.Context, *model.FriendChallenge) error) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
