// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: game/skills/v1/skills.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSkillTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillTreeRequest) Reset() {
	*x = GetSkillTreeRequest{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillTreeRequest) ProtoMessage() {}

func (x *GetSkillTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillTreeRequest.ProtoReflect.Descriptor instead.
func (*GetSkillTreeRequest) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{0}
}

type GetSkillTreeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Nodes           []*SkillNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges           []*SkillEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	PointsAvailable int32                  `protobuf:"varint,3,opt,name=points_available,json=pointsAvailable,proto3" json:"points_available,omitempty"`
	PointsEarned    int32                  `protobuf:"varint,4,opt,name=points_earned,json=pointsEarned,proto3" json:"points_earned,omitempty"`
	PointsSpent     int32                  `protobuf:"varint,5,opt,name=points_spent,json=pointsSpent,proto3" json:"points_spent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSkillTreeResponse) Reset() {
	*x = GetSkillTreeResponse{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillTreeResponse) ProtoMessage() {}

func (x *GetSkillTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillTreeResponse.ProtoReflect.Descriptor instead.
func (*GetSkillTreeResponse) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{1}
}

func (x *GetSkillTreeResponse) GetNodes() []*SkillNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetSkillTreeResponse) GetEdges() []*SkillEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *GetSkillTreeResponse) GetPointsAvailable() int32 {
	if x != nil {
		return x.PointsAvailable
	}
	return 0
}

func (x *GetSkillTreeResponse) GetPointsEarned() int32 {
	if x != nil {
		return x.PointsEarned
	}
	return 0
}

func (x *GetSkillTreeResponse) GetPointsSpent() int32 {
	if x != nil {
		return x.PointsSpent
	}
	return 0
}

type GetSkillPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillPointsRequest) Reset() {
	*x = GetSkillPointsRequest{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillPointsRequest) ProtoMessage() {}

func (x *GetSkillPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillPointsRequest.ProtoReflect.Descriptor instead.
func (*GetSkillPointsRequest) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{2}
}

type GetSkillPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     int32                  `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Earned        int32                  `protobuf:"varint,2,opt,name=earned,proto3" json:"earned,omitempty"`
	Spent         int32                  `protobuf:"varint,3,opt,name=spent,proto3" json:"spent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillPointsResponse) Reset() {
	*x = GetSkillPointsResponse{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillPointsResponse) ProtoMessage() {}

func (x *GetSkillPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillPointsResponse.ProtoReflect.Descriptor instead.
func (*GetSkillPointsResponse) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{3}
}

func (x *GetSkillPointsResponse) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetSkillPointsResponse) GetEarned() int32 {
	if x != nil {
		return x.Earned
	}
	return 0
}

func (x *GetSkillPointsResponse) GetSpent() int32 {
	if x != nil {
		return x.Spent
	}
	return 0
}

type AllocateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateSkillRequest) Reset() {
	*x = AllocateSkillRequest{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSkillRequest) ProtoMessage() {}

func (x *AllocateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateSkillRequest.ProtoReflect.Descriptor instead.
func (*AllocateSkillRequest) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{4}
}

func (x *AllocateSkillRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

type AllocateSkillResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	PointsRemaining int32                  `protobuf:"varint,3,opt,name=points_remaining,json=pointsRemaining,proto3" json:"points_remaining,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllocateSkillResponse) Reset() {
	*x = AllocateSkillResponse{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSkillResponse) ProtoMessage() {}

func (x *AllocateSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateSkillResponse.ProtoReflect.Descriptor instead.
func (*AllocateSkillResponse) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{5}
}

func (x *AllocateSkillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AllocateSkillResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AllocateSkillResponse) GetPointsRemaining() int32 {
	if x != nil {
		return x.PointsRemaining
	}
	return 0
}

type RefundSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundSkillRequest) Reset() {
	*x = RefundSkillRequest{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundSkillRequest) ProtoMessage() {}

func (x *RefundSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundSkillRequest.ProtoReflect.Descriptor instead.
func (*RefundSkillRequest) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{6}
}

func (x *RefundSkillRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

type RefundSkillResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	GoldCost       int32                  `protobuf:"varint,3,opt,name=gold_cost,json=goldCost,proto3" json:"gold_cost,omitempty"`
	PointsReturned int32                  `protobuf:"varint,4,opt,name=points_returned,json=pointsReturned,proto3" json:"points_returned,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefundSkillResponse) Reset() {
	*x = RefundSkillResponse{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundSkillResponse) ProtoMessage() {}

func (x *RefundSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundSkillResponse.ProtoReflect.Descriptor instead.
func (*RefundSkillResponse) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{7}
}

func (x *RefundSkillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefundSkillResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RefundSkillResponse) GetGoldCost() int32 {
	if x != nil {
		return x.GoldCost
	}
	return 0
}

func (x *RefundSkillResponse) GetPointsReturned() int32 {
	if x != nil {
		return x.PointsReturned
	}
	return 0
}

type SkillNode struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SkillId     string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Label       string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Branch      string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	Keystone    bool                   `protobuf:"varint,5,opt,name=keystone,proto3" json:"keystone,omitempty"`
	// Canvas coordinates (1100×760 viewBox)
	X int32 `protobuf:"varint,6,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,7,opt,name=y,proto3" json:"y,omitempty"`
	// "locked" | "available" | "allocated"
	State string `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	// Effect this node grants when allocated
	Effect *SkillEffect `protobuf:"bytes,9,opt,name=effect,proto3" json:"effect,omitempty"`
	// Refund cost in gold (0 when not allocated)
	RefundGold    int32 `protobuf:"varint,10,opt,name=refund_gold,json=refundGold,proto3" json:"refund_gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillNode) Reset() {
	*x = SkillNode{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillNode) ProtoMessage() {}

func (x *SkillNode) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillNode.ProtoReflect.Descriptor instead.
func (*SkillNode) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{8}
}

func (x *SkillNode) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *SkillNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SkillNode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillNode) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *SkillNode) GetKeystone() bool {
	if x != nil {
		return x.Keystone
	}
	return false
}

func (x *SkillNode) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SkillNode) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SkillNode) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SkillNode) GetEffect() *SkillEffect {
	if x != nil {
		return x.Effect
	}
	return nil
}

func (x *SkillNode) GetRefundGold() int32 {
	if x != nil {
		return x.RefundGold
	}
	return 0
}

type SkillEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSkillId   string                 `protobuf:"bytes,1,opt,name=from_skill_id,json=fromSkillId,proto3" json:"from_skill_id,omitempty"`
	ToSkillId     string                 `protobuf:"bytes,2,opt,name=to_skill_id,json=toSkillId,proto3" json:"to_skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillEdge) Reset() {
	*x = SkillEdge{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillEdge) ProtoMessage() {}

func (x *SkillEdge) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillEdge.ProtoReflect.Descriptor instead.
func (*SkillEdge) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{9}
}

func (x *SkillEdge) GetFromSkillId() string {
	if x != nil {
		return x.FromSkillId
	}
	return ""
}

func (x *SkillEdge) GetToSkillId() string {
	if x != nil {
		return x.ToSkillId
	}
	return ""
}

type SkillEffect struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "xp_multiplier", "gold_multiplier", "arena_time_bonus_pct",
	//
	//	"streak_grace_hours", "hint_count", "free_ai_review_daily",
	//	"streak_floor", "shop_discount_pct"
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Numeric value; interpretation depends on type
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	// Human-readable label shown in the UI ("+ 10% training XP")
	Label         string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillEffect) Reset() {
	*x = SkillEffect{}
	mi := &file_game_skills_v1_skills_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillEffect) ProtoMessage() {}

func (x *SkillEffect) ProtoReflect() protoreflect.Message {
	mi := &file_game_skills_v1_skills_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillEffect.ProtoReflect.Descriptor instead.
func (*SkillEffect) Descriptor() ([]byte, []int) {
	return file_game_skills_v1_skills_proto_rawDescGZIP(), []int{10}
}

func (x *SkillEffect) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SkillEffect) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SkillEffect) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_game_skills_v1_skills_proto protoreflect.FileDescriptor

const file_game_skills_v1_skills_proto_rawDesc = "" +
	"\n" +
	"\x1bgame/skills/v1/skills.proto\x12\tskills.v1\x1a\x1cgoogle/api/annotations.proto\"\x15\n" +
	"\x13GetSkillTreeRequest\"\xe1\x01\n" +
	"\x14GetSkillTreeResponse\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.skills.v1.SkillNodeR\x05nodes\x12*\n" +
	"\x05edges\x18\x02 \x03(\v2\x14.skills.v1.SkillEdgeR\x05edges\x12)\n" +
	"\x10points_available\x18\x03 \x01(\x05R\x0fpointsAvailable\x12#\n" +
	"\rpoints_earned\x18\x04 \x01(\x05R\fpointsEarned\x12!\n" +
	"\fpoints_spent\x18\x05 \x01(\x05R\vpointsSpent\"\x17\n" +
	"\x15GetSkillPointsRequest\"d\n" +
	"\x16GetSkillPointsResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\x05R\tavailable\x12\x16\n" +
	"\x06earned\x18\x02 \x01(\x05R\x06earned\x12\x14\n" +
	"\x05spent\x18\x03 \x01(\x05R\x05spent\"1\n" +
	"\x14AllocateSkillRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\"\x81\x01\n" +
	"\x15AllocateSkillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12)\n" +
	"\x10points_remaining\x18\x03 \x01(\x05R\x0fpointsRemaining\"/\n" +
	"\x12RefundSkillRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\"\x9a\x01\n" +
	"\x13RefundSkillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tgold_cost\x18\x03 \x01(\x05R\bgoldCost\x12'\n" +
	"\x0fpoints_returned\x18\x04 \x01(\x05R\x0epointsReturned\"\x95\x02\n" +
	"\tSkillNode\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\x12\x1a\n" +
	"\bkeystone\x18\x05 \x01(\bR\bkeystone\x12\f\n" +
	"\x01x\x18\x06 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\a \x01(\x05R\x01y\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12.\n" +
	"\x06effect\x18\t \x01(\v2\x16.skills.v1.SkillEffectR\x06effect\x12\x1f\n" +
	"\vrefund_gold\x18\n" +
	" \x01(\x05R\n" +
	"refundGold\"O\n" +
	"\tSkillEdge\x12\"\n" +
	"\rfrom_skill_id\x18\x01 \x01(\tR\vfromSkillId\x12\x1e\n" +
	"\vto_skill_id\x18\x02 \x01(\tR\ttoSkillId\"M\n" +
	"\vSkillEffect\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label2\xf2\x03\n" +
	"\rSkillsService\x12l\n" +
	"\fGetSkillTree\x12\x1e.skills.v1.GetSkillTreeRequest\x1a\x1f.skills.v1.GetSkillTreeResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/skills/tree\x12t\n" +
	"\x0eGetSkillPoints\x12 .skills.v1.GetSkillPointsRequest\x1a!.skills.v1.GetSkillPointsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/skills/points\x12\x81\x01\n" +
	"\rAllocateSkill\x12\x1f.skills.v1.AllocateSkillRequest\x1a .skills.v1.AllocateSkillResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/skills/{skill_id}/allocate\x12y\n" +
	"\vRefundSkill\x12\x1d.skills.v1.RefundSkillRequest\x1a\x1e.skills.v1.RefundSkillResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/skills/{skill_id}/refundB\x1aZ\x18api/pkg/api/skills/v1;v1b\x06proto3"

var (
	file_game_skills_v1_skills_proto_rawDescOnce sync.Once
	file_game_skills_v1_skills_proto_rawDescData []byte
)

func file_game_skills_v1_skills_proto_rawDescGZIP() []byte {
	file_game_skills_v1_skills_proto_rawDescOnce.Do(func() {
		file_game_skills_v1_skills_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_skills_v1_skills_proto_rawDesc), len(file_game_skills_v1_skills_proto_rawDesc)))
	})
	return file_game_skills_v1_skills_proto_rawDescData
}

var file_game_skills_v1_skills_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_game_skills_v1_skills_proto_goTypes = []any{
	(*GetSkillTreeRequest)(nil),    // 0: skills.v1.GetSkillTreeRequest
	(*GetSkillTreeResponse)(nil),   // 1: skills.v1.GetSkillTreeResponse
	(*GetSkillPointsRequest)(nil),  // 2: skills.v1.GetSkillPointsRequest
	(*GetSkillPointsResponse)(nil), // 3: skills.v1.GetSkillPointsResponse
	(*AllocateSkillRequest)(nil),   // 4: skills.v1.AllocateSkillRequest
	(*AllocateSkillResponse)(nil),  // 5: skills.v1.AllocateSkillResponse
	(*RefundSkillRequest)(nil),     // 6: skills.v1.RefundSkillRequest
	(*RefundSkillResponse)(nil),    // 7: skills.v1.RefundSkillResponse
	(*SkillNode)(nil),              // 8: skills.v1.SkillNode
	(*SkillEdge)(nil),              // 9: skills.v1.SkillEdge
	(*SkillEffect)(nil),            // 10: skills.v1.SkillEffect
}
var file_game_skills_v1_skills_proto_depIdxs = []int32{
	8,  // 0: skills.v1.GetSkillTreeResponse.nodes:type_name -> skills.v1.SkillNode
	9,  // 1: skills.v1.GetSkillTreeResponse.edges:type_name -> skills.v1.SkillEdge
	10, // 2: skills.v1.SkillNode.effect:type_name -> skills.v1.SkillEffect
	0,  // 3: skills.v1.SkillsService.GetSkillTree:input_type -> skills.v1.GetSkillTreeRequest
	2,  // 4: skills.v1.SkillsService.GetSkillPoints:input_type -> skills.v1.GetSkillPointsRequest
	4,  // 5: skills.v1.SkillsService.AllocateSkill:input_type -> skills.v1.AllocateSkillRequest
	6,  // 6: skills.v1.SkillsService.RefundSkill:input_type -> skills.v1.RefundSkillRequest
	1,  // 7: skills.v1.SkillsService.GetSkillTree:output_type -> skills.v1.GetSkillTreeResponse
	3,  // 8: skills.v1.SkillsService.GetSkillPoints:output_type -> skills.v1.GetSkillPointsResponse
	5,  // 9: skills.v1.SkillsService.AllocateSkill:output_type -> skills.v1.AllocateSkillResponse
	7,  // 10: skills.v1.SkillsService.RefundSkill:output_type -> skills.v1.RefundSkillResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_game_skills_v1_skills_proto_init() }
func file_game_skills_v1_skills_proto_init() {
	if File_game_skills_v1_skills_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_skills_v1_skills_proto_rawDesc), len(file_game_skills_v1_skills_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_skills_v1_skills_proto_goTypes,
		DependencyIndexes: file_game_skills_v1_skills_proto_depIdxs,
		MessageInfos:      file_game_skills_v1_skills_proto_msgTypes,
	}.Build()
	File_game_skills_v1_skills_proto = out.File
	file_game_skills_v1_skills_proto_goTypes = nil
	file_game_skills_v1_skills_proto_depIdxs = nil
}
