// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: core/profile/v1/profile.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProfileServiceBindTelegram = "/profile.v1.ProfileService/BindTelegram"
const OperationProfileServiceCompleteRegistration = "/profile.v1.ProfileService/CompleteRegistration"
const OperationProfileServiceCreateTelegramAuthChallenge = "/profile.v1.ProfileService/CreateTelegramAuthChallenge"
const OperationProfileServiceGetProfile = "/profile.v1.ProfileService/GetProfile"
const OperationProfileServiceGetProfileByID = "/profile.v1.ProfileService/GetProfileByID"
const OperationProfileServiceGetProfileFeed = "/profile.v1.ProfileService/GetProfileFeed"
const OperationProfileServiceGetProfileProgress = "/profile.v1.ProfileService/GetProfileProgress"
const OperationProfileServiceGetReadiness = "/profile.v1.ProfileService/GetReadiness"
const OperationProfileServiceGetUserPreferences = "/profile.v1.ProfileService/GetUserPreferences"
const OperationProfileServiceGetWallet = "/profile.v1.ProfileService/GetWallet"
const OperationProfileServiceListCompletedTours = "/profile.v1.ProfileService/ListCompletedTours"
const OperationProfileServiceListProfileAchievements = "/profile.v1.ProfileService/ListProfileAchievements"
const OperationProfileServiceListProfileActivity = "/profile.v1.ProfileService/ListProfileActivity"
const OperationProfileServiceLogout = "/profile.v1.ProfileService/Logout"
const OperationProfileServiceMarkTourCompleted = "/profile.v1.ProfileService/MarkTourCompleted"
const OperationProfileServiceSetUserGoal = "/profile.v1.ProfileService/SetUserGoal"
const OperationProfileServiceStartYandexAuth = "/profile.v1.ProfileService/StartYandexAuth"
const OperationProfileServiceTelegramAuth = "/profile.v1.ProfileService/TelegramAuth"
const OperationProfileServiceUpdateLocation = "/profile.v1.ProfileService/UpdateLocation"
const OperationProfileServiceUpdateProfile = "/profile.v1.ProfileService/UpdateProfile"
const OperationProfileServiceUpdateUserPreferences = "/profile.v1.ProfileService/UpdateUserPreferences"
const OperationProfileServiceYandexAuth = "/profile.v1.ProfileService/YandexAuth"

type ProfileServiceHTTPServer interface {
	BindTelegram(context.Context, *BindTelegramRequest) (*ProfileStatusResponse, error)
	CompleteRegistration(context.Context, *CompleteRegistrationRequest) (*ProfileResponse, error)
	CreateTelegramAuthChallenge(context.Context, *CreateTelegramAuthChallengeRequest) (*CreateTelegramAuthChallengeResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error)
	GetProfileByID(context.Context, *GetProfileByIDRequest) (*ProfileResponse, error)
	GetProfileFeed(context.Context, *GetProfileFeedRequest) (*GetProfileFeedResponse, error)
	GetProfileProgress(context.Context, *GetProfileProgressRequest) (*ProfileProgressResponse, error)
	GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessResponse, error)
	// GetUserPreferences ADR-005 — User UI preferences (layout density, etc.). Separate from
	// notification settings (which live in notification.proto).
	GetUserPreferences(context.Context, *GetUserPreferencesRequest) (*UserPreferences, error)
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	// ListCompletedTours ADR-004 — Onboarding tours. The frontend triggers a guided tour the
	// first time a user lands on a page with no completed_at row; calling
	// MarkTourCompleted records the dismissal so it never re-triggers.
	ListCompletedTours(context.Context, *ListCompletedToursRequest) (*ListCompletedToursResponse, error)
	ListProfileAchievements(context.Context, *ListProfileAchievementsRequest) (*ListProfileAchievementsResponse, error)
	ListProfileActivity(context.Context, *ListProfileActivityRequest) (*ListProfileActivityResponse, error)
	Logout(context.Context, *LogoutRequest) (*ProfileStatusResponse, error)
	MarkTourCompleted(context.Context, *MarkTourCompletedRequest) (*ListCompletedToursResponse, error)
	SetUserGoal(context.Context, *SetUserGoalRequest) (*SetUserGoalResponse, error)
	StartYandexAuth(context.Context, *StartYandexAuthRequest) (*StartYandexAuthResponse, error)
	TelegramAuth(context.Context, *TelegramAuthRequest) (*ProfileResponse, error)
	UpdateLocation(context.Context, *UpdateLocationRequest) (*ProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*ProfileResponse, error)
	UpdateUserPreferences(context.Context, *UpdateUserPreferencesRequest) (*UserPreferences, error)
	YandexAuth(context.Context, *YandexAuthRequest) (*ProfileResponse, error)
}

func RegisterProfileServiceHTTPServer(s *http.Server, srv ProfileServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/profile/auth/telegram/challenge", _ProfileService_CreateTelegramAuthChallenge0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/auth/telegram", _ProfileService_TelegramAuth0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/auth/yandex/start", _ProfileService_StartYandexAuth0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/auth/yandex/callback", _ProfileService_YandexAuth0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/auth/complete-registration", _ProfileService_CompleteRegistration0_HTTP_Handler(srv))
	r.GET("/api/v1/profile", _ProfileService_GetProfile0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/{user_id}", _ProfileService_GetProfileByID0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/location", _ProfileService_UpdateLocation0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/update", _ProfileService_UpdateProfile0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/auth/logout", _ProfileService_Logout0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/bind-telegram", _ProfileService_BindTelegram0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/{user_id}/progress", _ProfileService_GetProfileProgress0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/goal", _ProfileService_SetUserGoal0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/{user_id}/readiness", _ProfileService_GetReadiness0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/{user_id}/feed", _ProfileService_GetProfileFeed0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/{user_id}/achievements", _ProfileService_ListProfileAchievements0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/{user_id}/activity", _ProfileService_ListProfileActivity0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/preferences", _ProfileService_GetUserPreferences0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/preferences", _ProfileService_UpdateUserPreferences0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/tours", _ProfileService_ListCompletedTours0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/tours", _ProfileService_MarkTourCompleted0_HTTP_Handler(srv))
	r.GET("/api/v1/wallet", _ProfileService_GetWallet0_HTTP_Handler(srv))
}

func _ProfileService_CreateTelegramAuthChallenge0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTelegramAuthChallengeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceCreateTelegramAuthChallenge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTelegramAuthChallenge(ctx, req.(*CreateTelegramAuthChallengeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTelegramAuthChallengeResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_TelegramAuth0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TelegramAuthRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceTelegramAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TelegramAuth(ctx, req.(*TelegramAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_StartYandexAuth0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartYandexAuthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceStartYandexAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartYandexAuth(ctx, req.(*StartYandexAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartYandexAuthResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_YandexAuth0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in YandexAuthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceYandexAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.YandexAuth(ctx, req.(*YandexAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_CompleteRegistration0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteRegistrationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceCompleteRegistration)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteRegistration(ctx, req.(*CompleteRegistrationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetProfileByID0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileByIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetProfileByID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfileByID(ctx, req.(*GetProfileByIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_UpdateLocation0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateLocationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceUpdateLocation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateLocation(ctx, req.(*UpdateLocationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_UpdateProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceUpdateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProfile(ctx, req.(*UpdateProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_Logout0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileStatusResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_BindTelegram0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindTelegramRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceBindTelegram)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindTelegram(ctx, req.(*BindTelegramRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileStatusResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetProfileProgress0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileProgressRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetProfileProgress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfileProgress(ctx, req.(*GetProfileProgressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileProgressResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_SetUserGoal0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetUserGoalRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceSetUserGoal)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetUserGoal(ctx, req.(*SetUserGoalRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetUserGoalResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetReadiness0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReadinessRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetReadiness)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReadiness(ctx, req.(*GetReadinessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReadinessResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetProfileFeed0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileFeedRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetProfileFeed)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfileFeed(ctx, req.(*GetProfileFeedRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProfileFeedResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_ListProfileAchievements0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProfileAchievementsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceListProfileAchievements)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProfileAchievements(ctx, req.(*ListProfileAchievementsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProfileAchievementsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_ListProfileActivity0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProfileActivityRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceListProfileActivity)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProfileActivity(ctx, req.(*ListProfileActivityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProfileActivityResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetUserPreferences0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserPreferencesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetUserPreferences)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserPreferences(ctx, req.(*GetUserPreferencesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserPreferences)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_UpdateUserPreferences0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserPreferencesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceUpdateUserPreferences)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserPreferences(ctx, req.(*UpdateUserPreferencesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserPreferences)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_ListCompletedTours0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCompletedToursRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceListCompletedTours)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCompletedTours(ctx, req.(*ListCompletedToursRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCompletedToursResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_MarkTourCompleted0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarkTourCompletedRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceMarkTourCompleted)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkTourCompleted(ctx, req.(*MarkTourCompletedRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCompletedToursResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetWallet0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWalletRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetWallet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWallet(ctx, req.(*GetWalletRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWalletResponse)
		return ctx.Result(200, reply)
	}
}

type ProfileServiceHTTPClient interface {
	BindTelegram(ctx context.Context, req *BindTelegramRequest, opts ...http.CallOption) (rsp *ProfileStatusResponse, err error)
	CompleteRegistration(ctx context.Context, req *CompleteRegistrationRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	CreateTelegramAuthChallenge(ctx context.Context, req *CreateTelegramAuthChallengeRequest, opts ...http.CallOption) (rsp *CreateTelegramAuthChallengeResponse, err error)
	GetProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	GetProfileByID(ctx context.Context, req *GetProfileByIDRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	GetProfileFeed(ctx context.Context, req *GetProfileFeedRequest, opts ...http.CallOption) (rsp *GetProfileFeedResponse, err error)
	GetProfileProgress(ctx context.Context, req *GetProfileProgressRequest, opts ...http.CallOption) (rsp *ProfileProgressResponse, err error)
	GetReadiness(ctx context.Context, req *GetReadinessRequest, opts ...http.CallOption) (rsp *GetReadinessResponse, err error)
	// GetUserPreferences ADR-005 — User UI preferences (layout density, etc.). Separate from
	// notification settings (which live in notification.proto).
	GetUserPreferences(ctx context.Context, req *GetUserPreferencesRequest, opts ...http.CallOption) (rsp *UserPreferences, err error)
	GetWallet(ctx context.Context, req *GetWalletRequest, opts ...http.CallOption) (rsp *GetWalletResponse, err error)
	// ListCompletedTours ADR-004 — Onboarding tours. The frontend triggers a guided tour the
	// first time a user lands on a page with no completed_at row; calling
	// MarkTourCompleted records the dismissal so it never re-triggers.
	ListCompletedTours(ctx context.Context, req *ListCompletedToursRequest, opts ...http.CallOption) (rsp *ListCompletedToursResponse, err error)
	ListProfileAchievements(ctx context.Context, req *ListProfileAchievementsRequest, opts ...http.CallOption) (rsp *ListProfileAchievementsResponse, err error)
	ListProfileActivity(ctx context.Context, req *ListProfileActivityRequest, opts ...http.CallOption) (rsp *ListProfileActivityResponse, err error)
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *ProfileStatusResponse, err error)
	MarkTourCompleted(ctx context.Context, req *MarkTourCompletedRequest, opts ...http.CallOption) (rsp *ListCompletedToursResponse, err error)
	SetUserGoal(ctx context.Context, req *SetUserGoalRequest, opts ...http.CallOption) (rsp *SetUserGoalResponse, err error)
	StartYandexAuth(ctx context.Context, req *StartYandexAuthRequest, opts ...http.CallOption) (rsp *StartYandexAuthResponse, err error)
	TelegramAuth(ctx context.Context, req *TelegramAuthRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	UpdateLocation(ctx context.Context, req *UpdateLocationRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	UpdateProfile(ctx context.Context, req *UpdateProfileRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	UpdateUserPreferences(ctx context.Context, req *UpdateUserPreferencesRequest, opts ...http.CallOption) (rsp *UserPreferences, err error)
	YandexAuth(ctx context.Context, req *YandexAuthRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
}

type ProfileServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProfileServiceHTTPClient(client *http.Client) ProfileServiceHTTPClient {
	return &ProfileServiceHTTPClientImpl{client}
}

func (c *ProfileServiceHTTPClientImpl) BindTelegram(ctx context.Context, in *BindTelegramRequest, opts ...http.CallOption) (*ProfileStatusResponse, error) {
	var out ProfileStatusResponse
	pattern := "/api/v1/profile/bind-telegram"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceBindTelegram))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) CompleteRegistration(ctx context.Context, in *CompleteRegistrationRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/auth/complete-registration"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceCompleteRegistration))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) CreateTelegramAuthChallenge(ctx context.Context, in *CreateTelegramAuthChallengeRequest, opts ...http.CallOption) (*CreateTelegramAuthChallengeResponse, error) {
	var out CreateTelegramAuthChallengeResponse
	pattern := "/api/v1/profile/auth/telegram/challenge"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceCreateTelegramAuthChallenge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceGetProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetProfileByID(ctx context.Context, in *GetProfileByIDRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/{user_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceGetProfileByID))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetProfileFeed(ctx context.Context, in *GetProfileFeedRequest, opts ...http.CallOption) (*GetProfileFeedResponse, error) {
	var out GetProfileFeedResponse
	pattern := "/api/v1/profile/{user_id}/feed"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceGetProfileFeed))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetProfileProgress(ctx context.Context, in *GetProfileProgressRequest, opts ...http.CallOption) (*ProfileProgressResponse, error) {
	var out ProfileProgressResponse
	pattern := "/api/v1/profile/{user_id}/progress"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceGetProfileProgress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...http.CallOption) (*GetReadinessResponse, error) {
	var out GetReadinessResponse
	pattern := "/api/v1/profile/{user_id}/readiness"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceGetReadiness))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserPreferences ADR-005 — User UI preferences (layout density, etc.). Separate from
// notification settings (which live in notification.proto).
func (c *ProfileServiceHTTPClientImpl) GetUserPreferences(ctx context.Context, in *GetUserPreferencesRequest, opts ...http.CallOption) (*UserPreferences, error) {
	var out UserPreferences
	pattern := "/api/v1/profile/preferences"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceGetUserPreferences))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...http.CallOption) (*GetWalletResponse, error) {
	var out GetWalletResponse
	pattern := "/api/v1/wallet"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceGetWallet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCompletedTours ADR-004 — Onboarding tours. The frontend triggers a guided tour the
// first time a user lands on a page with no completed_at row; calling
// MarkTourCompleted records the dismissal so it never re-triggers.
func (c *ProfileServiceHTTPClientImpl) ListCompletedTours(ctx context.Context, in *ListCompletedToursRequest, opts ...http.CallOption) (*ListCompletedToursResponse, error) {
	var out ListCompletedToursResponse
	pattern := "/api/v1/profile/tours"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceListCompletedTours))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) ListProfileAchievements(ctx context.Context, in *ListProfileAchievementsRequest, opts ...http.CallOption) (*ListProfileAchievementsResponse, error) {
	var out ListProfileAchievementsResponse
	pattern := "/api/v1/profile/{user_id}/achievements"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceListProfileAchievements))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) ListProfileActivity(ctx context.Context, in *ListProfileActivityRequest, opts ...http.CallOption) (*ListProfileActivityResponse, error) {
	var out ListProfileActivityResponse
	pattern := "/api/v1/profile/{user_id}/activity"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceListProfileActivity))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*ProfileStatusResponse, error) {
	var out ProfileStatusResponse
	pattern := "/api/v1/profile/auth/logout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceLogout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) MarkTourCompleted(ctx context.Context, in *MarkTourCompletedRequest, opts ...http.CallOption) (*ListCompletedToursResponse, error) {
	var out ListCompletedToursResponse
	pattern := "/api/v1/profile/tours"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceMarkTourCompleted))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) SetUserGoal(ctx context.Context, in *SetUserGoalRequest, opts ...http.CallOption) (*SetUserGoalResponse, error) {
	var out SetUserGoalResponse
	pattern := "/api/v1/profile/goal"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceSetUserGoal))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) StartYandexAuth(ctx context.Context, in *StartYandexAuthRequest, opts ...http.CallOption) (*StartYandexAuthResponse, error) {
	var out StartYandexAuthResponse
	pattern := "/api/v1/profile/auth/yandex/start"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceStartYandexAuth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) TelegramAuth(ctx context.Context, in *TelegramAuthRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/auth/telegram"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceTelegramAuth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/location"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceUpdateLocation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceUpdateProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) UpdateUserPreferences(ctx context.Context, in *UpdateUserPreferencesRequest, opts ...http.CallOption) (*UserPreferences, error) {
	var out UserPreferences
	pattern := "/api/v1/profile/preferences"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceUpdateUserPreferences))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) YandexAuth(ctx context.Context, in *YandexAuthRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/auth/yandex/callback"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceYandexAuth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
