// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: profile/v1/profile.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProfileServiceBindTelegram = "/profile.v1.ProfileService/BindTelegram"
const OperationProfileServiceCompletePhotoUpload = "/profile.v1.ProfileService/CompletePhotoUpload"
const OperationProfileServiceCompleteRegistration = "/profile.v1.ProfileService/CompleteRegistration"
const OperationProfileServiceConfirmTelegramAuth = "/profile.v1.ProfileService/ConfirmTelegramAuth"
const OperationProfileServiceCreateTelegramAuthChallenge = "/profile.v1.ProfileService/CreateTelegramAuthChallenge"
const OperationProfileServiceGetPhotoUploadURL = "/profile.v1.ProfileService/GetPhotoUploadURL"
const OperationProfileServiceGetProfile = "/profile.v1.ProfileService/GetProfile"
const OperationProfileServiceGetProfileByID = "/profile.v1.ProfileService/GetProfileByID"
const OperationProfileServiceLoginWithPassword = "/profile.v1.ProfileService/LoginWithPassword"
const OperationProfileServiceLogout = "/profile.v1.ProfileService/Logout"
const OperationProfileServiceRegisterWithPassword = "/profile.v1.ProfileService/RegisterWithPassword"
const OperationProfileServiceTelegramAuth = "/profile.v1.ProfileService/TelegramAuth"
const OperationProfileServiceUpdateLocation = "/profile.v1.ProfileService/UpdateLocation"
const OperationProfileServiceUpdateProfile = "/profile.v1.ProfileService/UpdateProfile"

type ProfileServiceHTTPServer interface {
	BindTelegram(context.Context, *BindTelegramRequest) (*BindTelegramResponse, error)
	CompletePhotoUpload(context.Context, *CompletePhotoUploadRequest) (*CompletePhotoUploadResponse, error)
	CompleteRegistration(context.Context, *CompleteRegistrationRequest) (*ProfileResponse, error)
	ConfirmTelegramAuth(context.Context, *ConfirmTelegramAuthRequest) (*ConfirmTelegramAuthResponse, error)
	CreateTelegramAuthChallenge(context.Context, *CreateTelegramAuthChallengeRequest) (*CreateTelegramAuthChallengeResponse, error)
	GetPhotoUploadURL(context.Context, *GetPhotoUploadURLRequest) (*GetPhotoUploadURLResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error)
	GetProfileByID(context.Context, *GetProfileByIDRequest) (*ProfileResponse, error)
	LoginWithPassword(context.Context, *LoginWithPasswordRequest) (*LoginWithPasswordResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	RegisterWithPassword(context.Context, *RegisterWithPasswordRequest) (*RegisterWithPasswordResponse, error)
	TelegramAuth(context.Context, *TelegramAuthRequest) (*ProfileResponse, error)
	UpdateLocation(context.Context, *UpdateLocationRequest) (*ProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*ProfileResponse, error)
}

func RegisterProfileServiceHTTPServer(s *http.Server, srv ProfileServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/profile/auth/telegram/challenge", _ProfileService_CreateTelegramAuthChallenge0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/auth/telegram/confirm", _ProfileService_ConfirmTelegramAuth0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/auth/telegram", _ProfileService_TelegramAuth0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/auth/complete-registration", _ProfileService_CompleteRegistration0_HTTP_Handler(srv))
	r.GET("/api/v1/profile", _ProfileService_GetProfile0_HTTP_Handler(srv))
	r.GET("/api/v1/profile/{user_id}", _ProfileService_GetProfileByID0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/location", _ProfileService_UpdateLocation0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/update", _ProfileService_UpdateProfile0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/auth/logout", _ProfileService_Logout0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/bind-telegram", _ProfileService_BindTelegram0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/photo/upload-url", _ProfileService_GetPhotoUploadURL0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/photo/complete", _ProfileService_CompletePhotoUpload0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/auth/login-password", _ProfileService_LoginWithPassword0_HTTP_Handler(srv))
	r.POST("/api/v1/profile/auth/register-password", _ProfileService_RegisterWithPassword0_HTTP_Handler(srv))
}

func _ProfileService_CreateTelegramAuthChallenge0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTelegramAuthChallengeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceCreateTelegramAuthChallenge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTelegramAuthChallenge(ctx, req.(*CreateTelegramAuthChallengeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTelegramAuthChallengeResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_ConfirmTelegramAuth0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfirmTelegramAuthRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceConfirmTelegramAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfirmTelegramAuth(ctx, req.(*ConfirmTelegramAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfirmTelegramAuthResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_TelegramAuth0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TelegramAuthRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceTelegramAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TelegramAuth(ctx, req.(*TelegramAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_CompleteRegistration0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteRegistrationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceCompleteRegistration)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteRegistration(ctx, req.(*CompleteRegistrationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetProfileByID0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileByIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetProfileByID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfileByID(ctx, req.(*GetProfileByIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_UpdateLocation0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateLocationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceUpdateLocation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateLocation(ctx, req.(*UpdateLocationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_UpdateProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceUpdateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProfile(ctx, req.(*UpdateProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_Logout0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_BindTelegram0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindTelegramRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceBindTelegram)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindTelegram(ctx, req.(*BindTelegramRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BindTelegramResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetPhotoUploadURL0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPhotoUploadURLRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetPhotoUploadURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPhotoUploadURL(ctx, req.(*GetPhotoUploadURLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPhotoUploadURLResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_CompletePhotoUpload0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompletePhotoUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceCompletePhotoUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompletePhotoUpload(ctx, req.(*CompletePhotoUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompletePhotoUploadResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_LoginWithPassword0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginWithPasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceLoginWithPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginWithPassword(ctx, req.(*LoginWithPasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginWithPasswordResponse)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_RegisterWithPassword0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterWithPasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceRegisterWithPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterWithPassword(ctx, req.(*RegisterWithPasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterWithPasswordResponse)
		return ctx.Result(200, reply)
	}
}

type ProfileServiceHTTPClient interface {
	BindTelegram(ctx context.Context, req *BindTelegramRequest, opts ...http.CallOption) (rsp *BindTelegramResponse, err error)
	CompletePhotoUpload(ctx context.Context, req *CompletePhotoUploadRequest, opts ...http.CallOption) (rsp *CompletePhotoUploadResponse, err error)
	CompleteRegistration(ctx context.Context, req *CompleteRegistrationRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	ConfirmTelegramAuth(ctx context.Context, req *ConfirmTelegramAuthRequest, opts ...http.CallOption) (rsp *ConfirmTelegramAuthResponse, err error)
	CreateTelegramAuthChallenge(ctx context.Context, req *CreateTelegramAuthChallengeRequest, opts ...http.CallOption) (rsp *CreateTelegramAuthChallengeResponse, err error)
	GetPhotoUploadURL(ctx context.Context, req *GetPhotoUploadURLRequest, opts ...http.CallOption) (rsp *GetPhotoUploadURLResponse, err error)
	GetProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	GetProfileByID(ctx context.Context, req *GetProfileByIDRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	LoginWithPassword(ctx context.Context, req *LoginWithPasswordRequest, opts ...http.CallOption) (rsp *LoginWithPasswordResponse, err error)
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *LogoutResponse, err error)
	RegisterWithPassword(ctx context.Context, req *RegisterWithPasswordRequest, opts ...http.CallOption) (rsp *RegisterWithPasswordResponse, err error)
	TelegramAuth(ctx context.Context, req *TelegramAuthRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	UpdateLocation(ctx context.Context, req *UpdateLocationRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
	UpdateProfile(ctx context.Context, req *UpdateProfileRequest, opts ...http.CallOption) (rsp *ProfileResponse, err error)
}

type ProfileServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProfileServiceHTTPClient(client *http.Client) ProfileServiceHTTPClient {
	return &ProfileServiceHTTPClientImpl{client}
}

func (c *ProfileServiceHTTPClientImpl) BindTelegram(ctx context.Context, in *BindTelegramRequest, opts ...http.CallOption) (*BindTelegramResponse, error) {
	var out BindTelegramResponse
	pattern := "/api/v1/profile/bind-telegram"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceBindTelegram))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) CompletePhotoUpload(ctx context.Context, in *CompletePhotoUploadRequest, opts ...http.CallOption) (*CompletePhotoUploadResponse, error) {
	var out CompletePhotoUploadResponse
	pattern := "/api/v1/profile/photo/complete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceCompletePhotoUpload))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) CompleteRegistration(ctx context.Context, in *CompleteRegistrationRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/auth/complete-registration"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceCompleteRegistration))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) ConfirmTelegramAuth(ctx context.Context, in *ConfirmTelegramAuthRequest, opts ...http.CallOption) (*ConfirmTelegramAuthResponse, error) {
	var out ConfirmTelegramAuthResponse
	pattern := "/api/v1/profile/auth/telegram/confirm"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceConfirmTelegramAuth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) CreateTelegramAuthChallenge(ctx context.Context, in *CreateTelegramAuthChallengeRequest, opts ...http.CallOption) (*CreateTelegramAuthChallengeResponse, error) {
	var out CreateTelegramAuthChallengeResponse
	pattern := "/api/v1/profile/auth/telegram/challenge"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceCreateTelegramAuthChallenge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetPhotoUploadURL(ctx context.Context, in *GetPhotoUploadURLRequest, opts ...http.CallOption) (*GetPhotoUploadURLResponse, error) {
	var out GetPhotoUploadURLResponse
	pattern := "/api/v1/profile/photo/upload-url"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceGetPhotoUploadURL))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceGetProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetProfileByID(ctx context.Context, in *GetProfileByIDRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/{user_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceGetProfileByID))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) LoginWithPassword(ctx context.Context, in *LoginWithPasswordRequest, opts ...http.CallOption) (*LoginWithPasswordResponse, error) {
	var out LoginWithPasswordResponse
	pattern := "/api/v1/profile/auth/login-password"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceLoginWithPassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*LogoutResponse, error) {
	var out LogoutResponse
	pattern := "/api/v1/profile/auth/logout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceLogout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) RegisterWithPassword(ctx context.Context, in *RegisterWithPasswordRequest, opts ...http.CallOption) (*RegisterWithPasswordResponse, error) {
	var out RegisterWithPasswordResponse
	pattern := "/api/v1/profile/auth/register-password"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceRegisterWithPassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) TelegramAuth(ctx context.Context, in *TelegramAuthRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/auth/telegram"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceTelegramAuth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/location"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceUpdateLocation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...http.CallOption) (*ProfileResponse, error) {
	var out ProfileResponse
	pattern := "/api/v1/profile/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceUpdateProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
