// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: event/v1/event.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventListFilter int32

const (
	EventListFilter_EVENT_LIST_FILTER_UNSPECIFIED EventListFilter = 0
	EventListFilter_EVENT_LIST_FILTER_UPCOMING    EventListFilter = 1
	EventListFilter_EVENT_LIST_FILTER_PAST        EventListFilter = 2
)

// Enum value maps for EventListFilter.
var (
	EventListFilter_name = map[int32]string{
		0: "EVENT_LIST_FILTER_UNSPECIFIED",
		1: "EVENT_LIST_FILTER_UPCOMING",
		2: "EVENT_LIST_FILTER_PAST",
	}
	EventListFilter_value = map[string]int32{
		"EVENT_LIST_FILTER_UNSPECIFIED": 0,
		"EVENT_LIST_FILTER_UPCOMING":    1,
		"EVENT_LIST_FILTER_PAST":        2,
	}
)

func (x EventListFilter) Enum() *EventListFilter {
	p := new(EventListFilter)
	*p = x
	return p
}

func (x EventListFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventListFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_event_v1_event_proto_enumTypes[0].Descriptor()
}

func (EventListFilter) Type() protoreflect.EnumType {
	return &file_event_v1_event_proto_enumTypes[0]
}

func (x EventListFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventListFilter.Descriptor instead.
func (EventListFilter) EnumDescriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{0}
}

type ParticipantStatus int32

const (
	ParticipantStatus_PARTICIPANT_STATUS_UNSPECIFIED ParticipantStatus = 0
	ParticipantStatus_PARTICIPANT_STATUS_PENDING     ParticipantStatus = 1
	ParticipantStatus_PARTICIPANT_STATUS_CONFIRMED   ParticipantStatus = 2
	ParticipantStatus_PARTICIPANT_STATUS_DECLINED    ParticipantStatus = 3
)

// Enum value maps for ParticipantStatus.
var (
	ParticipantStatus_name = map[int32]string{
		0: "PARTICIPANT_STATUS_UNSPECIFIED",
		1: "PARTICIPANT_STATUS_PENDING",
		2: "PARTICIPANT_STATUS_CONFIRMED",
		3: "PARTICIPANT_STATUS_DECLINED",
	}
	ParticipantStatus_value = map[string]int32{
		"PARTICIPANT_STATUS_UNSPECIFIED": 0,
		"PARTICIPANT_STATUS_PENDING":     1,
		"PARTICIPANT_STATUS_CONFIRMED":   2,
		"PARTICIPANT_STATUS_DECLINED":    3,
	}
)

func (x ParticipantStatus) Enum() *ParticipantStatus {
	p := new(ParticipantStatus)
	*p = x
	return p
}

func (x ParticipantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_event_v1_event_proto_enumTypes[1].Descriptor()
}

func (ParticipantStatus) Type() protoreflect.EnumType {
	return &file_event_v1_event_proto_enumTypes[1]
}

func (x ParticipantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipantStatus.Descriptor instead.
func (ParticipantStatus) EnumDescriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{1}
}

// DeleteEventScope controls which occurrences of a recurring event to delete.
type DeleteEventScope int32

const (
	DeleteEventScope_DELETE_EVENT_SCOPE_UNSPECIFIED DeleteEventScope = 0
	DeleteEventScope_DELETE_EVENT_SCOPE_SINGLE      DeleteEventScope = 1 // only this occurrence
	DeleteEventScope_DELETE_EVENT_SCOPE_FUTURE      DeleteEventScope = 2 // this and all future occurrences
	DeleteEventScope_DELETE_EVENT_SCOPE_ALL         DeleteEventScope = 3 // all occurrences in the series
)

// Enum value maps for DeleteEventScope.
var (
	DeleteEventScope_name = map[int32]string{
		0: "DELETE_EVENT_SCOPE_UNSPECIFIED",
		1: "DELETE_EVENT_SCOPE_SINGLE",
		2: "DELETE_EVENT_SCOPE_FUTURE",
		3: "DELETE_EVENT_SCOPE_ALL",
	}
	DeleteEventScope_value = map[string]int32{
		"DELETE_EVENT_SCOPE_UNSPECIFIED": 0,
		"DELETE_EVENT_SCOPE_SINGLE":      1,
		"DELETE_EVENT_SCOPE_FUTURE":      2,
		"DELETE_EVENT_SCOPE_ALL":         3,
	}
)

func (x DeleteEventScope) Enum() *DeleteEventScope {
	p := new(DeleteEventScope)
	*p = x
	return p
}

func (x DeleteEventScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteEventScope) Descriptor() protoreflect.EnumDescriptor {
	return file_event_v1_event_proto_enumTypes[2].Descriptor()
}

func (DeleteEventScope) Type() protoreflect.EnumType {
	return &file_event_v1_event_proto_enumTypes[2]
}

func (x DeleteEventScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteEventScope.Descriptor instead.
func (DeleteEventScope) EnumDescriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{2}
}

// EventRepeat defines the recurrence rule for a created event.
type EventRepeat int32

const (
	EventRepeat_EVENT_REPEAT_UNSPECIFIED EventRepeat = 0
	EventRepeat_EVENT_REPEAT_NONE        EventRepeat = 1
	EventRepeat_EVENT_REPEAT_DAILY       EventRepeat = 2
	EventRepeat_EVENT_REPEAT_WEEKLY      EventRepeat = 3
	EventRepeat_EVENT_REPEAT_MONTHLY     EventRepeat = 4
)

// Enum value maps for EventRepeat.
var (
	EventRepeat_name = map[int32]string{
		0: "EVENT_REPEAT_UNSPECIFIED",
		1: "EVENT_REPEAT_NONE",
		2: "EVENT_REPEAT_DAILY",
		3: "EVENT_REPEAT_WEEKLY",
		4: "EVENT_REPEAT_MONTHLY",
	}
	EventRepeat_value = map[string]int32{
		"EVENT_REPEAT_UNSPECIFIED": 0,
		"EVENT_REPEAT_NONE":        1,
		"EVENT_REPEAT_DAILY":       2,
		"EVENT_REPEAT_WEEKLY":      3,
		"EVENT_REPEAT_MONTHLY":     4,
	}
)

func (x EventRepeat) Enum() *EventRepeat {
	p := new(EventRepeat)
	*p = x
	return p
}

func (x EventRepeat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventRepeat) Descriptor() protoreflect.EnumDescriptor {
	return file_event_v1_event_proto_enumTypes[3].Descriptor()
}

func (EventRepeat) Type() protoreflect.EnumType {
	return &file_event_v1_event_proto_enumTypes[3]
}

func (x EventRepeat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventRepeat.Descriptor instead.
func (EventRepeat) EnumDescriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{3}
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        EventListFilter        `protobuf:"varint,3,opt,name=status,proto3,enum=event.v1.EventListFilter" json:"status,omitempty"`
	CreatorId     string                 `protobuf:"bytes,4,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListEventsRequest) GetStatus() EventListFilter {
	if x != nil {
		return x.Status
	}
	return EventListFilter_EVENT_LIST_FILTER_UNSPECIFIED
}

func (x *ListEventsRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type CreateEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	PlaceLabel     string                 `protobuf:"bytes,2,opt,name=place_label,json=placeLabel,proto3" json:"place_label,omitempty"`
	Region         string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Country        string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	City           string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Latitude       float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ScheduledAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	InvitedUserIds []string               `protobuf:"bytes,9,rep,name=invited_user_ids,json=invitedUserIds,proto3" json:"invited_user_ids,omitempty"`
	Description    string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	MeetingLink    string                 `protobuf:"bytes,11,opt,name=meeting_link,json=meetingLink,proto3" json:"meeting_link,omitempty"`
	Repeat         EventRepeat            `protobuf:"varint,12,opt,name=repeat,proto3,enum=event.v1.EventRepeat" json:"repeat,omitempty"` // was: string
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetPlaceLabel() string {
	if x != nil {
		return x.PlaceLabel
	}
	return ""
}

func (x *CreateEventRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateEventRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateEventRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateEventRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateEventRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateEventRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *CreateEventRequest) GetInvitedUserIds() []string {
	if x != nil {
		return x.InvitedUserIds
	}
	return nil
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetMeetingLink() string {
	if x != nil {
		return x.MeetingLink
	}
	return ""
}

func (x *CreateEventRequest) GetRepeat() EventRepeat {
	if x != nil {
		return x.Repeat
	}
	return EventRepeat_EVENT_REPEAT_UNSPECIFIED
}

type JoinEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinEventRequest) Reset() {
	*x = JoinEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEventRequest) ProtoMessage() {}

func (x *JoinEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEventRequest.ProtoReflect.Descriptor instead.
func (*JoinEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *JoinEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type LeaveEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveEventRequest) Reset() {
	*x = LeaveEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveEventRequest) ProtoMessage() {}

func (x *LeaveEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveEventRequest.ProtoReflect.Descriptor instead.
func (*LeaveEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type UpdateEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PlaceLabel     string                 `protobuf:"bytes,3,opt,name=place_label,json=placeLabel,proto3" json:"place_label,omitempty"`
	Region         string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Country        string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	City           string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Latitude       float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ScheduledAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	InvitedUserIds []string               `protobuf:"bytes,10,rep,name=invited_user_ids,json=invitedUserIds,proto3" json:"invited_user_ids,omitempty"`
	Description    string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	MeetingLink    string                 `protobuf:"bytes,12,opt,name=meeting_link,json=meetingLink,proto3" json:"meeting_link,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetPlaceLabel() string {
	if x != nil {
		return x.PlaceLabel
	}
	return ""
}

func (x *UpdateEventRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UpdateEventRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateEventRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateEventRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateEventRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateEventRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *UpdateEventRequest) GetInvitedUserIds() []string {
	if x != nil {
		return x.InvitedUserIds
	}
	return nil
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetMeetingLink() string {
	if x != nil {
		return x.MeetingLink
	}
	return ""
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DeleteScope   DeleteEventScope       `protobuf:"varint,2,opt,name=delete_scope,json=deleteScope,proto3,enum=event.v1.DeleteEventScope" json:"delete_scope,omitempty"` // was: string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeleteEventRequest) GetDeleteScope() DeleteEventScope {
	if x != nil {
		return x.DeleteScope
	}
	return DeleteEventScope_DELETE_EVENT_SCOPE_UNSPECIFIED
}

// EventStatusResponse replaces the separate LeaveEventResponse and DeleteEventResponse.
type EventStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStatusResponse) Reset() {
	*x = EventStatusResponse{}
	mi := &file_event_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatusResponse) ProtoMessage() {}

func (x *EventStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatusResponse.ProtoReflect.Descriptor instead.
func (*EventStatusResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *EventStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_event_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{7}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEventsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListEventsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListEventsResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_event_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{8}
}

func (x *EventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type Event struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PlaceLabel       string                 `protobuf:"bytes,3,opt,name=place_label,json=placeLabel,proto3" json:"place_label,omitempty"`
	Region           string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Country          string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	City             string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Latitude         float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ScheduledAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatorId        string                 `protobuf:"bytes,11,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorName      string                 `protobuf:"bytes,12,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	IsCreator        bool                   `protobuf:"varint,13,opt,name=is_creator,json=isCreator,proto3" json:"is_creator,omitempty"`
	IsJoined         bool                   `protobuf:"varint,14,opt,name=is_joined,json=isJoined,proto3" json:"is_joined,omitempty"`
	ParticipantCount uint32                 `protobuf:"varint,15,opt,name=participant_count,json=participantCount,proto3" json:"participant_count,omitempty"`
	Participants     []*EventParticipant    `protobuf:"bytes,16,rep,name=participants,proto3" json:"participants,omitempty"`
	Description      string                 `protobuf:"bytes,17,opt,name=description,proto3" json:"description,omitempty"`
	MeetingLink      string                 `protobuf:"bytes,18,opt,name=meeting_link,json=meetingLink,proto3" json:"meeting_link,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetPlaceLabel() string {
	if x != nil {
		return x.PlaceLabel
	}
	return ""
}

func (x *Event) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Event) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Event) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Event) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Event) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Event) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Event) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *Event) GetIsCreator() bool {
	if x != nil {
		return x.IsCreator
	}
	return false
}

func (x *Event) GetIsJoined() bool {
	if x != nil {
		return x.IsJoined
	}
	return false
}

func (x *Event) GetParticipantCount() uint32 {
	if x != nil {
		return x.ParticipantCount
	}
	return 0
}

func (x *Event) GetParticipants() []*EventParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetMeetingLink() string {
	if x != nil {
		return x.MeetingLink
	}
	return ""
}

type EventParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // was: title (misleading name)
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Status        ParticipantStatus      `protobuf:"varint,7,opt,name=status,proto3,enum=event.v1.ParticipantStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventParticipant) Reset() {
	*x = EventParticipant{}
	mi := &file_event_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventParticipant) ProtoMessage() {}

func (x *EventParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventParticipant.ProtoReflect.Descriptor instead.
func (*EventParticipant) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{10}
}

func (x *EventParticipant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventParticipant) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *EventParticipant) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *EventParticipant) GetStatus() ParticipantStatus {
	if x != nil {
		return x.Status
	}
	return ParticipantStatus_PARTICIPANT_STATUS_UNSPECIFIED
}

var File_event_v1_event_proto protoreflect.FileDescriptor

const file_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x14event/v1/event.proto\x12\bevent.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\x11ListEventsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.event.v1.EventListFilterR\x06status\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x04 \x01(\tR\tcreatorId\"\xa8\x03\n" +
	"\x12CreateEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1f\n" +
	"\vplace_label\x18\x02 \x01(\tR\n" +
	"placeLabel\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12=\n" +
	"\fscheduled_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12(\n" +
	"\x10invited_user_ids\x18\t \x03(\tR\x0einvitedUserIds\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12!\n" +
	"\fmeeting_link\x18\v \x01(\tR\vmeetingLink\x12-\n" +
	"\x06repeat\x18\f \x01(\x0e2\x15.event.v1.EventRepeatR\x06repeat\"-\n" +
	"\x10JoinEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\".\n" +
	"\x11LeaveEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\x94\x03\n" +
	"\x12UpdateEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vplace_label\x18\x03 \x01(\tR\n" +
	"placeLabel\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x12=\n" +
	"\fscheduled_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12(\n" +
	"\x10invited_user_ids\x18\n" +
	" \x03(\tR\x0einvitedUserIds\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12!\n" +
	"\fmeeting_link\x18\f \x01(\tR\vmeetingLink\"n\n" +
	"\x12DeleteEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12=\n" +
	"\fdelete_scope\x18\x02 \x01(\x0e2\x1a.event.v1.DeleteEventScopeR\vdeleteScope\"-\n" +
	"\x13EventStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xb0\x01\n" +
	"\x12ListEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.event.v1.EventR\x06events\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\"\n" +
	"\rhas_next_page\x18\x05 \x01(\bR\vhasNextPage\"6\n" +
	"\rEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.event.v1.EventR\x05event\"\xf8\x04\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vplace_label\x18\x03 \x01(\tR\n" +
	"placeLabel\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x12=\n" +
	"\fscheduled_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"creator_id\x18\v \x01(\tR\tcreatorId\x12!\n" +
	"\fcreator_name\x18\f \x01(\tR\vcreatorName\x12\x1d\n" +
	"\n" +
	"is_creator\x18\r \x01(\bR\tisCreator\x12\x1b\n" +
	"\tis_joined\x18\x0e \x01(\bR\bisJoined\x12+\n" +
	"\x11participant_count\x18\x0f \x01(\rR\x10participantCount\x12>\n" +
	"\fparticipants\x18\x10 \x03(\v2\x1a.event.v1.EventParticipantR\fparticipants\x12 \n" +
	"\vdescription\x18\x11 \x01(\tR\vdescription\x12!\n" +
	"\fmeeting_link\x18\x12 \x01(\tR\vmeetingLink\"\xa2\x01\n" +
	"\x10EventParticipant\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.event.v1.ParticipantStatusR\x06status*p\n" +
	"\x0fEventListFilter\x12!\n" +
	"\x1dEVENT_LIST_FILTER_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aEVENT_LIST_FILTER_UPCOMING\x10\x01\x12\x1a\n" +
	"\x16EVENT_LIST_FILTER_PAST\x10\x02*\x9a\x01\n" +
	"\x11ParticipantStatus\x12\"\n" +
	"\x1ePARTICIPANT_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPARTICIPANT_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cPARTICIPANT_STATUS_CONFIRMED\x10\x02\x12\x1f\n" +
	"\x1bPARTICIPANT_STATUS_DECLINED\x10\x03*\x90\x01\n" +
	"\x10DeleteEventScope\x12\"\n" +
	"\x1eDELETE_EVENT_SCOPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DELETE_EVENT_SCOPE_SINGLE\x10\x01\x12\x1d\n" +
	"\x19DELETE_EVENT_SCOPE_FUTURE\x10\x02\x12\x1a\n" +
	"\x16DELETE_EVENT_SCOPE_ALL\x10\x03*\x8d\x01\n" +
	"\vEventRepeat\x12\x1c\n" +
	"\x18EVENT_REPEAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_REPEAT_NONE\x10\x01\x12\x16\n" +
	"\x12EVENT_REPEAT_DAILY\x10\x02\x12\x17\n" +
	"\x13EVENT_REPEAT_WEEKLY\x10\x03\x12\x18\n" +
	"\x14EVENT_REPEAT_MONTHLY\x10\x042\x8e\x05\n" +
	"\fEventService\x12_\n" +
	"\n" +
	"ListEvents\x12\x1b.event.v1.ListEventsRequest\x1a\x1c.event.v1.ListEventsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/events\x12_\n" +
	"\vCreateEvent\x12\x1c.event.v1.CreateEventRequest\x1a\x17.event.v1.EventResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/events\x12k\n" +
	"\tJoinEvent\x12\x1a.event.v1.JoinEventRequest\x1a\x17.event.v1.EventResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/events/{event_id}/join\x12t\n" +
	"\n" +
	"LeaveEvent\x12\x1b.event.v1.LeaveEventRequest\x1a\x1d.event.v1.EventStatusResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/events/{event_id}/leave\x12j\n" +
	"\vUpdateEvent\x12\x1c.event.v1.UpdateEventRequest\x1a\x17.event.v1.EventResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/v1/events/{event_id}\x12m\n" +
	"\vDeleteEvent\x12\x1c.event.v1.DeleteEventRequest\x1a\x1d.event.v1.EventStatusResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/v1/events/{event_id}B\x19Z\x17api/pkg/api/event/v1;v1b\x06proto3"

var (
	file_event_v1_event_proto_rawDescOnce sync.Once
	file_event_v1_event_proto_rawDescData []byte
)

func file_event_v1_event_proto_rawDescGZIP() []byte {
	file_event_v1_event_proto_rawDescOnce.Do(func() {
		file_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_v1_event_proto_rawDesc), len(file_event_v1_event_proto_rawDesc)))
	})
	return file_event_v1_event_proto_rawDescData
}

var file_event_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_event_v1_event_proto_goTypes = []any{
	(EventListFilter)(0),          // 0: event.v1.EventListFilter
	(ParticipantStatus)(0),        // 1: event.v1.ParticipantStatus
	(DeleteEventScope)(0),         // 2: event.v1.DeleteEventScope
	(EventRepeat)(0),              // 3: event.v1.EventRepeat
	(*ListEventsRequest)(nil),     // 4: event.v1.ListEventsRequest
	(*CreateEventRequest)(nil),    // 5: event.v1.CreateEventRequest
	(*JoinEventRequest)(nil),      // 6: event.v1.JoinEventRequest
	(*LeaveEventRequest)(nil),     // 7: event.v1.LeaveEventRequest
	(*UpdateEventRequest)(nil),    // 8: event.v1.UpdateEventRequest
	(*DeleteEventRequest)(nil),    // 9: event.v1.DeleteEventRequest
	(*EventStatusResponse)(nil),   // 10: event.v1.EventStatusResponse
	(*ListEventsResponse)(nil),    // 11: event.v1.ListEventsResponse
	(*EventResponse)(nil),         // 12: event.v1.EventResponse
	(*Event)(nil),                 // 13: event.v1.Event
	(*EventParticipant)(nil),      // 14: event.v1.EventParticipant
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_event_v1_event_proto_depIdxs = []int32{
	0,  // 0: event.v1.ListEventsRequest.status:type_name -> event.v1.EventListFilter
	15, // 1: event.v1.CreateEventRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	3,  // 2: event.v1.CreateEventRequest.repeat:type_name -> event.v1.EventRepeat
	15, // 3: event.v1.UpdateEventRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	2,  // 4: event.v1.DeleteEventRequest.delete_scope:type_name -> event.v1.DeleteEventScope
	13, // 5: event.v1.ListEventsResponse.events:type_name -> event.v1.Event
	13, // 6: event.v1.EventResponse.event:type_name -> event.v1.Event
	15, // 7: event.v1.Event.scheduled_at:type_name -> google.protobuf.Timestamp
	15, // 8: event.v1.Event.created_at:type_name -> google.protobuf.Timestamp
	14, // 9: event.v1.Event.participants:type_name -> event.v1.EventParticipant
	1,  // 10: event.v1.EventParticipant.status:type_name -> event.v1.ParticipantStatus
	4,  // 11: event.v1.EventService.ListEvents:input_type -> event.v1.ListEventsRequest
	5,  // 12: event.v1.EventService.CreateEvent:input_type -> event.v1.CreateEventRequest
	6,  // 13: event.v1.EventService.JoinEvent:input_type -> event.v1.JoinEventRequest
	7,  // 14: event.v1.EventService.LeaveEvent:input_type -> event.v1.LeaveEventRequest
	8,  // 15: event.v1.EventService.UpdateEvent:input_type -> event.v1.UpdateEventRequest
	9,  // 16: event.v1.EventService.DeleteEvent:input_type -> event.v1.DeleteEventRequest
	11, // 17: event.v1.EventService.ListEvents:output_type -> event.v1.ListEventsResponse
	12, // 18: event.v1.EventService.CreateEvent:output_type -> event.v1.EventResponse
	12, // 19: event.v1.EventService.JoinEvent:output_type -> event.v1.EventResponse
	10, // 20: event.v1.EventService.LeaveEvent:output_type -> event.v1.EventStatusResponse
	12, // 21: event.v1.EventService.UpdateEvent:output_type -> event.v1.EventResponse
	10, // 22: event.v1.EventService.DeleteEvent:output_type -> event.v1.EventStatusResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_event_v1_event_proto_init() }
func file_event_v1_event_proto_init() {
	if File_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_v1_event_proto_rawDesc), len(file_event_v1_event_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_v1_event_proto_goTypes,
		DependencyIndexes: file_event_v1_event_proto_depIdxs,
		EnumInfos:         file_event_v1_event_proto_enumTypes,
		MessageInfos:      file_event_v1_event_proto_msgTypes,
	}.Build()
	File_event_v1_event_proto = out.File
	file_event_v1_event_proto_goTypes = nil
	file_event_v1_event_proto_depIdxs = nil
}
