// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: notification/v1/notification.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ScheduleAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=schedule_at,json=scheduleAt,proto3" json:"schedule_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SendRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendRequest) GetScheduleAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduleAt
	}
	return nil
}

type SendResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type SendBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchRequest) Reset() {
	*x = SendBatchRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchRequest) ProtoMessage() {}

func (x *SendBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchRequest.ProtoReflect.Descriptor instead.
func (*SendBatchRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendBatchRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *SendBatchRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SendBatchRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendBatchRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendBatchRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enqueued      int32                  `protobuf:"varint,1,opt,name=enqueued,proto3" json:"enqueued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchResponse) Reset() {
	*x = SendBatchResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchResponse) ProtoMessage() {}

func (x *SendBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchResponse.ProtoReflect.Descriptor instead.
func (*SendBatchResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendBatchResponse) GetEnqueued() int32 {
	if x != nil {
		return x.Enqueued
	}
	return 0
}

type RegisterChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TelegramChatId int64                  `protobuf:"varint,2,opt,name=telegram_chat_id,json=telegramChatId,proto3" json:"telegram_chat_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterChatRequest) Reset() {
	*x = RegisterChatRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChatRequest) ProtoMessage() {}

func (x *RegisterChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChatRequest.ProtoReflect.Descriptor instead.
func (*RegisterChatRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterChatRequest) GetTelegramChatId() int64 {
	if x != nil {
		return x.TelegramChatId
	}
	return 0
}

type RegisterChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChatResponse) Reset() {
	*x = RegisterChatResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChatResponse) ProtoMessage() {}

func (x *RegisterChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChatResponse.ProtoReflect.Descriptor instead.
func (*RegisterChatResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

type LinkTelegramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TelegramId    int64                  `protobuf:"varint,2,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkTelegramRequest) Reset() {
	*x = LinkTelegramRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkTelegramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkTelegramRequest) ProtoMessage() {}

func (x *LinkTelegramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkTelegramRequest.ProtoReflect.Descriptor instead.
func (*LinkTelegramRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *LinkTelegramRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LinkTelegramRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

type LinkTelegramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkTelegramResponse) Reset() {
	*x = LinkTelegramResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkTelegramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkTelegramResponse) ProtoMessage() {}

func (x *LinkTelegramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkTelegramResponse.ProtoReflect.Descriptor instead.
func (*LinkTelegramResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

type UpdateSettingsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DuelsEnabled          *bool                  `protobuf:"varint,2,opt,name=duels_enabled,json=duelsEnabled,proto3,oneof" json:"duels_enabled,omitempty"`
	ProgressEnabled       *bool                  `protobuf:"varint,3,opt,name=progress_enabled,json=progressEnabled,proto3,oneof" json:"progress_enabled,omitempty"`
	CirclesEnabled        *bool                  `protobuf:"varint,4,opt,name=circles_enabled,json=circlesEnabled,proto3,oneof" json:"circles_enabled,omitempty"`
	DailyChallengeEnabled *bool                  `protobuf:"varint,5,opt,name=daily_challenge_enabled,json=dailyChallengeEnabled,proto3,oneof" json:"daily_challenge_enabled,omitempty"`
	QuietHoursStart       *int32                 `protobuf:"varint,6,opt,name=quiet_hours_start,json=quietHoursStart,proto3,oneof" json:"quiet_hours_start,omitempty"`
	QuietHoursEnd         *int32                 `protobuf:"varint,7,opt,name=quiet_hours_end,json=quietHoursEnd,proto3,oneof" json:"quiet_hours_end,omitempty"`
	Timezone              *string                `protobuf:"bytes,8,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateSettingsRequest) GetDuelsEnabled() bool {
	if x != nil && x.DuelsEnabled != nil {
		return *x.DuelsEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetProgressEnabled() bool {
	if x != nil && x.ProgressEnabled != nil {
		return *x.ProgressEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetCirclesEnabled() bool {
	if x != nil && x.CirclesEnabled != nil {
		return *x.CirclesEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetDailyChallengeEnabled() bool {
	if x != nil && x.DailyChallengeEnabled != nil {
		return *x.DailyChallengeEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetQuietHoursStart() int32 {
	if x != nil && x.QuietHoursStart != nil {
		return *x.QuietHoursStart
	}
	return 0
}

func (x *UpdateSettingsRequest) GetQuietHoursEnd() int32 {
	if x != nil && x.QuietHoursEnd != nil {
		return *x.QuietHoursEnd
	}
	return 0
}

func (x *UpdateSettingsRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

type UpdateSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsResponse) Reset() {
	*x = UpdateSettingsResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsResponse) ProtoMessage() {}

func (x *UpdateSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSettingsResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{9}
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{10}
}

func (x *GetSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSettingsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DuelsEnabled          bool                   `protobuf:"varint,1,opt,name=duels_enabled,json=duelsEnabled,proto3" json:"duels_enabled,omitempty"`
	ProgressEnabled       bool                   `protobuf:"varint,2,opt,name=progress_enabled,json=progressEnabled,proto3" json:"progress_enabled,omitempty"`
	CirclesEnabled        bool                   `protobuf:"varint,3,opt,name=circles_enabled,json=circlesEnabled,proto3" json:"circles_enabled,omitempty"`
	DailyChallengeEnabled bool                   `protobuf:"varint,4,opt,name=daily_challenge_enabled,json=dailyChallengeEnabled,proto3" json:"daily_challenge_enabled,omitempty"`
	QuietHoursStart       int32                  `protobuf:"varint,5,opt,name=quiet_hours_start,json=quietHoursStart,proto3" json:"quiet_hours_start,omitempty"`
	QuietHoursEnd         int32                  `protobuf:"varint,6,opt,name=quiet_hours_end,json=quietHoursEnd,proto3" json:"quiet_hours_end,omitempty"`
	Timezone              string                 `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	TelegramChatId        int64                  `protobuf:"varint,8,opt,name=telegram_chat_id,json=telegramChatId,proto3" json:"telegram_chat_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{11}
}

func (x *GetSettingsResponse) GetDuelsEnabled() bool {
	if x != nil {
		return x.DuelsEnabled
	}
	return false
}

func (x *GetSettingsResponse) GetProgressEnabled() bool {
	if x != nil {
		return x.ProgressEnabled
	}
	return false
}

func (x *GetSettingsResponse) GetCirclesEnabled() bool {
	if x != nil {
		return x.CirclesEnabled
	}
	return false
}

func (x *GetSettingsResponse) GetDailyChallengeEnabled() bool {
	if x != nil {
		return x.DailyChallengeEnabled
	}
	return false
}

func (x *GetSettingsResponse) GetQuietHoursStart() int32 {
	if x != nil {
		return x.QuietHoursStart
	}
	return 0
}

func (x *GetSettingsResponse) GetQuietHoursEnd() int32 {
	if x != nil {
		return x.QuietHoursEnd
	}
	return 0
}

func (x *GetSettingsResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *GetSettingsResponse) GetTelegramChatId() int64 {
	if x != nil {
		return x.TelegramChatId
	}
	return 0
}

type UpdateCircleSettingsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CircleId        string                 `protobuf:"bytes,2,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
	EventsEnabled   *bool                  `protobuf:"varint,3,opt,name=events_enabled,json=eventsEnabled,proto3,oneof" json:"events_enabled,omitempty"`
	ActivityEnabled *bool                  `protobuf:"varint,4,opt,name=activity_enabled,json=activityEnabled,proto3,oneof" json:"activity_enabled,omitempty"`
	DigestEnabled   *bool                  `protobuf:"varint,5,opt,name=digest_enabled,json=digestEnabled,proto3,oneof" json:"digest_enabled,omitempty"`
	Muted           *bool                  `protobuf:"varint,6,opt,name=muted,proto3,oneof" json:"muted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCircleSettingsRequest) Reset() {
	*x = UpdateCircleSettingsRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCircleSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCircleSettingsRequest) ProtoMessage() {}

func (x *UpdateCircleSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCircleSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateCircleSettingsRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCircleSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCircleSettingsRequest) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

func (x *UpdateCircleSettingsRequest) GetEventsEnabled() bool {
	if x != nil && x.EventsEnabled != nil {
		return *x.EventsEnabled
	}
	return false
}

func (x *UpdateCircleSettingsRequest) GetActivityEnabled() bool {
	if x != nil && x.ActivityEnabled != nil {
		return *x.ActivityEnabled
	}
	return false
}

func (x *UpdateCircleSettingsRequest) GetDigestEnabled() bool {
	if x != nil && x.DigestEnabled != nil {
		return *x.DigestEnabled
	}
	return false
}

func (x *UpdateCircleSettingsRequest) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

type UpdateCircleSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCircleSettingsResponse) Reset() {
	*x = UpdateCircleSettingsResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCircleSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCircleSettingsResponse) ProtoMessage() {}

func (x *UpdateCircleSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCircleSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateCircleSettingsResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{13}
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x0fnotification.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\vSendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12;\n" +
	"\vschedule_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"scheduleAt\"7\n" +
	"\fSendResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"\x9e\x01\n" +
	"\x10SendBatchRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\"/\n" +
	"\x11SendBatchResponse\x12\x1a\n" +
	"\benqueued\x18\x01 \x01(\x05R\benqueued\"X\n" +
	"\x13RegisterChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10telegram_chat_id\x18\x02 \x01(\x03R\x0etelegramChatId\"\x16\n" +
	"\x14RegisterChatResponse\"O\n" +
	"\x13LinkTelegramRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtelegram_id\x18\x02 \x01(\x03R\n" +
	"telegramId\"\x16\n" +
	"\x14LinkTelegramResponse\"\x82\x04\n" +
	"\x15UpdateSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\rduels_enabled\x18\x02 \x01(\bH\x00R\fduelsEnabled\x88\x01\x01\x12.\n" +
	"\x10progress_enabled\x18\x03 \x01(\bH\x01R\x0fprogressEnabled\x88\x01\x01\x12,\n" +
	"\x0fcircles_enabled\x18\x04 \x01(\bH\x02R\x0ecirclesEnabled\x88\x01\x01\x12;\n" +
	"\x17daily_challenge_enabled\x18\x05 \x01(\bH\x03R\x15dailyChallengeEnabled\x88\x01\x01\x12/\n" +
	"\x11quiet_hours_start\x18\x06 \x01(\x05H\x04R\x0fquietHoursStart\x88\x01\x01\x12+\n" +
	"\x0fquiet_hours_end\x18\a \x01(\x05H\x05R\rquietHoursEnd\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\b \x01(\tH\x06R\btimezone\x88\x01\x01B\x10\n" +
	"\x0e_duels_enabledB\x13\n" +
	"\x11_progress_enabledB\x12\n" +
	"\x10_circles_enabledB\x1a\n" +
	"\x18_daily_challenge_enabledB\x14\n" +
	"\x12_quiet_hours_startB\x12\n" +
	"\x10_quiet_hours_endB\v\n" +
	"\t_timezone\"\x18\n" +
	"\x16UpdateSettingsResponse\"-\n" +
	"\x12GetSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xe0\x02\n" +
	"\x13GetSettingsResponse\x12#\n" +
	"\rduels_enabled\x18\x01 \x01(\bR\fduelsEnabled\x12)\n" +
	"\x10progress_enabled\x18\x02 \x01(\bR\x0fprogressEnabled\x12'\n" +
	"\x0fcircles_enabled\x18\x03 \x01(\bR\x0ecirclesEnabled\x126\n" +
	"\x17daily_challenge_enabled\x18\x04 \x01(\bR\x15dailyChallengeEnabled\x12*\n" +
	"\x11quiet_hours_start\x18\x05 \x01(\x05R\x0fquietHoursStart\x12&\n" +
	"\x0fquiet_hours_end\x18\x06 \x01(\x05R\rquietHoursEnd\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\x12(\n" +
	"\x10telegram_chat_id\x18\b \x01(\x03R\x0etelegramChatId\"\xbb\x02\n" +
	"\x1bUpdateCircleSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcircle_id\x18\x02 \x01(\tR\bcircleId\x12*\n" +
	"\x0eevents_enabled\x18\x03 \x01(\bH\x00R\reventsEnabled\x88\x01\x01\x12.\n" +
	"\x10activity_enabled\x18\x04 \x01(\bH\x01R\x0factivityEnabled\x88\x01\x01\x12*\n" +
	"\x0edigest_enabled\x18\x05 \x01(\bH\x02R\rdigestEnabled\x88\x01\x01\x12\x19\n" +
	"\x05muted\x18\x06 \x01(\bH\x03R\x05muted\x88\x01\x01B\x11\n" +
	"\x0f_events_enabledB\x13\n" +
	"\x11_activity_enabledB\x11\n" +
	"\x0f_digest_enabledB\b\n" +
	"\x06_muted\"\x1e\n" +
	"\x1cUpdateCircleSettingsResponse2\x9a\x05\n" +
	"\x13NotificationService\x12C\n" +
	"\x04Send\x12\x1c.notification.v1.SendRequest\x1a\x1d.notification.v1.SendResponse\x12R\n" +
	"\tSendBatch\x12!.notification.v1.SendBatchRequest\x1a\".notification.v1.SendBatchResponse\x12[\n" +
	"\fRegisterChat\x12$.notification.v1.RegisterChatRequest\x1a%.notification.v1.RegisterChatResponse\x12[\n" +
	"\fLinkTelegram\x12$.notification.v1.LinkTelegramRequest\x1a%.notification.v1.LinkTelegramResponse\x12a\n" +
	"\x0eUpdateSettings\x12&.notification.v1.UpdateSettingsRequest\x1a'.notification.v1.UpdateSettingsResponse\x12X\n" +
	"\vGetSettings\x12#.notification.v1.GetSettingsRequest\x1a$.notification.v1.GetSettingsResponse\x12s\n" +
	"\x14UpdateCircleSettings\x12,.notification.v1.UpdateCircleSettingsRequest\x1a-.notification.v1.UpdateCircleSettingsResponseB Z\x1eapi/pkg/api/notification/v1;v1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_notification_v1_notification_proto_goTypes = []any{
	(*SendRequest)(nil),                  // 0: notification.v1.SendRequest
	(*SendResponse)(nil),                 // 1: notification.v1.SendResponse
	(*SendBatchRequest)(nil),             // 2: notification.v1.SendBatchRequest
	(*SendBatchResponse)(nil),            // 3: notification.v1.SendBatchResponse
	(*RegisterChatRequest)(nil),          // 4: notification.v1.RegisterChatRequest
	(*RegisterChatResponse)(nil),         // 5: notification.v1.RegisterChatResponse
	(*LinkTelegramRequest)(nil),          // 6: notification.v1.LinkTelegramRequest
	(*LinkTelegramResponse)(nil),         // 7: notification.v1.LinkTelegramResponse
	(*UpdateSettingsRequest)(nil),        // 8: notification.v1.UpdateSettingsRequest
	(*UpdateSettingsResponse)(nil),       // 9: notification.v1.UpdateSettingsResponse
	(*GetSettingsRequest)(nil),           // 10: notification.v1.GetSettingsRequest
	(*GetSettingsResponse)(nil),          // 11: notification.v1.GetSettingsResponse
	(*UpdateCircleSettingsRequest)(nil),  // 12: notification.v1.UpdateCircleSettingsRequest
	(*UpdateCircleSettingsResponse)(nil), // 13: notification.v1.UpdateCircleSettingsResponse
	(*structpb.Struct)(nil),              // 14: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	14, // 0: notification.v1.SendRequest.payload:type_name -> google.protobuf.Struct
	15, // 1: notification.v1.SendRequest.schedule_at:type_name -> google.protobuf.Timestamp
	14, // 2: notification.v1.SendBatchRequest.payload:type_name -> google.protobuf.Struct
	0,  // 3: notification.v1.NotificationService.Send:input_type -> notification.v1.SendRequest
	2,  // 4: notification.v1.NotificationService.SendBatch:input_type -> notification.v1.SendBatchRequest
	4,  // 5: notification.v1.NotificationService.RegisterChat:input_type -> notification.v1.RegisterChatRequest
	6,  // 6: notification.v1.NotificationService.LinkTelegram:input_type -> notification.v1.LinkTelegramRequest
	8,  // 7: notification.v1.NotificationService.UpdateSettings:input_type -> notification.v1.UpdateSettingsRequest
	10, // 8: notification.v1.NotificationService.GetSettings:input_type -> notification.v1.GetSettingsRequest
	12, // 9: notification.v1.NotificationService.UpdateCircleSettings:input_type -> notification.v1.UpdateCircleSettingsRequest
	1,  // 10: notification.v1.NotificationService.Send:output_type -> notification.v1.SendResponse
	3,  // 11: notification.v1.NotificationService.SendBatch:output_type -> notification.v1.SendBatchResponse
	5,  // 12: notification.v1.NotificationService.RegisterChat:output_type -> notification.v1.RegisterChatResponse
	7,  // 13: notification.v1.NotificationService.LinkTelegram:output_type -> notification.v1.LinkTelegramResponse
	9,  // 14: notification.v1.NotificationService.UpdateSettings:output_type -> notification.v1.UpdateSettingsResponse
	11, // 15: notification.v1.NotificationService.GetSettings:output_type -> notification.v1.GetSettingsResponse
	13, // 16: notification.v1.NotificationService.UpdateCircleSettings:output_type -> notification.v1.UpdateCircleSettingsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	file_notification_v1_notification_proto_msgTypes[8].OneofWrappers = []any{}
	file_notification_v1_notification_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
