// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "api/internal/model"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CommunityMap provides a mock function with given fields: _a0, _a1
func (_m *Service) CommunityMap(_a0 context.Context, _a1 string) (*model.CommunityMapResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CommunityMap")
	}

	var r0 *model.CommunityMapResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.CommunityMapResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.CommunityMapResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CommunityMapResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CommunityMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommunityMap'
type Service_CommunityMap_Call struct {
	*mock.Call
}

// CommunityMap is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *Service_Expecter) CommunityMap(_a0 interface{}, _a1 interface{}) *Service_CommunityMap_Call {
	return &Service_CommunityMap_Call{Call: _e.mock.On("CommunityMap", _a0, _a1)}
}

func (_c *Service_CommunityMap_Call) Run(run func(_a0 context.Context, _a1 string)) *Service_CommunityMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_CommunityMap_Call) Return(_a0 *model.CommunityMapResponse, _a1 error) *Service_CommunityMap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CommunityMap_Call) RunAndReturn(run func(context.Context, string) (*model.CommunityMapResponse, error)) *Service_CommunityMap_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: _a0, _a1
func (_m *Service) Resolve(_a0 context.Context, _a1 string) (*model.GeoResolveResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 *model.GeoResolveResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.GeoResolveResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.GeoResolveResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GeoResolveResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type Service_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *Service_Expecter) Resolve(_a0 interface{}, _a1 interface{}) *Service_Resolve_Call {
	return &Service_Resolve_Call{Call: _e.mock.On("Resolve", _a0, _a1)}
}

func (_c *Service_Resolve_Call) Run(run func(_a0 context.Context, _a1 string)) *Service_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_Resolve_Call) Return(_a0 *model.GeoResolveResponse, _a1 error) *Service_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Resolve_Call) RunAndReturn(run func(context.Context, string) (*model.GeoResolveResponse, error)) *Service_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
