// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: game/shop/v1/shop.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShopServiceEquipCosmetic = "/shop.v1.ShopService/EquipCosmetic"
const OperationShopServiceGetInventory = "/shop.v1.ShopService/GetInventory"
const OperationShopServiceGetItem = "/shop.v1.ShopService/GetItem"
const OperationShopServiceListCategories = "/shop.v1.ShopService/ListCategories"
const OperationShopServiceListItems = "/shop.v1.ShopService/ListItems"
const OperationShopServicePurchase = "/shop.v1.ShopService/Purchase"

type ShopServiceHTTPServer interface {
	// EquipCosmetic EquipCosmetic marks an owned item as equipped. If another item in the
	// same slot is already equipped it's atomically unequipped. Pass
	// unequip=true to clear the slot without equipping anything new (item_id
	// still required so we know which slot to target).
	EquipCosmetic(context.Context, *EquipCosmeticRequest) (*EquipCosmeticResponse, error)
	// GetInventory GetInventory returns items the authenticated user owns.
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	// GetItem GetItem returns a single item's full detail (art, lore, price).
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	// ListCategories ListCategories returns the tabs shown on the tavern page along with the
	// item count per tab.
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	// ListItems ListItems returns catalog entries filtered by category and/or rarity.
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	// Purchase Purchase buys an item with the user's gold/gems. Idempotent on a
	// per-item basis (re-purchasing an owned item returns AlreadyOwned).
	Purchase(context.Context, *PurchaseRequest) (*PurchaseResponse, error)
}

func RegisterShopServiceHTTPServer(s *http.Server, srv ShopServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/shop/categories", _ShopService_ListCategories0_HTTP_Handler(srv))
	r.GET("/api/v1/shop/items", _ShopService_ListItems0_HTTP_Handler(srv))
	r.GET("/api/v1/shop/items/{item_id}", _ShopService_GetItem0_HTTP_Handler(srv))
	r.GET("/api/v1/shop/inventory", _ShopService_GetInventory0_HTTP_Handler(srv))
	r.POST("/api/v1/shop/purchase", _ShopService_Purchase0_HTTP_Handler(srv))
	r.POST("/api/v1/shop/equip", _ShopService_EquipCosmetic0_HTTP_Handler(srv))
}

func _ShopService_ListCategories0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCategoriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceListCategories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCategories(ctx, req.(*ListCategoriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCategoriesResponse)
		return ctx.Result(200, reply)
	}
}

func _ShopService_ListItems0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListItemsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceListItems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListItems(ctx, req.(*ListItemsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListItemsResponse)
		return ctx.Result(200, reply)
	}
}

func _ShopService_GetItem0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetItemRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceGetItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetItem(ctx, req.(*GetItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetItemResponse)
		return ctx.Result(200, reply)
	}
}

func _ShopService_GetInventory0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInventoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceGetInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInventory(ctx, req.(*GetInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetInventoryResponse)
		return ctx.Result(200, reply)
	}
}

func _ShopService_Purchase0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PurchaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServicePurchase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Purchase(ctx, req.(*PurchaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PurchaseResponse)
		return ctx.Result(200, reply)
	}
}

func _ShopService_EquipCosmetic0_HTTP_Handler(srv ShopServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EquipCosmeticRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceEquipCosmetic)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EquipCosmetic(ctx, req.(*EquipCosmeticRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EquipCosmeticResponse)
		return ctx.Result(200, reply)
	}
}

type ShopServiceHTTPClient interface {
	// EquipCosmetic EquipCosmetic marks an owned item as equipped. If another item in the
	// same slot is already equipped it's atomically unequipped. Pass
	// unequip=true to clear the slot without equipping anything new (item_id
	// still required so we know which slot to target).
	EquipCosmetic(ctx context.Context, req *EquipCosmeticRequest, opts ...http.CallOption) (rsp *EquipCosmeticResponse, err error)
	// GetInventory GetInventory returns items the authenticated user owns.
	GetInventory(ctx context.Context, req *GetInventoryRequest, opts ...http.CallOption) (rsp *GetInventoryResponse, err error)
	// GetItem GetItem returns a single item's full detail (art, lore, price).
	GetItem(ctx context.Context, req *GetItemRequest, opts ...http.CallOption) (rsp *GetItemResponse, err error)
	// ListCategories ListCategories returns the tabs shown on the tavern page along with the
	// item count per tab.
	ListCategories(ctx context.Context, req *ListCategoriesRequest, opts ...http.CallOption) (rsp *ListCategoriesResponse, err error)
	// ListItems ListItems returns catalog entries filtered by category and/or rarity.
	ListItems(ctx context.Context, req *ListItemsRequest, opts ...http.CallOption) (rsp *ListItemsResponse, err error)
	// Purchase Purchase buys an item with the user's gold/gems. Idempotent on a
	// per-item basis (re-purchasing an owned item returns AlreadyOwned).
	Purchase(ctx context.Context, req *PurchaseRequest, opts ...http.CallOption) (rsp *PurchaseResponse, err error)
}

type ShopServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewShopServiceHTTPClient(client *http.Client) ShopServiceHTTPClient {
	return &ShopServiceHTTPClientImpl{client}
}

// EquipCosmetic EquipCosmetic marks an owned item as equipped. If another item in the
// same slot is already equipped it's atomically unequipped. Pass
// unequip=true to clear the slot without equipping anything new (item_id
// still required so we know which slot to target).
func (c *ShopServiceHTTPClientImpl) EquipCosmetic(ctx context.Context, in *EquipCosmeticRequest, opts ...http.CallOption) (*EquipCosmeticResponse, error) {
	var out EquipCosmeticResponse
	pattern := "/api/v1/shop/equip"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServiceEquipCosmetic))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetInventory GetInventory returns items the authenticated user owns.
func (c *ShopServiceHTTPClientImpl) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...http.CallOption) (*GetInventoryResponse, error) {
	var out GetInventoryResponse
	pattern := "/api/v1/shop/inventory"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceGetInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetItem GetItem returns a single item's full detail (art, lore, price).
func (c *ShopServiceHTTPClientImpl) GetItem(ctx context.Context, in *GetItemRequest, opts ...http.CallOption) (*GetItemResponse, error) {
	var out GetItemResponse
	pattern := "/api/v1/shop/items/{item_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceGetItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCategories ListCategories returns the tabs shown on the tavern page along with the
// item count per tab.
func (c *ShopServiceHTTPClientImpl) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...http.CallOption) (*ListCategoriesResponse, error) {
	var out ListCategoriesResponse
	pattern := "/api/v1/shop/categories"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceListCategories))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListItems ListItems returns catalog entries filtered by category and/or rarity.
func (c *ShopServiceHTTPClientImpl) ListItems(ctx context.Context, in *ListItemsRequest, opts ...http.CallOption) (*ListItemsResponse, error) {
	var out ListItemsResponse
	pattern := "/api/v1/shop/items"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceListItems))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Purchase Purchase buys an item with the user's gold/gems. Idempotent on a
// per-item basis (re-purchasing an owned item returns AlreadyOwned).
func (c *ShopServiceHTTPClientImpl) Purchase(ctx context.Context, in *PurchaseRequest, opts ...http.CallOption) (*PurchaseResponse, error) {
	var out PurchaseResponse
	pattern := "/api/v1/shop/purchase"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServicePurchase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
