// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	v1 "api/pkg/api/skills/v1"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AddEarnedPoints provides a mock function with given fields: ctx, userID, delta
func (_m *Service) AddEarnedPoints(ctx context.Context, userID uuid.UUID, delta int32) error {
	ret := _m.Called(ctx, userID, delta)

	if len(ret) == 0 {
		panic("no return value specified for AddEarnedPoints")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32) error); ok {
		r0 = rf(ctx, userID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_AddEarnedPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEarnedPoints'
type Service_AddEarnedPoints_Call struct {
	*mock.Call
}

// AddEarnedPoints is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - delta int32
func (_e *Service_Expecter) AddEarnedPoints(ctx interface{}, userID interface{}, delta interface{}) *Service_AddEarnedPoints_Call {
	return &Service_AddEarnedPoints_Call{Call: _e.mock.On("AddEarnedPoints", ctx, userID, delta)}
}

func (_c *Service_AddEarnedPoints_Call) Run(run func(ctx context.Context, userID uuid.UUID, delta int32)) *Service_AddEarnedPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int32))
	})
	return _c
}

func (_c *Service_AddEarnedPoints_Call) Return(_a0 error) *Service_AddEarnedPoints_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_AddEarnedPoints_Call) RunAndReturn(run func(context.Context, uuid.UUID, int32) error) *Service_AddEarnedPoints_Call {
	_c.Call.Return(run)
	return _c
}

// AllocateSkill provides a mock function with given fields: ctx, userID, skillID
func (_m *Service) AllocateSkill(ctx context.Context, userID uuid.UUID, skillID string) (*v1.AllocateSkillResponse, error) {
	ret := _m.Called(ctx, userID, skillID)

	if len(ret) == 0 {
		panic("no return value specified for AllocateSkill")
	}

	var r0 *v1.AllocateSkillResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*v1.AllocateSkillResponse, error)); ok {
		return rf(ctx, userID, skillID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *v1.AllocateSkillResponse); ok {
		r0 = rf(ctx, userID, skillID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.AllocateSkillResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, skillID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_AllocateSkill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllocateSkill'
type Service_AllocateSkill_Call struct {
	*mock.Call
}

// AllocateSkill is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - skillID string
func (_e *Service_Expecter) AllocateSkill(ctx interface{}, userID interface{}, skillID interface{}) *Service_AllocateSkill_Call {
	return &Service_AllocateSkill_Call{Call: _e.mock.On("AllocateSkill", ctx, userID, skillID)}
}

func (_c *Service_AllocateSkill_Call) Run(run func(ctx context.Context, userID uuid.UUID, skillID string)) *Service_AllocateSkill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *Service_AllocateSkill_Call) Return(_a0 *v1.AllocateSkillResponse, _a1 error) *Service_AllocateSkill_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_AllocateSkill_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*v1.AllocateSkillResponse, error)) *Service_AllocateSkill_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkillPoints provides a mock function with given fields: ctx, userID
func (_m *Service) GetSkillPoints(ctx context.Context, userID uuid.UUID) (*v1.GetSkillPointsResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSkillPoints")
	}

	var r0 *v1.GetSkillPointsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*v1.GetSkillPointsResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *v1.GetSkillPointsResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.GetSkillPointsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetSkillPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkillPoints'
type Service_GetSkillPoints_Call struct {
	*mock.Call
}

// GetSkillPoints is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Service_Expecter) GetSkillPoints(ctx interface{}, userID interface{}) *Service_GetSkillPoints_Call {
	return &Service_GetSkillPoints_Call{Call: _e.mock.On("GetSkillPoints", ctx, userID)}
}

func (_c *Service_GetSkillPoints_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Service_GetSkillPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetSkillPoints_Call) Return(_a0 *v1.GetSkillPointsResponse, _a1 error) *Service_GetSkillPoints_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetSkillPoints_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*v1.GetSkillPointsResponse, error)) *Service_GetSkillPoints_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkillTree provides a mock function with given fields: ctx, userID
func (_m *Service) GetSkillTree(ctx context.Context, userID uuid.UUID) (*v1.GetSkillTreeResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSkillTree")
	}

	var r0 *v1.GetSkillTreeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*v1.GetSkillTreeResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *v1.GetSkillTreeResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.GetSkillTreeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetSkillTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkillTree'
type Service_GetSkillTree_Call struct {
	*mock.Call
}

// GetSkillTree is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Service_Expecter) GetSkillTree(ctx interface{}, userID interface{}) *Service_GetSkillTree_Call {
	return &Service_GetSkillTree_Call{Call: _e.mock.On("GetSkillTree", ctx, userID)}
}

func (_c *Service_GetSkillTree_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Service_GetSkillTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetSkillTree_Call) Return(_a0 *v1.GetSkillTreeResponse, _a1 error) *Service_GetSkillTree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetSkillTree_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*v1.GetSkillTreeResponse, error)) *Service_GetSkillTree_Call {
	_c.Call.Return(run)
	return _c
}

// RefundSkill provides a mock function with given fields: ctx, userID, skillID
func (_m *Service) RefundSkill(ctx context.Context, userID uuid.UUID, skillID string) (*v1.RefundSkillResponse, error) {
	ret := _m.Called(ctx, userID, skillID)

	if len(ret) == 0 {
		panic("no return value specified for RefundSkill")
	}

	var r0 *v1.RefundSkillResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*v1.RefundSkillResponse, error)); ok {
		return rf(ctx, userID, skillID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *v1.RefundSkillResponse); ok {
		r0 = rf(ctx, userID, skillID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.RefundSkillResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, skillID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_RefundSkill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefundSkill'
type Service_RefundSkill_Call struct {
	*mock.Call
}

// RefundSkill is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - skillID string
func (_e *Service_Expecter) RefundSkill(ctx interface{}, userID interface{}, skillID interface{}) *Service_RefundSkill_Call {
	return &Service_RefundSkill_Call{Call: _e.mock.On("RefundSkill", ctx, userID, skillID)}
}

func (_c *Service_RefundSkill_Call) Run(run func(ctx context.Context, userID uuid.UUID, skillID string)) *Service_RefundSkill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *Service_RefundSkill_Call) Return(_a0 *v1.RefundSkillResponse, _a1 error) *Service_RefundSkill_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_RefundSkill_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*v1.RefundSkillResponse, error)) *Service_RefundSkill_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
