// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: game/friend_challenge/v1/friend_challenge.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FriendChallengeService_ListIncoming_FullMethodName   = "/friend_challenge.v1.FriendChallengeService/ListIncoming"
	FriendChallengeService_ListSent_FullMethodName       = "/friend_challenge.v1.FriendChallengeService/ListSent"
	FriendChallengeService_ListHistory_FullMethodName    = "/friend_challenge.v1.FriendChallengeService/ListHistory"
	FriendChallengeService_SendChallenge_FullMethodName  = "/friend_challenge.v1.FriendChallengeService/SendChallenge"
	FriendChallengeService_SubmitSolution_FullMethodName = "/friend_challenge.v1.FriendChallengeService/SubmitSolution"
	FriendChallengeService_Decline_FullMethodName        = "/friend_challenge.v1.FriendChallengeService/Decline"
)

// FriendChallengeServiceClient is the client API for FriendChallengeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FriendChallengeService handles asynchronous 1v1 task duels between friends.
// Unlike live arena matches, both players solve the same task on their own
// schedule within a 48-hour window; the faster-and-more-correct submission
// wins.
type FriendChallengeServiceClient interface {
	// ListIncoming returns challenges where the authenticated user is the
	// opponent and hasn't yet submitted their solution.
	ListIncoming(ctx context.Context, in *ListIncomingRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error)
	// ListSent returns challenges the authenticated user originated (pending
	// opponent response or in progress).
	ListSent(ctx context.Context, in *ListSentRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error)
	// ListHistory returns completed (won/lost/expired/declined) challenges.
	ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error)
	// SendChallenge creates a new challenge addressed to a friend by username.
	SendChallenge(ctx context.Context, in *SendChallengeRequest, opts ...grpc.CallOption) (*SendChallengeResponse, error)
	// SubmitSolution records a player's completion time + score. When both
	// sides have submitted, the row transitions to COMPLETED and a winner is
	// assigned.
	SubmitSolution(ctx context.Context, in *SubmitSolutionRequest, opts ...grpc.CallOption) (*SubmitSolutionResponse, error)
	// Decline lets the opponent refuse a challenge before they start.
	Decline(ctx context.Context, in *DeclineRequest, opts ...grpc.CallOption) (*DeclineResponse, error)
}

type friendChallengeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendChallengeServiceClient(cc grpc.ClientConnInterface) FriendChallengeServiceClient {
	return &friendChallengeServiceClient{cc}
}

func (c *friendChallengeServiceClient) ListIncoming(ctx context.Context, in *ListIncomingRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChallengesResponse)
	err := c.cc.Invoke(ctx, FriendChallengeService_ListIncoming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendChallengeServiceClient) ListSent(ctx context.Context, in *ListSentRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChallengesResponse)
	err := c.cc.Invoke(ctx, FriendChallengeService_ListSent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendChallengeServiceClient) ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListChallengesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChallengesResponse)
	err := c.cc.Invoke(ctx, FriendChallengeService_ListHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendChallengeServiceClient) SendChallenge(ctx context.Context, in *SendChallengeRequest, opts ...grpc.CallOption) (*SendChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChallengeResponse)
	err := c.cc.Invoke(ctx, FriendChallengeService_SendChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendChallengeServiceClient) SubmitSolution(ctx context.Context, in *SubmitSolutionRequest, opts ...grpc.CallOption) (*SubmitSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitSolutionResponse)
	err := c.cc.Invoke(ctx, FriendChallengeService_SubmitSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendChallengeServiceClient) Decline(ctx context.Context, in *DeclineRequest, opts ...grpc.CallOption) (*DeclineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclineResponse)
	err := c.cc.Invoke(ctx, FriendChallengeService_Decline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendChallengeServiceServer is the server API for FriendChallengeService service.
// All implementations must embed UnimplementedFriendChallengeServiceServer
// for forward compatibility.
//
// FriendChallengeService handles asynchronous 1v1 task duels between friends.
// Unlike live arena matches, both players solve the same task on their own
// schedule within a 48-hour window; the faster-and-more-correct submission
// wins.
type FriendChallengeServiceServer interface {
	// ListIncoming returns challenges where the authenticated user is the
	// opponent and hasn't yet submitted their solution.
	ListIncoming(context.Context, *ListIncomingRequest) (*ListChallengesResponse, error)
	// ListSent returns challenges the authenticated user originated (pending
	// opponent response or in progress).
	ListSent(context.Context, *ListSentRequest) (*ListChallengesResponse, error)
	// ListHistory returns completed (won/lost/expired/declined) challenges.
	ListHistory(context.Context, *ListHistoryRequest) (*ListChallengesResponse, error)
	// SendChallenge creates a new challenge addressed to a friend by username.
	SendChallenge(context.Context, *SendChallengeRequest) (*SendChallengeResponse, error)
	// SubmitSolution records a player's completion time + score. When both
	// sides have submitted, the row transitions to COMPLETED and a winner is
	// assigned.
	SubmitSolution(context.Context, *SubmitSolutionRequest) (*SubmitSolutionResponse, error)
	// Decline lets the opponent refuse a challenge before they start.
	Decline(context.Context, *DeclineRequest) (*DeclineResponse, error)
	mustEmbedUnimplementedFriendChallengeServiceServer()
}

// UnimplementedFriendChallengeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendChallengeServiceServer struct{}

func (UnimplementedFriendChallengeServiceServer) ListIncoming(context.Context, *ListIncomingRequest) (*ListChallengesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIncoming not implemented")
}
func (UnimplementedFriendChallengeServiceServer) ListSent(context.Context, *ListSentRequest) (*ListChallengesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSent not implemented")
}
func (UnimplementedFriendChallengeServiceServer) ListHistory(context.Context, *ListHistoryRequest) (*ListChallengesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHistory not implemented")
}
func (UnimplementedFriendChallengeServiceServer) SendChallenge(context.Context, *SendChallengeRequest) (*SendChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendChallenge not implemented")
}
func (UnimplementedFriendChallengeServiceServer) SubmitSolution(context.Context, *SubmitSolutionRequest) (*SubmitSolutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSolution not implemented")
}
func (UnimplementedFriendChallengeServiceServer) Decline(context.Context, *DeclineRequest) (*DeclineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decline not implemented")
}
func (UnimplementedFriendChallengeServiceServer) mustEmbedUnimplementedFriendChallengeServiceServer() {
}
func (UnimplementedFriendChallengeServiceServer) testEmbeddedByValue() {}

// UnsafeFriendChallengeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendChallengeServiceServer will
// result in compilation errors.
type UnsafeFriendChallengeServiceServer interface {
	mustEmbedUnimplementedFriendChallengeServiceServer()
}

func RegisterFriendChallengeServiceServer(s grpc.ServiceRegistrar, srv FriendChallengeServiceServer) {
	// If the following call panics, it indicates UnimplementedFriendChallengeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FriendChallengeService_ServiceDesc, srv)
}

func _FriendChallengeService_ListIncoming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIncomingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendChallengeServiceServer).ListIncoming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendChallengeService_ListIncoming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendChallengeServiceServer).ListIncoming(ctx, req.(*ListIncomingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendChallengeService_ListSent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendChallengeServiceServer).ListSent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendChallengeService_ListSent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendChallengeServiceServer).ListSent(ctx, req.(*ListSentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendChallengeService_ListHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendChallengeServiceServer).ListHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendChallengeService_ListHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendChallengeServiceServer).ListHistory(ctx, req.(*ListHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendChallengeService_SendChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendChallengeServiceServer).SendChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendChallengeService_SendChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendChallengeServiceServer).SendChallenge(ctx, req.(*SendChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendChallengeService_SubmitSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendChallengeServiceServer).SubmitSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendChallengeService_SubmitSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendChallengeServiceServer).SubmitSolution(ctx, req.(*SubmitSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendChallengeService_Decline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendChallengeServiceServer).Decline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendChallengeService_Decline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendChallengeServiceServer).Decline(ctx, req.(*DeclineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FriendChallengeService_ServiceDesc is the grpc.ServiceDesc for FriendChallengeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendChallengeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friend_challenge.v1.FriendChallengeService",
	HandlerType: (*FriendChallengeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIncoming",
			Handler:    _FriendChallengeService_ListIncoming_Handler,
		},
		{
			MethodName: "ListSent",
			Handler:    _FriendChallengeService_ListSent_Handler,
		},
		{
			MethodName: "ListHistory",
			Handler:    _FriendChallengeService_ListHistory_Handler,
		},
		{
			MethodName: "SendChallenge",
			Handler:    _FriendChallengeService_SendChallenge_Handler,
		},
		{
			MethodName: "SubmitSolution",
			Handler:    _FriendChallengeService_SubmitSolution_Handler,
		},
		{
			MethodName: "Decline",
			Handler:    _FriendChallengeService_Decline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game/friend_challenge/v1/friend_challenge.proto",
}
